/**
 * Deterministic CSS-variable generation from the token objects.
 *
 * dot-notation `color.status.green` -> CSS var `--odp-color-status-green`
 * (tokens doc §1.1). The three representations (spec / CSS / TS) are kept in
 * lock-step by GENERATING the CSS from the TS values rather than hand-copying.
 */
import {
  fontFamily,
  fontSize,
  fontWeight,
  lineHeight,
  space,
  radius,
  elevation,
  zIndex,
  breakpoint,
  layout,
  motion,
} from "./primitives.ts";
import { colorThemes, density, type ThemeName } from "./themes.ts";

const toVar = (dotName: string): string =>
  "--odp-" + dotName.replace(/\./g, "-").replace(/_/g, "-");

function block(entries: Record<string, string | number>, prefix = ""): string {
  return Object.entries(entries)
    .map(([k, v]) => `  ${toVar(prefix ? `${prefix}.${k}` : k)}: ${v};`)
    .join("\n");
}

/** Scale tokens that are theme-invariant (typography / spacing / motion / layout). */
function scaleVars(): string {
  const lines: string[] = [];
  lines.push(block(fontFamily, "font.family"));
  lines.push(block(fontSize, "font.size"));
  lines.push(block(fontWeight, "font.weight"));
  lines.push(block(lineHeight, "line-height"));
  lines.push(block(space, "space"));
  lines.push(block(radius, "radius"));
  lines.push(block(elevation, "elevation"));
  lines.push(block(zIndex, "z"));
  lines.push(block(breakpoint, "breakpoint"));
  lines.push(block(layout, "layout"));
  lines.push(block(motion.duration, "motion.duration"));
  lines.push(block(motion.easing, "motion.easing"));
  return lines.join("\n");
}

/** Full CSS for `:root` (light) plus `[data-theme]` / `[data-density]` selectors. */
export function generateCss(): string {
  const themeNames = Object.keys(colorThemes) as ThemeName[];
  const parts: string[] = [];

  parts.push("/* AUTO-GENERATED by @oday-plus/design-tokens — do not edit by hand. */");
  parts.push("/* Source values: docs/design/ODAY_PLUS_DESIGN_TOKENS.md */");

  // :root = scale tokens + light color theme + comfortable density default.
  parts.push(
    `:root {\n${scaleVars()}\n${block(colorThemes.light)}\n${block(
      density.comfortable,
    )}\n}`,
  );

  // Theme overrides (light included for explicitness on [data-theme="light"]).
  for (const name of themeNames) {
    parts.push(`[data-theme="${name}"] {\n${block(colorThemes[name])}\n}`);
  }

  // Density overrides.
  for (const [name, vals] of Object.entries(density)) {
    parts.push(`[data-density="${name}"] {\n${block(vals)}\n}`);
  }

  return parts.join("\n\n") + "\n";
}

export { toVar as tokenToCssVar };
