# Generated by packages/oday_data_contracts_client/codegen.py -- do not edit.
#
# Contract:  emgi.coverage.v4.1 (kernel, v4.1.0)
# Release:   oday-data-foundation-contracts.v0.4.1
# Producer:  alfloop-dev/oday-data-platform@3f0bd995bbd2248a9cff9176f27ed0e39d25948f
# Schema:    schemas/coverage.schema.json
# Digest:    84eaa0217c1b90c6a894076be79728e51deadbd0e03e07c262e9126b1ff4982e
"""Canonical contract schema for entity-partition coverage proofs and valid-zero reconciliation across dataset, scope, entity, business date, geometry, and time window in EMGI v0.4.1."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Any

CONTRACT_ID = "emgi.coverage.v4.1"
CONTRACT_VERSION = "4.1.0"
CONTRACT_CATEGORY = "kernel"
SCHEMA_FILE = "schemas/coverage.schema.json"
SCHEMA_SHA256 = "84eaa0217c1b90c6a894076be79728e51deadbd0e03e07c262e9126b1ff4982e"
ROOT_MODEL = "Coverage"


@dataclass(frozen=True, slots=True)
class Coverage:
    """Canonical contract schema for entity-partition coverage proofs and valid-zero reconciliation across dataset, scope, entity, business date, geometry, and time window in EMGI v0.4.1.

    Root model of contract `emgi.coverage.v4.1`
    (kernel, version 4.1.0).
    """

    coverage_id: str
    dataset_id: str
    is_complete: bool
    scope_principal_id: str
    state: str
    available_at: str | None = None
    business_date: str | None = None
    contract_version: str = "emgi.coverage.v4.1"
    dataset_version_id: str | None = None
    entity_id: str | None = None
    entity_type: str | None = None
    error_detail: str | None = None
    expected_count: int | None = None
    knowledge_as_of: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    negative_evidence_valid: bool = False
    observation_ids: list[str] = field(default_factory=list)
    observed_count: int = 0
    quarantine_reason: str | None = None
    query_geometry: dict[str, Any] | None = None
    reconciled_at: str | None = None
    reconciliation_run_id: str | None = None
    saturation_limit: float | None = None
    search_execution_ids: list[str] = field(default_factory=list)
    store_timezone: str = "Asia/Taipei"
    sub_partitions: list[dict[str, Any]] = field(default_factory=list)
    tenant_id: str | None = None
    time_window: dict[str, Any] | None = None
    truncation_limit: int | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Coverage:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["coverage_id"] = data["coverage_id"]
        values["dataset_id"] = data["dataset_id"]
        values["is_complete"] = data["is_complete"]
        values["scope_principal_id"] = data["scope_principal_id"]
        values["state"] = data["state"]
        if "available_at" in data:
            values["available_at"] = data["available_at"]
        if "business_date" in data:
            values["business_date"] = data["business_date"]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "dataset_version_id" in data:
            values["dataset_version_id"] = data["dataset_version_id"]
        if "entity_id" in data:
            values["entity_id"] = data["entity_id"]
        if "entity_type" in data:
            values["entity_type"] = data["entity_type"]
        if "error_detail" in data:
            values["error_detail"] = data["error_detail"]
        if "expected_count" in data:
            values["expected_count"] = data["expected_count"]
        if "knowledge_as_of" in data:
            values["knowledge_as_of"] = data["knowledge_as_of"]
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        if "negative_evidence_valid" in data:
            values["negative_evidence_valid"] = data["negative_evidence_valid"]
        if "observation_ids" in data:
            values["observation_ids"] = list(data["observation_ids"])
        if "observed_count" in data:
            values["observed_count"] = data["observed_count"]
        if "quarantine_reason" in data:
            values["quarantine_reason"] = data["quarantine_reason"]
        if "query_geometry" in data:
            values["query_geometry"] = data["query_geometry"]
        if "reconciled_at" in data:
            values["reconciled_at"] = data["reconciled_at"]
        if "reconciliation_run_id" in data:
            values["reconciliation_run_id"] = data["reconciliation_run_id"]
        if "saturation_limit" in data:
            values["saturation_limit"] = data["saturation_limit"]
        if "search_execution_ids" in data:
            values["search_execution_ids"] = list(data["search_execution_ids"])
        if "store_timezone" in data:
            values["store_timezone"] = data["store_timezone"]
        if "sub_partitions" in data:
            values["sub_partitions"] = list(data["sub_partitions"])
        if "tenant_id" in data:
            values["tenant_id"] = data["tenant_id"]
        if "time_window" in data:
            values["time_window"] = data["time_window"]
        if "truncation_limit" in data:
            values["truncation_limit"] = data["truncation_limit"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["coverage_id"] = self.coverage_id
        data["dataset_id"] = self.dataset_id
        data["is_complete"] = self.is_complete
        data["scope_principal_id"] = self.scope_principal_id
        data["state"] = self.state
        if self.available_at is not None:
            data["available_at"] = self.available_at
        if self.business_date is not None:
            data["business_date"] = self.business_date
        data["contract_version"] = self.contract_version
        if self.dataset_version_id is not None:
            data["dataset_version_id"] = self.dataset_version_id
        if self.entity_id is not None:
            data["entity_id"] = self.entity_id
        if self.entity_type is not None:
            data["entity_type"] = self.entity_type
        if self.error_detail is not None:
            data["error_detail"] = self.error_detail
        if self.expected_count is not None:
            data["expected_count"] = self.expected_count
        if self.knowledge_as_of is not None:
            data["knowledge_as_of"] = self.knowledge_as_of
        data["metadata"] = self.metadata
        data["negative_evidence_valid"] = self.negative_evidence_valid
        data["observation_ids"] = list(self.observation_ids)
        data["observed_count"] = self.observed_count
        if self.quarantine_reason is not None:
            data["quarantine_reason"] = self.quarantine_reason
        if self.query_geometry is not None:
            data["query_geometry"] = self.query_geometry
        if self.reconciled_at is not None:
            data["reconciled_at"] = self.reconciled_at
        if self.reconciliation_run_id is not None:
            data["reconciliation_run_id"] = self.reconciliation_run_id
        if self.saturation_limit is not None:
            data["saturation_limit"] = self.saturation_limit
        data["search_execution_ids"] = list(self.search_execution_ids)
        data["store_timezone"] = self.store_timezone
        data["sub_partitions"] = list(self.sub_partitions)
        if self.tenant_id is not None:
            data["tenant_id"] = self.tenant_id
        if self.time_window is not None:
            data["time_window"] = self.time_window
        if self.truncation_limit is not None:
            data["truncation_limit"] = self.truncation_limit
        return data

