# Generated by packages/oday_data_contracts_client/codegen.py -- do not edit.
#
# Contract:  emgi.manifests.v4.1 (manifests, v4.1.0)
# Release:   oday-data-foundation-contracts.v0.4.1
# Producer:  alfloop-dev/oday-data-platform@3f0bd995bbd2248a9cff9176f27ed0e39d25948f
# Schema:    schemas/manifests/manifests.schema.json
# Digest:    d618ee198004c844d193794d688512db2f6935968e14b72c339411c6c58d5366
"""EMGI Universal Manifest Document v4.1"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

CONTRACT_ID = "emgi.manifests.v4.1"
CONTRACT_VERSION = "4.1.0"
CONTRACT_CATEGORY = "manifests"
SCHEMA_FILE = "schemas/manifests/manifests.schema.json"
SCHEMA_SHA256 = "d618ee198004c844d193794d688512db2f6935968e14b72c339411c6c58d5366"
ROOT_MODEL = "ManifestDocument"


class LabelStatus(StrEnum):
    """Maturity and availability status of a label value."""

    MATURE = "MATURE"
    CENSORED = "CENSORED"
    UNAVAILABLE = "UNAVAILABLE"
    INCOMPLETE = "INCOMPLETE"
    RETRACTED = "RETRACTED"


class ManifestStatus(StrEnum):
    """Lifecycle status of a manifest."""

    DRAFT = "DRAFT"
    SEALED = "SEALED"
    PUBLISHED = "PUBLISHED"
    SUPERSEDED = "SUPERSEDED"
    QUARANTINED = "QUARANTINED"
    DEPRECATED = "DEPRECATED"


class MaterializationEnvironment(StrEnum):
    """MaterializationEnvironment"""

    development = "development"
    test = "test"
    production = "production"


class MaterializationKind(StrEnum):
    """MaterializationKind"""

    observation = "observation"
    feature = "feature"
    label = "label"


class MeasurementState(StrEnum):
    """Canonical observation, degradation, and missingness states for measurements."""

    observed = "observed"
    partial = "partial"
    stale = "stale"
    uncollected = "uncollected"
    unlicensed = "unlicensed"
    unauthorized = "unauthorized"
    quarantined = "quarantined"
    source_error = "source_error"
    saturated = "saturated"
    truncated = "truncated"


class ProductComponentKind(StrEnum):
    """Component domains composing a published data product."""

    GEOGRAPHY = "GEOGRAPHY"
    DEMOGRAPHICS = "DEMOGRAPHICS"
    POI = "POI"
    COMPETITOR = "COMPETITOR"
    RENT = "RENT"
    TRANSPORT = "TRANSPORT"
    MOBILITY = "MOBILITY"
    EVENTS = "EVENTS"
    COVERAGE = "COVERAGE"
    ACQUISITION = "ACQUISITION"
    FEATURE_SET = "FEATURE_SET"
    MODEL_PREDICTION = "MODEL_PREDICTION"
    CUSTOM = "CUSTOM"


class SplitPartition(StrEnum):
    """Role assigned to a partition split in model training and evaluation."""

    TRAIN = "TRAIN"
    VALIDATION = "VALIDATION"
    TEST = "TEST"
    HOLDOUT = "HOLDOUT"
    SHADOW = "SHADOW"


class SplitStrategy(StrEnum):
    """Partitioning strategy for training instances."""

    TEMPORAL = "TEMPORAL"
    SPATIAL = "SPATIAL"
    RANDOM = "RANDOM"
    ENTITY_GROUP = "ENTITY_GROUP"
    STRATIFIED = "STRATIFIED"


@dataclass(frozen=True, slots=True)
class CoverageReference:
    """Entity-partition coverage reference proving observation completeness."""

    coverage_id: str
    dataset_version_id: str | None = None
    entity_id: str | None = None
    expected_count: int | None = None
    is_complete: bool = False
    observed_count: int | None = None
    partition_id: str | None = None
    reconciled_at: str | None = None
    scope: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> CoverageReference:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["coverage_id"] = data["coverage_id"]
        if "dataset_version_id" in data:
            values["dataset_version_id"] = data["dataset_version_id"]
        if "entity_id" in data:
            values["entity_id"] = data["entity_id"]
        if "expected_count" in data:
            values["expected_count"] = data["expected_count"]
        if "is_complete" in data:
            values["is_complete"] = data["is_complete"]
        if "observed_count" in data:
            values["observed_count"] = data["observed_count"]
        if "partition_id" in data:
            values["partition_id"] = data["partition_id"]
        if "reconciled_at" in data:
            values["reconciled_at"] = data["reconciled_at"]
        if "scope" in data:
            values["scope"] = data["scope"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["coverage_id"] = self.coverage_id
        if self.dataset_version_id is not None:
            data["dataset_version_id"] = self.dataset_version_id
        if self.entity_id is not None:
            data["entity_id"] = self.entity_id
        if self.expected_count is not None:
            data["expected_count"] = self.expected_count
        data["is_complete"] = self.is_complete
        if self.observed_count is not None:
            data["observed_count"] = self.observed_count
        if self.partition_id is not None:
            data["partition_id"] = self.partition_id
        if self.reconciled_at is not None:
            data["reconciled_at"] = self.reconciled_at
        if self.scope is not None:
            data["scope"] = self.scope
        return data


@dataclass(frozen=True, slots=True)
class FeatureEntityRecord:
    """Point-in-time feature values for a single entity."""

    entity_id: str
    available_at: str | None = None
    coverage_ref: str | None = None
    features: dict[str, Any] | None = None
    missing_count: int = 0
    observed_at: str | None = None
    valid_zero_proven: bool = False

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> FeatureEntityRecord:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["entity_id"] = data["entity_id"]
        if "available_at" in data:
            values["available_at"] = data["available_at"]
        if "coverage_ref" in data:
            values["coverage_ref"] = data["coverage_ref"]
        if "features" in data:
            values["features"] = data["features"]
        if "missing_count" in data:
            values["missing_count"] = data["missing_count"]
        if "observed_at" in data:
            values["observed_at"] = data["observed_at"]
        if "valid_zero_proven" in data:
            values["valid_zero_proven"] = data["valid_zero_proven"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["entity_id"] = self.entity_id
        if self.available_at is not None:
            data["available_at"] = self.available_at
        if self.coverage_ref is not None:
            data["coverage_ref"] = self.coverage_ref
        if self.features is not None:
            data["features"] = self.features
        data["missing_count"] = self.missing_count
        if self.observed_at is not None:
            data["observed_at"] = self.observed_at
        data["valid_zero_proven"] = self.valid_zero_proven
        return data


@dataclass(frozen=True, slots=True)
class FeatureManifest:
    """Point-in-time feature manifest for entity cohorts with strict cutoff validation."""

    entity_type: str
    feature_set_name: str
    feature_set_version: str
    manifest_id: str
    time_contract: TimeContract
    content_digest: str | None = None
    contract_version: str = "emgi.manifests.v4.1"
    created_at: str | None = None
    created_by: str | None = None
    entity_count: int = 0
    feature_names: list[str] = field(default_factory=list)
    manifest_kind: str = "feature"
    manifest_status: ManifestStatus = ManifestStatus.SEALED
    metadata: dict[str, Any] | None = None
    records: list[FeatureEntityRecord] = field(default_factory=list)
    source_manifest_ids: list[str] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> FeatureManifest:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["entity_type"] = data["entity_type"]
        values["feature_set_name"] = data["feature_set_name"]
        values["feature_set_version"] = data["feature_set_version"]
        values["manifest_id"] = data["manifest_id"]
        values["time_contract"] = TimeContract.from_dict(data["time_contract"])
        if "content_digest" in data:
            values["content_digest"] = data["content_digest"]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "created_at" in data:
            values["created_at"] = data["created_at"]
        if "created_by" in data:
            values["created_by"] = data["created_by"]
        if "entity_count" in data:
            values["entity_count"] = data["entity_count"]
        if "feature_names" in data:
            values["feature_names"] = list(data["feature_names"])
        if "manifest_kind" in data:
            values["manifest_kind"] = data["manifest_kind"]
        if "manifest_status" in data:
            values["manifest_status"] = ManifestStatus(data["manifest_status"])
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        if "records" in data:
            values["records"] = [FeatureEntityRecord.from_dict(item) for item in data["records"]]
        if "source_manifest_ids" in data:
            values["source_manifest_ids"] = list(data["source_manifest_ids"])
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["entity_type"] = self.entity_type
        data["feature_set_name"] = self.feature_set_name
        data["feature_set_version"] = self.feature_set_version
        data["manifest_id"] = self.manifest_id
        data["time_contract"] = self.time_contract.to_dict()
        if self.content_digest is not None:
            data["content_digest"] = self.content_digest
        data["contract_version"] = self.contract_version
        if self.created_at is not None:
            data["created_at"] = self.created_at
        if self.created_by is not None:
            data["created_by"] = self.created_by
        data["entity_count"] = self.entity_count
        data["feature_names"] = list(self.feature_names)
        data["manifest_kind"] = self.manifest_kind
        data["manifest_status"] = self.manifest_status.value
        if self.metadata is not None:
            data["metadata"] = self.metadata
        data["records"] = [item.to_dict() for item in self.records]
        data["source_manifest_ids"] = list(self.source_manifest_ids)
        return data


@dataclass(frozen=True, slots=True)
class LabelEntityRecord:
    """Ground truth outcome label evaluated over a future observation window."""

    entity_id: str
    label_name: str
    observation_window_end: str
    observation_window_start: str
    censoring_reason: str | None = None
    envelope: MeasurementEnvelope | None = None
    matured_at: str | None = None
    status: LabelStatus = LabelStatus.MATURE
    value: Any = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> LabelEntityRecord:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["entity_id"] = data["entity_id"]
        values["label_name"] = data["label_name"]
        values["observation_window_end"] = data["observation_window_end"]
        values["observation_window_start"] = data["observation_window_start"]
        if "censoring_reason" in data:
            values["censoring_reason"] = data["censoring_reason"]
        if "envelope" in data:
            values["envelope"] = None if data["envelope"] is None else MeasurementEnvelope.from_dict(data["envelope"])
        if "matured_at" in data:
            values["matured_at"] = data["matured_at"]
        if "status" in data:
            values["status"] = LabelStatus(data["status"])
        if "value" in data:
            values["value"] = data["value"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["entity_id"] = self.entity_id
        data["label_name"] = self.label_name
        data["observation_window_end"] = self.observation_window_end
        data["observation_window_start"] = self.observation_window_start
        if self.censoring_reason is not None:
            data["censoring_reason"] = self.censoring_reason
        if self.envelope is not None:
            data["envelope"] = self.envelope.to_dict()
        if self.matured_at is not None:
            data["matured_at"] = self.matured_at
        data["status"] = self.status.value
        if self.value is not None:
            data["value"] = self.value
        return data


@dataclass(frozen=True, slots=True)
class LabelManifest:
    """Manifest representing future outcome labels separate from feature evidence."""

    entity_type: str
    label_set_name: str
    label_set_version: str
    manifest_id: str
    time_contract: TimeContract
    content_digest: str | None = None
    contract_version: str = "emgi.manifests.v4.1"
    created_at: str | None = None
    created_by: str | None = None
    entity_count: int = 0
    label_names: list[str] = field(default_factory=list)
    manifest_kind: str = "label"
    manifest_status: ManifestStatus = ManifestStatus.SEALED
    metadata: dict[str, Any] | None = None
    records: list[LabelEntityRecord] = field(default_factory=list)
    source_manifest_ids: list[str] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> LabelManifest:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["entity_type"] = data["entity_type"]
        values["label_set_name"] = data["label_set_name"]
        values["label_set_version"] = data["label_set_version"]
        values["manifest_id"] = data["manifest_id"]
        values["time_contract"] = TimeContract.from_dict(data["time_contract"])
        if "content_digest" in data:
            values["content_digest"] = data["content_digest"]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "created_at" in data:
            values["created_at"] = data["created_at"]
        if "created_by" in data:
            values["created_by"] = data["created_by"]
        if "entity_count" in data:
            values["entity_count"] = data["entity_count"]
        if "label_names" in data:
            values["label_names"] = list(data["label_names"])
        if "manifest_kind" in data:
            values["manifest_kind"] = data["manifest_kind"]
        if "manifest_status" in data:
            values["manifest_status"] = ManifestStatus(data["manifest_status"])
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        if "records" in data:
            values["records"] = [LabelEntityRecord.from_dict(item) for item in data["records"]]
        if "source_manifest_ids" in data:
            values["source_manifest_ids"] = list(data["source_manifest_ids"])
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["entity_type"] = self.entity_type
        data["label_set_name"] = self.label_set_name
        data["label_set_version"] = self.label_set_version
        data["manifest_id"] = self.manifest_id
        data["time_contract"] = self.time_contract.to_dict()
        if self.content_digest is not None:
            data["content_digest"] = self.content_digest
        data["contract_version"] = self.contract_version
        if self.created_at is not None:
            data["created_at"] = self.created_at
        if self.created_by is not None:
            data["created_by"] = self.created_by
        data["entity_count"] = self.entity_count
        data["label_names"] = list(self.label_names)
        data["manifest_kind"] = self.manifest_kind
        data["manifest_status"] = self.manifest_status.value
        if self.metadata is not None:
            data["metadata"] = self.metadata
        data["records"] = [item.to_dict() for item in self.records]
        data["source_manifest_ids"] = list(self.source_manifest_ids)
        return data


@dataclass(frozen=True, slots=True)
class MeasurementEnvelope:
    """Envelope encapsulating a metric value, missingness classification, and negative evidence."""

    metric_name: str
    state: MeasurementState
    confidence: float | None = None
    contract_version: str = "emgi.measurement-envelope.v4.1"
    coverage: CoverageReference | None = None
    coverage_complete: bool | None = None
    coverage_ref: str | None = None
    dataset_id: str | None = None
    effective_from: str | None = None
    effective_to: str | None = None
    error_detail: str | None = None
    metadata: dict[str, Any] | None = None
    negative_evidence_valid: bool = False
    observed_at: str | None = None
    quarantine_reason: str | None = None
    saturation_limit: Any = None
    source_observation_id: str | None = None
    truncation_limit: int | None = None
    unit: str | None = None
    value: Any = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> MeasurementEnvelope:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["metric_name"] = data["metric_name"]
        values["state"] = MeasurementState(data["state"])
        if "confidence" in data:
            values["confidence"] = data["confidence"]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "coverage" in data:
            values["coverage"] = None if data["coverage"] is None else CoverageReference.from_dict(data["coverage"])
        if "coverage_complete" in data:
            values["coverage_complete"] = data["coverage_complete"]
        if "coverage_ref" in data:
            values["coverage_ref"] = data["coverage_ref"]
        if "dataset_id" in data:
            values["dataset_id"] = data["dataset_id"]
        if "effective_from" in data:
            values["effective_from"] = data["effective_from"]
        if "effective_to" in data:
            values["effective_to"] = data["effective_to"]
        if "error_detail" in data:
            values["error_detail"] = data["error_detail"]
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        if "negative_evidence_valid" in data:
            values["negative_evidence_valid"] = data["negative_evidence_valid"]
        if "observed_at" in data:
            values["observed_at"] = data["observed_at"]
        if "quarantine_reason" in data:
            values["quarantine_reason"] = data["quarantine_reason"]
        if "saturation_limit" in data:
            values["saturation_limit"] = data["saturation_limit"]
        if "source_observation_id" in data:
            values["source_observation_id"] = data["source_observation_id"]
        if "truncation_limit" in data:
            values["truncation_limit"] = data["truncation_limit"]
        if "unit" in data:
            values["unit"] = data["unit"]
        if "value" in data:
            values["value"] = data["value"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["metric_name"] = self.metric_name
        data["state"] = self.state.value
        if self.confidence is not None:
            data["confidence"] = self.confidence
        data["contract_version"] = self.contract_version
        if self.coverage is not None:
            data["coverage"] = self.coverage.to_dict()
        if self.coverage_complete is not None:
            data["coverage_complete"] = self.coverage_complete
        if self.coverage_ref is not None:
            data["coverage_ref"] = self.coverage_ref
        if self.dataset_id is not None:
            data["dataset_id"] = self.dataset_id
        if self.effective_from is not None:
            data["effective_from"] = self.effective_from
        if self.effective_to is not None:
            data["effective_to"] = self.effective_to
        if self.error_detail is not None:
            data["error_detail"] = self.error_detail
        if self.metadata is not None:
            data["metadata"] = self.metadata
        data["negative_evidence_valid"] = self.negative_evidence_valid
        if self.observed_at is not None:
            data["observed_at"] = self.observed_at
        if self.quarantine_reason is not None:
            data["quarantine_reason"] = self.quarantine_reason
        if self.saturation_limit is not None:
            data["saturation_limit"] = self.saturation_limit
        if self.source_observation_id is not None:
            data["source_observation_id"] = self.source_observation_id
        if self.truncation_limit is not None:
            data["truncation_limit"] = self.truncation_limit
        if self.unit is not None:
            data["unit"] = self.unit
        if self.value is not None:
            data["value"] = self.value
        return data


@dataclass(frozen=True, slots=True)
class ProductComponentRef:
    """Content-addressed component reference forming part of a published data product."""

    component_id: str
    component_kind: ProductComponentKind
    contract_id: str
    sha256: str
    feature_manifest_id: str | None = None
    row_count: int | None = None
    size_bytes: int | None = None
    source_manifest_id: str | None = None
    storage_uri: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> ProductComponentRef:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["component_id"] = data["component_id"]
        values["component_kind"] = ProductComponentKind(data["component_kind"])
        values["contract_id"] = data["contract_id"]
        values["sha256"] = data["sha256"]
        if "feature_manifest_id" in data:
            values["feature_manifest_id"] = data["feature_manifest_id"]
        if "row_count" in data:
            values["row_count"] = data["row_count"]
        if "size_bytes" in data:
            values["size_bytes"] = data["size_bytes"]
        if "source_manifest_id" in data:
            values["source_manifest_id"] = data["source_manifest_id"]
        if "storage_uri" in data:
            values["storage_uri"] = data["storage_uri"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["component_id"] = self.component_id
        data["component_kind"] = self.component_kind.value
        data["contract_id"] = self.contract_id
        data["sha256"] = self.sha256
        if self.feature_manifest_id is not None:
            data["feature_manifest_id"] = self.feature_manifest_id
        if self.row_count is not None:
            data["row_count"] = self.row_count
        if self.size_bytes is not None:
            data["size_bytes"] = self.size_bytes
        if self.source_manifest_id is not None:
            data["source_manifest_id"] = self.source_manifest_id
        if self.storage_uri is not None:
            data["storage_uri"] = self.storage_uri
        return data


@dataclass(frozen=True, slots=True)
class ProductManifest:
    """Manifest describing a published, immutable EMGI data product release."""

    manifest_id: str
    product_contract_id: str
    product_version: str
    time_contract: TimeContract
    components: list[ProductComponentRef] = field(default_factory=list)
    content_digest: str | None = None
    contract_version: str = "emgi.manifests.v4.1"
    created_at: str | None = None
    created_by: str | None = None
    feature_manifest_ids: list[str] = field(default_factory=list)
    manifest_kind: str = "product"
    manifest_status: ManifestStatus = ManifestStatus.SEALED
    metadata: dict[str, Any] | None = None
    quality_summary: ProductQualitySummary | None = None
    source_manifest_ids: list[str] = field(default_factory=list)
    spatial_coverage: SpatialCoverageSummary | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> ProductManifest:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["manifest_id"] = data["manifest_id"]
        values["product_contract_id"] = data["product_contract_id"]
        values["product_version"] = data["product_version"]
        values["time_contract"] = TimeContract.from_dict(data["time_contract"])
        if "components" in data:
            values["components"] = [ProductComponentRef.from_dict(item) for item in data["components"]]
        if "content_digest" in data:
            values["content_digest"] = data["content_digest"]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "created_at" in data:
            values["created_at"] = data["created_at"]
        if "created_by" in data:
            values["created_by"] = data["created_by"]
        if "feature_manifest_ids" in data:
            values["feature_manifest_ids"] = list(data["feature_manifest_ids"])
        if "manifest_kind" in data:
            values["manifest_kind"] = data["manifest_kind"]
        if "manifest_status" in data:
            values["manifest_status"] = ManifestStatus(data["manifest_status"])
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        if "quality_summary" in data:
            values["quality_summary"] = None if data["quality_summary"] is None else ProductQualitySummary.from_dict(data["quality_summary"])
        if "source_manifest_ids" in data:
            values["source_manifest_ids"] = list(data["source_manifest_ids"])
        if "spatial_coverage" in data:
            values["spatial_coverage"] = None if data["spatial_coverage"] is None else SpatialCoverageSummary.from_dict(data["spatial_coverage"])
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["manifest_id"] = self.manifest_id
        data["product_contract_id"] = self.product_contract_id
        data["product_version"] = self.product_version
        data["time_contract"] = self.time_contract.to_dict()
        data["components"] = [item.to_dict() for item in self.components]
        if self.content_digest is not None:
            data["content_digest"] = self.content_digest
        data["contract_version"] = self.contract_version
        if self.created_at is not None:
            data["created_at"] = self.created_at
        if self.created_by is not None:
            data["created_by"] = self.created_by
        data["feature_manifest_ids"] = list(self.feature_manifest_ids)
        data["manifest_kind"] = self.manifest_kind
        data["manifest_status"] = self.manifest_status.value
        if self.metadata is not None:
            data["metadata"] = self.metadata
        if self.quality_summary is not None:
            data["quality_summary"] = self.quality_summary.to_dict()
        data["source_manifest_ids"] = list(self.source_manifest_ids)
        if self.spatial_coverage is not None:
            data["spatial_coverage"] = self.spatial_coverage.to_dict()
        return data


@dataclass(frozen=True, slots=True)
class ProductQualitySummary:
    """Quality, valid-zero proof, and missingness metrics for product entities."""

    total_entities: int
    completeness_ratio: float = 1.0
    fully_observed_count: int = 0
    missing_count: int = 0
    partial_count: int = 0
    quarantined_count: int = 0
    valid_zero_count: int = 0

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> ProductQualitySummary:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["total_entities"] = data["total_entities"]
        if "completeness_ratio" in data:
            values["completeness_ratio"] = data["completeness_ratio"]
        if "fully_observed_count" in data:
            values["fully_observed_count"] = data["fully_observed_count"]
        if "missing_count" in data:
            values["missing_count"] = data["missing_count"]
        if "partial_count" in data:
            values["partial_count"] = data["partial_count"]
        if "quarantined_count" in data:
            values["quarantined_count"] = data["quarantined_count"]
        if "valid_zero_count" in data:
            values["valid_zero_count"] = data["valid_zero_count"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["total_entities"] = self.total_entities
        data["completeness_ratio"] = self.completeness_ratio
        data["fully_observed_count"] = self.fully_observed_count
        data["missing_count"] = self.missing_count
        data["partial_count"] = self.partial_count
        data["quarantined_count"] = self.quarantined_count
        data["valid_zero_count"] = self.valid_zero_count
        return data


@dataclass(frozen=True, slots=True)
class SourceDatasetRef:
    """Reference to a registered source dataset and version."""

    dataset_id: str
    dataset_version_id: str
    content_digest: str | None = None
    observation_count: int = 0
    provider_id: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SourceDatasetRef:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["dataset_id"] = data["dataset_id"]
        values["dataset_version_id"] = data["dataset_version_id"]
        if "content_digest" in data:
            values["content_digest"] = data["content_digest"]
        if "observation_count" in data:
            values["observation_count"] = data["observation_count"]
        if "provider_id" in data:
            values["provider_id"] = data["provider_id"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["dataset_id"] = self.dataset_id
        data["dataset_version_id"] = self.dataset_version_id
        if self.content_digest is not None:
            data["content_digest"] = self.content_digest
        data["observation_count"] = self.observation_count
        if self.provider_id is not None:
            data["provider_id"] = self.provider_id
        return data


@dataclass(frozen=True, slots=True)
class SourceManifest:
    """Manifest describing the source evidence universe ingested as of a point in time."""

    manifest_id: str
    time_contract: TimeContract
    blob_ids: list[str] = field(default_factory=list)
    content_digest: str | None = None
    contract_version: str = "emgi.manifests.v4.1"
    coverage_refs: list[str] = field(default_factory=list)
    created_at: str | None = None
    created_by: str | None = None
    dataset_version_ids: list[str] = field(default_factory=list)
    datasets: list[SourceDatasetRef] = field(default_factory=list)
    item_digests: dict[str, Any] | None = None
    manifest_kind: str = "source"
    manifest_status: ManifestStatus = ManifestStatus.SEALED
    metadata: dict[str, Any] | None = None
    observation_ids: list[str] = field(default_factory=list)
    record_count: int = 0
    retraction_ids: list[str] = field(default_factory=list)
    scope_principal_id: str | None = None
    search_execution_ids: list[str] = field(default_factory=list)
    source_plane: str = "emgi-source-evidence"

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SourceManifest:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["manifest_id"] = data["manifest_id"]
        values["time_contract"] = TimeContract.from_dict(data["time_contract"])
        if "blob_ids" in data:
            values["blob_ids"] = list(data["blob_ids"])
        if "content_digest" in data:
            values["content_digest"] = data["content_digest"]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "coverage_refs" in data:
            values["coverage_refs"] = list(data["coverage_refs"])
        if "created_at" in data:
            values["created_at"] = data["created_at"]
        if "created_by" in data:
            values["created_by"] = data["created_by"]
        if "dataset_version_ids" in data:
            values["dataset_version_ids"] = list(data["dataset_version_ids"])
        if "datasets" in data:
            values["datasets"] = [SourceDatasetRef.from_dict(item) for item in data["datasets"]]
        if "item_digests" in data:
            values["item_digests"] = data["item_digests"]
        if "manifest_kind" in data:
            values["manifest_kind"] = data["manifest_kind"]
        if "manifest_status" in data:
            values["manifest_status"] = ManifestStatus(data["manifest_status"])
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        if "observation_ids" in data:
            values["observation_ids"] = list(data["observation_ids"])
        if "record_count" in data:
            values["record_count"] = data["record_count"]
        if "retraction_ids" in data:
            values["retraction_ids"] = list(data["retraction_ids"])
        if "scope_principal_id" in data:
            values["scope_principal_id"] = data["scope_principal_id"]
        if "search_execution_ids" in data:
            values["search_execution_ids"] = list(data["search_execution_ids"])
        if "source_plane" in data:
            values["source_plane"] = data["source_plane"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["manifest_id"] = self.manifest_id
        data["time_contract"] = self.time_contract.to_dict()
        data["blob_ids"] = list(self.blob_ids)
        if self.content_digest is not None:
            data["content_digest"] = self.content_digest
        data["contract_version"] = self.contract_version
        data["coverage_refs"] = list(self.coverage_refs)
        if self.created_at is not None:
            data["created_at"] = self.created_at
        if self.created_by is not None:
            data["created_by"] = self.created_by
        data["dataset_version_ids"] = list(self.dataset_version_ids)
        data["datasets"] = [item.to_dict() for item in self.datasets]
        if self.item_digests is not None:
            data["item_digests"] = self.item_digests
        data["manifest_kind"] = self.manifest_kind
        data["manifest_status"] = self.manifest_status.value
        if self.metadata is not None:
            data["metadata"] = self.metadata
        data["observation_ids"] = list(self.observation_ids)
        data["record_count"] = self.record_count
        data["retraction_ids"] = list(self.retraction_ids)
        if self.scope_principal_id is not None:
            data["scope_principal_id"] = self.scope_principal_id
        data["search_execution_ids"] = list(self.search_execution_ids)
        data["source_plane"] = self.source_plane
        return data


@dataclass(frozen=True, slots=True)
class SpatialCoverageSummary:
    """Spatial bounds and resolution coverage summary for product artifacts."""

    admin_codes: list[str] = field(default_factory=list)
    bbox_wgs84: list[Any] | None = None
    h3_resolution: int | None = None
    srid: int = 4326
    total_cells: int | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SpatialCoverageSummary:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        if "admin_codes" in data:
            values["admin_codes"] = list(data["admin_codes"])
        if "bbox_wgs84" in data:
            values["bbox_wgs84"] = data["bbox_wgs84"]
        if "h3_resolution" in data:
            values["h3_resolution"] = data["h3_resolution"]
        if "srid" in data:
            values["srid"] = data["srid"]
        if "total_cells" in data:
            values["total_cells"] = data["total_cells"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["admin_codes"] = list(self.admin_codes)
        if self.bbox_wgs84 is not None:
            data["bbox_wgs84"] = list(self.bbox_wgs84)
        if self.h3_resolution is not None:
            data["h3_resolution"] = self.h3_resolution
        data["srid"] = self.srid
        if self.total_cells is not None:
            data["total_cells"] = self.total_cells
        return data


@dataclass(frozen=True, slots=True)
class TimeContract:
    """Versioned temporal envelope shared by EMGI contracts. Observation fields are optional because providers do not expose every timestamp. Their absence remains explicit. Feature and label envelopes impose stronger requirements, and production materializations always need explicit knowledge and build cutoffs."""

    available_at: str | None = None
    build_at: str | None = None
    business_day_boundary: str = "00:00:00"
    contract_version: str = "emgi.time-contract.v4"
    effective_from: str | None = None
    effective_to: str | None = None
    event_time: str | None = None
    fetched_at: str | None = None
    ingested_at: str | None = None
    knowledge_as_of: str | None = None
    label_maturity_time: str | None = None
    materialization_environment: MaterializationEnvironment = MaterializationEnvironment.development
    materialization_kind: MaterializationKind = MaterializationKind.observation
    observed_at: str | None = None
    prediction_origin_time: str | None = None
    retracted_at: str | None = None
    source_published_at: str | None = None
    store_timezone: str = "Asia/Taipei"

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> TimeContract:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        if "available_at" in data:
            values["available_at"] = data["available_at"]
        if "build_at" in data:
            values["build_at"] = data["build_at"]
        if "business_day_boundary" in data:
            values["business_day_boundary"] = data["business_day_boundary"]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "effective_from" in data:
            values["effective_from"] = data["effective_from"]
        if "effective_to" in data:
            values["effective_to"] = data["effective_to"]
        if "event_time" in data:
            values["event_time"] = data["event_time"]
        if "fetched_at" in data:
            values["fetched_at"] = data["fetched_at"]
        if "ingested_at" in data:
            values["ingested_at"] = data["ingested_at"]
        if "knowledge_as_of" in data:
            values["knowledge_as_of"] = data["knowledge_as_of"]
        if "label_maturity_time" in data:
            values["label_maturity_time"] = data["label_maturity_time"]
        if "materialization_environment" in data:
            values["materialization_environment"] = MaterializationEnvironment(data["materialization_environment"])
        if "materialization_kind" in data:
            values["materialization_kind"] = MaterializationKind(data["materialization_kind"])
        if "observed_at" in data:
            values["observed_at"] = data["observed_at"]
        if "prediction_origin_time" in data:
            values["prediction_origin_time"] = data["prediction_origin_time"]
        if "retracted_at" in data:
            values["retracted_at"] = data["retracted_at"]
        if "source_published_at" in data:
            values["source_published_at"] = data["source_published_at"]
        if "store_timezone" in data:
            values["store_timezone"] = data["store_timezone"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        if self.available_at is not None:
            data["available_at"] = self.available_at
        if self.build_at is not None:
            data["build_at"] = self.build_at
        data["business_day_boundary"] = self.business_day_boundary
        data["contract_version"] = self.contract_version
        if self.effective_from is not None:
            data["effective_from"] = self.effective_from
        if self.effective_to is not None:
            data["effective_to"] = self.effective_to
        if self.event_time is not None:
            data["event_time"] = self.event_time
        if self.fetched_at is not None:
            data["fetched_at"] = self.fetched_at
        if self.ingested_at is not None:
            data["ingested_at"] = self.ingested_at
        if self.knowledge_as_of is not None:
            data["knowledge_as_of"] = self.knowledge_as_of
        if self.label_maturity_time is not None:
            data["label_maturity_time"] = self.label_maturity_time
        data["materialization_environment"] = self.materialization_environment.value
        data["materialization_kind"] = self.materialization_kind.value
        if self.observed_at is not None:
            data["observed_at"] = self.observed_at
        if self.prediction_origin_time is not None:
            data["prediction_origin_time"] = self.prediction_origin_time
        if self.retracted_at is not None:
            data["retracted_at"] = self.retracted_at
        if self.source_published_at is not None:
            data["source_published_at"] = self.source_published_at
        data["store_timezone"] = self.store_timezone
        return data


@dataclass(frozen=True, slots=True)
class TrainingManifest:
    """Manifest binding feature and label manifests with strict temporal split & provenance."""

    dataset_name: str
    dataset_version: str
    feature_manifest_ids: list[str]
    label_manifest_ids: list[str]
    manifest_id: str
    provenance: TrainingProvenance
    content_digest: str | None = None
    contract_version: str = "emgi.manifests.v4.1"
    created_at: str | None = None
    created_by: str | None = None
    feature_manifest_fingerprints: dict[str, Any] | None = None
    instance_ids_by_split: dict[str, Any] | None = None
    label_manifest_fingerprints: dict[str, Any] | None = None
    manifest_kind: str = "training"
    manifest_status: ManifestStatus = ManifestStatus.SEALED
    metadata: dict[str, Any] | None = None
    prediction_origin_cutoff: str | None = None
    split_strategy: SplitStrategy = SplitStrategy.TEMPORAL
    splits: list[TrainingSplitSpec] = field(default_factory=list)
    total_instances: int = 0

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> TrainingManifest:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["dataset_name"] = data["dataset_name"]
        values["dataset_version"] = data["dataset_version"]
        values["feature_manifest_ids"] = list(data["feature_manifest_ids"])
        values["label_manifest_ids"] = list(data["label_manifest_ids"])
        values["manifest_id"] = data["manifest_id"]
        values["provenance"] = TrainingProvenance.from_dict(data["provenance"])
        if "content_digest" in data:
            values["content_digest"] = data["content_digest"]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "created_at" in data:
            values["created_at"] = data["created_at"]
        if "created_by" in data:
            values["created_by"] = data["created_by"]
        if "feature_manifest_fingerprints" in data:
            values["feature_manifest_fingerprints"] = data["feature_manifest_fingerprints"]
        if "instance_ids_by_split" in data:
            values["instance_ids_by_split"] = data["instance_ids_by_split"]
        if "label_manifest_fingerprints" in data:
            values["label_manifest_fingerprints"] = data["label_manifest_fingerprints"]
        if "manifest_kind" in data:
            values["manifest_kind"] = data["manifest_kind"]
        if "manifest_status" in data:
            values["manifest_status"] = ManifestStatus(data["manifest_status"])
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        if "prediction_origin_cutoff" in data:
            values["prediction_origin_cutoff"] = data["prediction_origin_cutoff"]
        if "split_strategy" in data:
            values["split_strategy"] = SplitStrategy(data["split_strategy"])
        if "splits" in data:
            values["splits"] = [TrainingSplitSpec.from_dict(item) for item in data["splits"]]
        if "total_instances" in data:
            values["total_instances"] = data["total_instances"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["dataset_name"] = self.dataset_name
        data["dataset_version"] = self.dataset_version
        data["feature_manifest_ids"] = list(self.feature_manifest_ids)
        data["label_manifest_ids"] = list(self.label_manifest_ids)
        data["manifest_id"] = self.manifest_id
        data["provenance"] = self.provenance.to_dict()
        if self.content_digest is not None:
            data["content_digest"] = self.content_digest
        data["contract_version"] = self.contract_version
        if self.created_at is not None:
            data["created_at"] = self.created_at
        if self.created_by is not None:
            data["created_by"] = self.created_by
        if self.feature_manifest_fingerprints is not None:
            data["feature_manifest_fingerprints"] = self.feature_manifest_fingerprints
        if self.instance_ids_by_split is not None:
            data["instance_ids_by_split"] = self.instance_ids_by_split
        if self.label_manifest_fingerprints is not None:
            data["label_manifest_fingerprints"] = self.label_manifest_fingerprints
        data["manifest_kind"] = self.manifest_kind
        data["manifest_status"] = self.manifest_status.value
        if self.metadata is not None:
            data["metadata"] = self.metadata
        if self.prediction_origin_cutoff is not None:
            data["prediction_origin_cutoff"] = self.prediction_origin_cutoff
        data["split_strategy"] = self.split_strategy.value
        data["splits"] = [item.to_dict() for item in self.splits]
        data["total_instances"] = self.total_instances
        return data


@dataclass(frozen=True, slots=True)
class TrainingProvenance:
    """Audit provenance capturing exact reproducible pipeline execution details."""

    code_commit_sha: str
    pipeline_run_id: str
    code_repository: str = "alfloop-dev/oday-data-platform"
    environment: str = "production"
    executed_at: str | None = None
    feature_transform_version: str | None = None
    operator: str | None = None
    random_seed: int | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> TrainingProvenance:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["code_commit_sha"] = data["code_commit_sha"]
        values["pipeline_run_id"] = data["pipeline_run_id"]
        if "code_repository" in data:
            values["code_repository"] = data["code_repository"]
        if "environment" in data:
            values["environment"] = data["environment"]
        if "executed_at" in data:
            values["executed_at"] = data["executed_at"]
        if "feature_transform_version" in data:
            values["feature_transform_version"] = data["feature_transform_version"]
        if "operator" in data:
            values["operator"] = data["operator"]
        if "random_seed" in data:
            values["random_seed"] = data["random_seed"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["code_commit_sha"] = self.code_commit_sha
        data["pipeline_run_id"] = self.pipeline_run_id
        data["code_repository"] = self.code_repository
        data["environment"] = self.environment
        if self.executed_at is not None:
            data["executed_at"] = self.executed_at
        if self.feature_transform_version is not None:
            data["feature_transform_version"] = self.feature_transform_version
        if self.operator is not None:
            data["operator"] = self.operator
        if self.random_seed is not None:
            data["random_seed"] = self.random_seed
        return data


@dataclass(frozen=True, slots=True)
class TrainingSplitSpec:
    """Specification of a dataset split partition."""

    entity_count: int
    split: SplitPartition
    spatial_filter: str | None = None
    split_ratio: float | None = None
    temporal_end: str | None = None
    temporal_start: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> TrainingSplitSpec:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["entity_count"] = data["entity_count"]
        values["split"] = SplitPartition(data["split"])
        if "spatial_filter" in data:
            values["spatial_filter"] = data["spatial_filter"]
        if "split_ratio" in data:
            values["split_ratio"] = data["split_ratio"]
        if "temporal_end" in data:
            values["temporal_end"] = data["temporal_end"]
        if "temporal_start" in data:
            values["temporal_start"] = data["temporal_start"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["entity_count"] = self.entity_count
        data["split"] = self.split.value
        if self.spatial_filter is not None:
            data["spatial_filter"] = self.spatial_filter
        if self.split_ratio is not None:
            data["split_ratio"] = self.split_ratio
        if self.temporal_end is not None:
            data["temporal_end"] = self.temporal_end
        if self.temporal_start is not None:
            data["temporal_start"] = self.temporal_start
        return data


@dataclass(frozen=True, slots=True)
class ManifestDocument:
    """EMGI Universal Manifest Document v4.1

    Root model of contract `emgi.manifests.v4.1`
    (manifests, version 4.1.0).
    """

    manifest: Any
    contract_id: str = "emgi.manifests.v4.1"

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> ManifestDocument:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["manifest"] = data["manifest"]
        if "contract_id" in data:
            values["contract_id"] = data["contract_id"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["manifest"] = self.manifest
        data["contract_id"] = self.contract_id
        return data

