# Generated by packages/oday_data_contracts_client/codegen.py -- do not edit.
#
# Contract:  emgi.measurement-envelope.v4.1 (kernel, v4.1.0)
# Release:   oday-data-foundation-contracts.v0.4.1
# Producer:  alfloop-dev/oday-data-platform@3f0bd995bbd2248a9cff9176f27ed0e39d25948f
# Schema:    schemas/measurement-envelope.schema.json
# Digest:    29a5b602189b4c38f289edeb2e55b0d9b4cf790a26ee336bcd89c5153fcca656
"""Canonical contract schema for data measurements, missingness classifications, and negative evidence verification in EMGI v0.4.1."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

CONTRACT_ID = "emgi.measurement-envelope.v4.1"
CONTRACT_VERSION = "4.1.0"
CONTRACT_CATEGORY = "kernel"
SCHEMA_FILE = "schemas/measurement-envelope.schema.json"
SCHEMA_SHA256 = "29a5b602189b4c38f289edeb2e55b0d9b4cf790a26ee336bcd89c5153fcca656"
ROOT_MODEL = "MeasurementEnvelope"


@dataclass(frozen=True, slots=True)
class MeasurementEnvelope:
    """Canonical contract schema for data measurements, missingness classifications, and negative evidence verification in EMGI v0.4.1.

    Root model of contract `emgi.measurement-envelope.v4.1`
    (kernel, version 4.1.0).
    """

    contract_version: str
    metric_name: str
    state: str
    confidence: float | None = None
    coverage: dict[str, Any] | None = None
    coverage_complete: bool | None = None
    coverage_ref: str | None = None
    dataset_id: str | None = None
    effective_from: str | None = None
    effective_to: str | None = None
    error_detail: str | None = None
    metadata: dict[str, Any] | None = None
    negative_evidence_valid: bool = False
    observed_at: str | None = None
    quarantine_reason: str | None = None
    saturation_limit: float | None = None
    source_observation_id: str | None = None
    truncation_limit: int | None = None
    unit: str | None = None
    value: Any = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> MeasurementEnvelope:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["contract_version"] = data["contract_version"]
        values["metric_name"] = data["metric_name"]
        values["state"] = data["state"]
        if "confidence" in data:
            values["confidence"] = data["confidence"]
        if "coverage" in data:
            values["coverage"] = data["coverage"]
        if "coverage_complete" in data:
            values["coverage_complete"] = data["coverage_complete"]
        if "coverage_ref" in data:
            values["coverage_ref"] = data["coverage_ref"]
        if "dataset_id" in data:
            values["dataset_id"] = data["dataset_id"]
        if "effective_from" in data:
            values["effective_from"] = data["effective_from"]
        if "effective_to" in data:
            values["effective_to"] = data["effective_to"]
        if "error_detail" in data:
            values["error_detail"] = data["error_detail"]
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        if "negative_evidence_valid" in data:
            values["negative_evidence_valid"] = data["negative_evidence_valid"]
        if "observed_at" in data:
            values["observed_at"] = data["observed_at"]
        if "quarantine_reason" in data:
            values["quarantine_reason"] = data["quarantine_reason"]
        if "saturation_limit" in data:
            values["saturation_limit"] = data["saturation_limit"]
        if "source_observation_id" in data:
            values["source_observation_id"] = data["source_observation_id"]
        if "truncation_limit" in data:
            values["truncation_limit"] = data["truncation_limit"]
        if "unit" in data:
            values["unit"] = data["unit"]
        if "value" in data:
            values["value"] = data["value"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["contract_version"] = self.contract_version
        data["metric_name"] = self.metric_name
        data["state"] = self.state
        if self.confidence is not None:
            data["confidence"] = self.confidence
        if self.coverage is not None:
            data["coverage"] = self.coverage
        if self.coverage_complete is not None:
            data["coverage_complete"] = self.coverage_complete
        if self.coverage_ref is not None:
            data["coverage_ref"] = self.coverage_ref
        if self.dataset_id is not None:
            data["dataset_id"] = self.dataset_id
        if self.effective_from is not None:
            data["effective_from"] = self.effective_from
        if self.effective_to is not None:
            data["effective_to"] = self.effective_to
        if self.error_detail is not None:
            data["error_detail"] = self.error_detail
        if self.metadata is not None:
            data["metadata"] = self.metadata
        data["negative_evidence_valid"] = self.negative_evidence_valid
        if self.observed_at is not None:
            data["observed_at"] = self.observed_at
        if self.quarantine_reason is not None:
            data["quarantine_reason"] = self.quarantine_reason
        if self.saturation_limit is not None:
            data["saturation_limit"] = self.saturation_limit
        if self.source_observation_id is not None:
            data["source_observation_id"] = self.source_observation_id
        if self.truncation_limit is not None:
            data["truncation_limit"] = self.truncation_limit
        if self.unit is not None:
            data["unit"] = self.unit
        if self.value is not None:
            data["value"] = self.value
        return data

