# Generated by packages/oday_data_contracts_client/codegen.py -- do not edit.
#
# Contract:  oday.operational-start-observation.v1 (internal_analytical, v1.0.0)
# Release:   oday-data-foundation-contracts.v0.4.1
# Producer:  alfloop-dev/oday-data-platform@3f0bd995bbd2248a9cff9176f27ed0e39d25948f
# Schema:    schemas/operational-start-observation.schema.json
# Digest:    009642e121aa34e8142f847ead7b9945f3d112a6bc38e255f6f800084df3af9f
"""Observed lower bound on when a store began trading."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from enum import StrEnum
from typing import Any

CONTRACT_ID = "oday.operational-start-observation.v1"
CONTRACT_VERSION = "1.0.0"
CONTRACT_CATEGORY = "internal_analytical"
SCHEMA_FILE = "schemas/operational-start-observation.schema.json"
SCHEMA_SHA256 = "009642e121aa34e8142f847ead7b9945f3d112a6bc38e255f6f800084df3af9f"
ROOT_MODEL = "OperationalStartObservation"


class MaterializationEnvironment(StrEnum):
    """MaterializationEnvironment"""

    development = "development"
    test = "test"
    production = "production"


class MaterializationKind(StrEnum):
    """MaterializationKind"""

    observation = "observation"
    feature = "feature"
    label = "label"


class OperationalStartConfidence(StrEnum):
    """Strength of the published observation."""

    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


class OperationalStartMethod(StrEnum):
    """How the observed operational start was derived."""

    FIRST_OBSERVED_TRANSACTION = "FIRST_OBSERVED_TRANSACTION"
    PLACE_REGISTRATION = "PLACE_REGISTRATION"
    MERCHANT_REGISTRATION = "MERCHANT_REGISTRATION"
    DECLARED = "DECLARED"


@dataclass(frozen=True, slots=True)
class TimeContract:
    """Versioned temporal envelope shared by EMGI contracts. Observation fields are optional because providers do not expose every timestamp. Their absence remains explicit. Feature and label envelopes impose stronger requirements, and production materializations always need explicit knowledge and build cutoffs."""

    available_at: str | None = None
    build_at: str | None = None
    business_day_boundary: str = "00:00:00"
    contract_version: str = "emgi.time-contract.v4"
    effective_from: str | None = None
    effective_to: str | None = None
    event_time: str | None = None
    fetched_at: str | None = None
    ingested_at: str | None = None
    knowledge_as_of: str | None = None
    label_maturity_time: str | None = None
    materialization_environment: MaterializationEnvironment = MaterializationEnvironment.development
    materialization_kind: MaterializationKind = MaterializationKind.observation
    observed_at: str | None = None
    prediction_origin_time: str | None = None
    retracted_at: str | None = None
    source_published_at: str | None = None
    store_timezone: str = "Asia/Taipei"

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> TimeContract:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        if "available_at" in data:
            values["available_at"] = data["available_at"]
        if "build_at" in data:
            values["build_at"] = data["build_at"]
        if "business_day_boundary" in data:
            values["business_day_boundary"] = data["business_day_boundary"]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "effective_from" in data:
            values["effective_from"] = data["effective_from"]
        if "effective_to" in data:
            values["effective_to"] = data["effective_to"]
        if "event_time" in data:
            values["event_time"] = data["event_time"]
        if "fetched_at" in data:
            values["fetched_at"] = data["fetched_at"]
        if "ingested_at" in data:
            values["ingested_at"] = data["ingested_at"]
        if "knowledge_as_of" in data:
            values["knowledge_as_of"] = data["knowledge_as_of"]
        if "label_maturity_time" in data:
            values["label_maturity_time"] = data["label_maturity_time"]
        if "materialization_environment" in data:
            values["materialization_environment"] = MaterializationEnvironment(data["materialization_environment"])
        if "materialization_kind" in data:
            values["materialization_kind"] = MaterializationKind(data["materialization_kind"])
        if "observed_at" in data:
            values["observed_at"] = data["observed_at"]
        if "prediction_origin_time" in data:
            values["prediction_origin_time"] = data["prediction_origin_time"]
        if "retracted_at" in data:
            values["retracted_at"] = data["retracted_at"]
        if "source_published_at" in data:
            values["source_published_at"] = data["source_published_at"]
        if "store_timezone" in data:
            values["store_timezone"] = data["store_timezone"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        if self.available_at is not None:
            data["available_at"] = self.available_at
        if self.build_at is not None:
            data["build_at"] = self.build_at
        data["business_day_boundary"] = self.business_day_boundary
        data["contract_version"] = self.contract_version
        if self.effective_from is not None:
            data["effective_from"] = self.effective_from
        if self.effective_to is not None:
            data["effective_to"] = self.effective_to
        if self.event_time is not None:
            data["event_time"] = self.event_time
        if self.fetched_at is not None:
            data["fetched_at"] = self.fetched_at
        if self.ingested_at is not None:
            data["ingested_at"] = self.ingested_at
        if self.knowledge_as_of is not None:
            data["knowledge_as_of"] = self.knowledge_as_of
        if self.label_maturity_time is not None:
            data["label_maturity_time"] = self.label_maturity_time
        data["materialization_environment"] = self.materialization_environment.value
        data["materialization_kind"] = self.materialization_kind.value
        if self.observed_at is not None:
            data["observed_at"] = self.observed_at
        if self.prediction_origin_time is not None:
            data["prediction_origin_time"] = self.prediction_origin_time
        if self.retracted_at is not None:
            data["retracted_at"] = self.retracted_at
        if self.source_published_at is not None:
            data["source_published_at"] = self.source_published_at
        data["store_timezone"] = self.store_timezone
        return data


@dataclass(frozen=True, slots=True)
class OperationalStartObservation:
    """Observed lower bound on when a store began trading.

    Root model of contract `oday.operational-start-observation.v1`
    (internal_analytical, version 1.0.0).
    """

    method: OperationalStartMethod
    observation_window_end: str
    observation_window_start: str
    store_id: str
    time_contract: TimeContract
    business_day_boundary: str = "00:00:00"
    confidence: OperationalStartConfidence = OperationalStartConfidence.UNKNOWN
    contract_id: str = "oday.operational-start-observation.v1"
    contract_version: str = "1.0.0"
    evidence_ref: str | None = None
    is_left_censored: bool = False
    is_operator_truth: bool = False
    observed_start_at: str | None = None
    observed_start_business_date: str | None = None
    store_timezone: str = "Asia/Taipei"

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> OperationalStartObservation:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["method"] = OperationalStartMethod(data["method"])
        values["observation_window_end"] = data["observation_window_end"]
        values["observation_window_start"] = data["observation_window_start"]
        values["store_id"] = data["store_id"]
        values["time_contract"] = TimeContract.from_dict(data["time_contract"])
        if "business_day_boundary" in data:
            values["business_day_boundary"] = data["business_day_boundary"]
        if "confidence" in data:
            values["confidence"] = OperationalStartConfidence(data["confidence"])
        if "contract_id" in data:
            values["contract_id"] = data["contract_id"]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "evidence_ref" in data:
            values["evidence_ref"] = data["evidence_ref"]
        if "is_left_censored" in data:
            values["is_left_censored"] = data["is_left_censored"]
        if "is_operator_truth" in data:
            values["is_operator_truth"] = data["is_operator_truth"]
        if "observed_start_at" in data:
            values["observed_start_at"] = data["observed_start_at"]
        if "observed_start_business_date" in data:
            values["observed_start_business_date"] = data["observed_start_business_date"]
        if "store_timezone" in data:
            values["store_timezone"] = data["store_timezone"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["method"] = self.method.value
        data["observation_window_end"] = self.observation_window_end
        data["observation_window_start"] = self.observation_window_start
        data["store_id"] = self.store_id
        data["time_contract"] = self.time_contract.to_dict()
        data["business_day_boundary"] = self.business_day_boundary
        data["confidence"] = self.confidence.value
        data["contract_id"] = self.contract_id
        data["contract_version"] = self.contract_version
        if self.evidence_ref is not None:
            data["evidence_ref"] = self.evidence_ref
        data["is_left_censored"] = self.is_left_censored
        data["is_operator_truth"] = self.is_operator_truth
        if self.observed_start_at is not None:
            data["observed_start_at"] = self.observed_start_at
        if self.observed_start_business_date is not None:
            data["observed_start_business_date"] = self.observed_start_business_date
        data["store_timezone"] = self.store_timezone
        return data

