# Generated by packages/oday_data_contracts_client/codegen.py -- do not edit.
#
# Contract:  emgi.scope-principal.v4.1 (kernel, v4.1.0)
# Release:   oday-data-foundation-contracts.v0.4.1
# Producer:  alfloop-dev/oday-data-platform@3f0bd995bbd2248a9cff9176f27ed0e39d25948f
# Schema:    schemas/scope-principal.schema.json
# Digest:    3d67b579854d007811faf3fcd64017d44fd0bb20f169f55b30a428abb2230571
"""Portable, versioned document representing a scope principal contract snapshot."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

CONTRACT_ID = "emgi.scope-principal.v4.1"
CONTRACT_VERSION = "4.1.0"
CONTRACT_CATEGORY = "kernel"
SCHEMA_FILE = "schemas/scope-principal.schema.json"
SCHEMA_SHA256 = "3d67b579854d007811faf3fcd64017d44fd0bb20f169f55b30a428abb2230571"
ROOT_MODEL = "ScopePrincipalDocument"


class OwnerScope(StrEnum):
    """Entity category that owns the dataset or analytical asset."""

    PLATFORM = "PLATFORM"
    PARTNER = "PARTNER"
    TENANT = "TENANT"


class PurposeGrant(StrEnum):
    """Specific authorized analytical, operational, or export purposes."""

    TRAIN_MODEL = "TRAIN_MODEL"
    BUILD_BENCHMARK = "BUILD_BENCHMARK"
    SCORE_SITE = "SCORE_SITE"
    COMPARE_CANDIDATES = "COMPARE_CANDIDATES"
    MONITOR_MARKET = "MONITOR_MARKET"
    DISPLAY_RAW = "DISPLAY_RAW"
    DISPLAY_DERIVED = "DISPLAY_DERIVED"
    EXPORT_RAW = "EXPORT_RAW"
    EXPORT_DERIVED = "EXPORT_DERIVED"
    AUDIT_EVIDENCE = "AUDIT_EVIDENCE"


class SensitivityClass(StrEnum):
    """Information sensitivity and confidentiality classification."""

    PUBLIC = "PUBLIC"
    LICENSED = "LICENSED"
    PRIVATE = "PRIVATE"
    RESTRICTED = "RESTRICTED"


class SharingScope(StrEnum):
    """Audience boundary within which the data may be shared or queried."""

    GLOBAL = "GLOBAL"
    AUTHORIZED_CONSUMERS = "AUTHORIZED_CONSUMERS"
    SINGLE_TENANT = "SINGLE_TENANT"


@dataclass(frozen=True, slots=True)
class PurposeGrantSpec:
    """Granular grant for a specific authorized purpose with optional expiration."""

    purpose: PurposeGrant
    expires_at: str | None = None
    granted_at: str | None = None
    granted_by: str | None = None
    restrictions: list[str] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> PurposeGrantSpec:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["purpose"] = PurposeGrant(data["purpose"])
        if "expires_at" in data:
            values["expires_at"] = data["expires_at"]
        if "granted_at" in data:
            values["granted_at"] = data["granted_at"]
        if "granted_by" in data:
            values["granted_by"] = data["granted_by"]
        if "restrictions" in data:
            values["restrictions"] = list(data["restrictions"])
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["purpose"] = self.purpose.value
        if self.expires_at is not None:
            data["expires_at"] = self.expires_at
        if self.granted_at is not None:
            data["granted_at"] = self.granted_at
        if self.granted_by is not None:
            data["granted_by"] = self.granted_by
        data["restrictions"] = list(self.restrictions)
        return data


@dataclass(frozen=True, slots=True)
class ScopePrincipal:
    """Canonical security principal defining ownership, sharing, sensitivity, and purpose grants."""

    name: str
    owner_scope: OwnerScope
    principal_id: str
    sensitivity_class: SensitivityClass
    sharing_scope: SharingScope
    authorized_tenant_ids: list[str] = field(default_factory=list)
    contract_version: str = "emgi.scope-principal.v4.1"
    created_at: str | None = None
    description: str | None = None
    expires_at: str | None = None
    grants: list[PurposeGrantSpec] = field(default_factory=list)
    partner_id: str | None = None
    tenant_id: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> ScopePrincipal:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["name"] = data["name"]
        values["owner_scope"] = OwnerScope(data["owner_scope"])
        values["principal_id"] = data["principal_id"]
        values["sensitivity_class"] = SensitivityClass(data["sensitivity_class"])
        values["sharing_scope"] = SharingScope(data["sharing_scope"])
        if "authorized_tenant_ids" in data:
            values["authorized_tenant_ids"] = list(data["authorized_tenant_ids"])
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "created_at" in data:
            values["created_at"] = data["created_at"]
        if "description" in data:
            values["description"] = data["description"]
        if "expires_at" in data:
            values["expires_at"] = data["expires_at"]
        if "grants" in data:
            values["grants"] = [PurposeGrantSpec.from_dict(item) for item in data["grants"]]
        if "partner_id" in data:
            values["partner_id"] = data["partner_id"]
        if "tenant_id" in data:
            values["tenant_id"] = data["tenant_id"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["name"] = self.name
        data["owner_scope"] = self.owner_scope.value
        data["principal_id"] = self.principal_id
        data["sensitivity_class"] = self.sensitivity_class.value
        data["sharing_scope"] = self.sharing_scope.value
        data["authorized_tenant_ids"] = list(self.authorized_tenant_ids)
        data["contract_version"] = self.contract_version
        if self.created_at is not None:
            data["created_at"] = self.created_at
        if self.description is not None:
            data["description"] = self.description
        if self.expires_at is not None:
            data["expires_at"] = self.expires_at
        data["grants"] = [item.to_dict() for item in self.grants]
        if self.partner_id is not None:
            data["partner_id"] = self.partner_id
        if self.tenant_id is not None:
            data["tenant_id"] = self.tenant_id
        return data


@dataclass(frozen=True, slots=True)
class ScopePrincipalDocument:
    """Portable, versioned document representing a scope principal contract snapshot.

    Root model of contract `emgi.scope-principal.v4.1`
    (kernel, version 4.1.0).
    """

    contract_id: str = "emgi.scope-principal.v4.1"
    principals: list[ScopePrincipal] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> ScopePrincipalDocument:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        if "contract_id" in data:
            values["contract_id"] = data["contract_id"]
        if "principals" in data:
            values["principals"] = [ScopePrincipal.from_dict(item) for item in data["principals"]]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["contract_id"] = self.contract_id
        data["principals"] = [item.to_dict() for item in self.principals]
        return data

