# Generated by packages/oday_data_contracts_client/codegen.py -- do not edit.
#
# Contract:  emgi.source-registry.v4.1 (kernel, v4.1.0)
# Release:   oday-data-foundation-contracts.v0.4.1
# Producer:  alfloop-dev/oday-data-platform@3f0bd995bbd2248a9cff9176f27ed0e39d25948f
# Schema:    schemas/source-registry.schema.json
# Digest:    2c463e84e26a3b49f20ad34b0a44219276542bd6a9a7ef0034272fc442dc49d5
"""Portable, fully referentially validated source-registry snapshot."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

CONTRACT_ID = "emgi.source-registry.v4.1"
CONTRACT_VERSION = "4.1.0"
CONTRACT_CATEGORY = "kernel"
SCHEMA_FILE = "schemas/source-registry.schema.json"
SCHEMA_SHA256 = "2c463e84e26a3b49f20ad34b0a44219276542bd6a9a7ef0034272fc442dc49d5"
ROOT_MODEL = "SourceRegistryDocument"


class DependencyKind(StrEnum):
    """How a dataset depends on another registered dataset."""

    DERIVED_FROM = "DERIVED_FROM"
    MIRROR_OF = "MIRROR_OF"
    REPACKAGES = "REPACKAGES"
    ENRICHES = "ENRICHES"
    VERIFIES = "VERIFIES"


class PolicyState(StrEnum):
    """PolicyState"""

    UNREVIEWED = "UNREVIEWED"
    APPROVED = "APPROVED"
    RESTRICTED = "RESTRICTED"
    BLOCKED = "BLOCKED"
    EXPIRED = "EXPIRED"


class PublicationState(StrEnum):
    """PublicationState"""

    NOT_ELIGIBLE = "NOT_ELIGIBLE"
    INTERNAL_ONLY = "INTERNAL_ONLY"
    READY = "READY"
    PUBLISHED = "PUBLISHED"
    SUSPENDED = "SUSPENDED"
    RETRACTED = "RETRACTED"


class ReleaseKind(StrEnum):
    """ReleaseKind"""

    SNAPSHOT = "SNAPSHOT"
    API_ENDPOINT = "API_ENDPOINT"
    STREAM = "STREAM"


class SourceRole(StrEnum):
    """The evidentiary role a dataset plays in canonical products."""

    AUTHORITATIVE = "AUTHORITATIVE"
    PRIMARY = "PRIMARY"
    SUPPLEMENTAL = "SUPPLEMENTAL"
    VERIFICATION = "VERIFICATION"
    DERIVED = "DERIVED"


class TechnicalReadiness(StrEnum):
    """TechnicalReadiness"""

    DECLARED = "DECLARED"
    ACCESS_CONFIGURED = "ACCESS_CONFIGURED"
    INGESTION_VERIFIED = "INGESTION_VERIFIED"
    CANONICAL_MAPPING_VERIFIED = "CANONICAL_MAPPING_VERIFIED"
    LIVE_VERIFIED = "LIVE_VERIFIED"
    DEGRADED = "DEGRADED"
    RETIRED = "RETIRED"


@dataclass(frozen=True, slots=True)
class CostMetadata:
    """Marginal source cost used for acquisition planning."""

    currency: str
    unit: str
    unit_cost: Any
    minimum_charge: Any = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> CostMetadata:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["currency"] = data["currency"]
        values["unit"] = data["unit"]
        values["unit_cost"] = data["unit_cost"]
        if "minimum_charge" in data:
            values["minimum_charge"] = data["minimum_charge"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["currency"] = self.currency
        data["unit"] = self.unit
        data["unit_cost"] = self.unit_cost
        if self.minimum_charge is not None:
            data["minimum_charge"] = self.minimum_charge
        return data


@dataclass(frozen=True, slots=True)
class Provider:
    """A provider organization, separate from what it publishes."""

    legal_name: str
    provider_id: str
    display_name: str | None = None
    homepage_uri: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Provider:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["legal_name"] = data["legal_name"]
        values["provider_id"] = data["provider_id"]
        if "display_name" in data:
            values["display_name"] = data["display_name"]
        if "homepage_uri" in data:
            values["homepage_uri"] = data["homepage_uri"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["legal_name"] = self.legal_name
        data["provider_id"] = self.provider_id
        if self.display_name is not None:
            data["display_name"] = self.display_name
        if self.homepage_uri is not None:
            data["homepage_uri"] = self.homepage_uri
        return data


@dataclass(frozen=True, slots=True)
class QuotaMetadata:
    """Static quota terms; live consumption belongs in operational telemetry."""

    limit: int
    period_seconds: int
    unit: str
    burst_limit: int | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> QuotaMetadata:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["limit"] = data["limit"]
        values["period_seconds"] = data["period_seconds"]
        values["unit"] = data["unit"]
        if "burst_limit" in data:
            values["burst_limit"] = data["burst_limit"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["limit"] = self.limit
        data["period_seconds"] = self.period_seconds
        data["unit"] = self.unit
        if self.burst_limit is not None:
            data["burst_limit"] = self.burst_limit
        return data


@dataclass(frozen=True, slots=True)
class ReadinessEvidence:
    """Evidence needed before a release can claim ``LIVE_VERIFIED``."""

    access_verified: bool = False
    canonical_mapping_verified: bool = False
    data_quality_verified: bool = False
    freshness_verified: bool = False
    published_consumer_lineage_verified: bool = False
    raw_snapshot_sha256: str | None = None
    release_or_endpoint_verified: bool = False
    restart_readback_verified: bool = False

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> ReadinessEvidence:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        if "access_verified" in data:
            values["access_verified"] = data["access_verified"]
        if "canonical_mapping_verified" in data:
            values["canonical_mapping_verified"] = data["canonical_mapping_verified"]
        if "data_quality_verified" in data:
            values["data_quality_verified"] = data["data_quality_verified"]
        if "freshness_verified" in data:
            values["freshness_verified"] = data["freshness_verified"]
        if "published_consumer_lineage_verified" in data:
            values["published_consumer_lineage_verified"] = data["published_consumer_lineage_verified"]
        if "raw_snapshot_sha256" in data:
            values["raw_snapshot_sha256"] = data["raw_snapshot_sha256"]
        if "release_or_endpoint_verified" in data:
            values["release_or_endpoint_verified"] = data["release_or_endpoint_verified"]
        if "restart_readback_verified" in data:
            values["restart_readback_verified"] = data["restart_readback_verified"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["access_verified"] = self.access_verified
        data["canonical_mapping_verified"] = self.canonical_mapping_verified
        data["data_quality_verified"] = self.data_quality_verified
        data["freshness_verified"] = self.freshness_verified
        data["published_consumer_lineage_verified"] = self.published_consumer_lineage_verified
        if self.raw_snapshot_sha256 is not None:
            data["raw_snapshot_sha256"] = self.raw_snapshot_sha256
        data["release_or_endpoint_verified"] = self.release_or_endpoint_verified
        data["restart_readback_verified"] = self.restart_readback_verified
        return data


@dataclass(frozen=True, slots=True)
class SourceAdapter:
    """Versioned implementation with explicit schema-contract compatibility."""

    adapter_id: str
    adapter_version: str
    compatible_contract_version_ids: list[str]
    dataset_id: str
    implementation: str
    technical_readiness: TechnicalReadiness = TechnicalReadiness.DECLARED

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SourceAdapter:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["adapter_id"] = data["adapter_id"]
        values["adapter_version"] = data["adapter_version"]
        values["compatible_contract_version_ids"] = list(data["compatible_contract_version_ids"])
        values["dataset_id"] = data["dataset_id"]
        values["implementation"] = data["implementation"]
        if "technical_readiness" in data:
            values["technical_readiness"] = TechnicalReadiness(data["technical_readiness"])
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["adapter_id"] = self.adapter_id
        data["adapter_version"] = self.adapter_version
        data["compatible_contract_version_ids"] = list(self.compatible_contract_version_ids)
        data["dataset_id"] = self.dataset_id
        data["implementation"] = self.implementation
        data["technical_readiness"] = self.technical_readiness.value
        return data


@dataclass(frozen=True, slots=True)
class SourceContractVersion:
    """An immutable schema contract understood by source adapters."""

    contract_version_id: str
    dataset_id: str
    schema_sha256: str
    schema_uri: str
    semantic_version: str
    media_type: str = "application/schema+json"

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SourceContractVersion:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["contract_version_id"] = data["contract_version_id"]
        values["dataset_id"] = data["dataset_id"]
        values["schema_sha256"] = data["schema_sha256"]
        values["schema_uri"] = data["schema_uri"]
        values["semantic_version"] = data["semantic_version"]
        if "media_type" in data:
            values["media_type"] = data["media_type"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["contract_version_id"] = self.contract_version_id
        data["dataset_id"] = self.dataset_id
        data["schema_sha256"] = self.schema_sha256
        data["schema_uri"] = self.schema_uri
        data["semantic_version"] = self.semantic_version
        data["media_type"] = self.media_type
        return data


@dataclass(frozen=True, slots=True)
class SourceDataset:
    """A named source offering whose releases share a semantic identity."""

    dataset_id: str
    name: str
    provider_id: str
    source_role: SourceRole
    upstream_dependencies: list[UpstreamDependency] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SourceDataset:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["dataset_id"] = data["dataset_id"]
        values["name"] = data["name"]
        values["provider_id"] = data["provider_id"]
        values["source_role"] = SourceRole(data["source_role"])
        if "upstream_dependencies" in data:
            values["upstream_dependencies"] = [UpstreamDependency.from_dict(item) for item in data["upstream_dependencies"]]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["dataset_id"] = self.dataset_id
        data["name"] = self.name
        data["provider_id"] = self.provider_id
        data["source_role"] = self.source_role.value
        data["upstream_dependencies"] = [item.to_dict() for item in self.upstream_dependencies]
        return data


@dataclass(frozen=True, slots=True)
class SourceDatasetVersion:
    """A concrete source release or versioned endpoint."""

    contract_version_id: str
    dataset_id: str
    dataset_version_id: str
    policy_state: PolicyState
    publication_state: PublicationState
    release_key: str
    release_kind: ReleaseKind
    source_uri: str
    technical_readiness: TechnicalReadiness
    content_sha256: str | None = None
    cost: CostMetadata | None = None
    quota: QuotaMetadata | None = None
    readiness_evidence: ReadinessEvidence | None = None
    released_at: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SourceDatasetVersion:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["contract_version_id"] = data["contract_version_id"]
        values["dataset_id"] = data["dataset_id"]
        values["dataset_version_id"] = data["dataset_version_id"]
        values["policy_state"] = PolicyState(data["policy_state"])
        values["publication_state"] = PublicationState(data["publication_state"])
        values["release_key"] = data["release_key"]
        values["release_kind"] = ReleaseKind(data["release_kind"])
        values["source_uri"] = data["source_uri"]
        values["technical_readiness"] = TechnicalReadiness(data["technical_readiness"])
        if "content_sha256" in data:
            values["content_sha256"] = data["content_sha256"]
        if "cost" in data:
            values["cost"] = None if data["cost"] is None else CostMetadata.from_dict(data["cost"])
        if "quota" in data:
            values["quota"] = None if data["quota"] is None else QuotaMetadata.from_dict(data["quota"])
        if "readiness_evidence" in data:
            values["readiness_evidence"] = None if data["readiness_evidence"] is None else ReadinessEvidence.from_dict(data["readiness_evidence"])
        if "released_at" in data:
            values["released_at"] = data["released_at"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["contract_version_id"] = self.contract_version_id
        data["dataset_id"] = self.dataset_id
        data["dataset_version_id"] = self.dataset_version_id
        data["policy_state"] = self.policy_state.value
        data["publication_state"] = self.publication_state.value
        data["release_key"] = self.release_key
        data["release_kind"] = self.release_kind.value
        data["source_uri"] = self.source_uri
        data["technical_readiness"] = self.technical_readiness.value
        if self.content_sha256 is not None:
            data["content_sha256"] = self.content_sha256
        if self.cost is not None:
            data["cost"] = self.cost.to_dict()
        if self.quota is not None:
            data["quota"] = self.quota.to_dict()
        if self.readiness_evidence is not None:
            data["readiness_evidence"] = self.readiness_evidence.to_dict()
        if self.released_at is not None:
            data["released_at"] = self.released_at
        return data


@dataclass(frozen=True, slots=True)
class UpstreamDependency:
    """UpstreamDependency"""

    dataset_id: str
    kind: DependencyKind

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> UpstreamDependency:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["dataset_id"] = data["dataset_id"]
        values["kind"] = DependencyKind(data["kind"])
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["dataset_id"] = self.dataset_id
        data["kind"] = self.kind.value
        return data


@dataclass(frozen=True, slots=True)
class SourceRegistryDocument:
    """Portable, fully referentially validated source-registry snapshot.

    Root model of contract `emgi.source-registry.v4.1`
    (kernel, version 4.1.0).
    """

    adapters: list[SourceAdapter] = field(default_factory=list)
    contract_id: str = "emgi.source-registry.v4.1"
    contract_versions: list[SourceContractVersion] = field(default_factory=list)
    dataset_versions: list[SourceDatasetVersion] = field(default_factory=list)
    datasets: list[SourceDataset] = field(default_factory=list)
    providers: list[Provider] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SourceRegistryDocument:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        if "adapters" in data:
            values["adapters"] = [SourceAdapter.from_dict(item) for item in data["adapters"]]
        if "contract_id" in data:
            values["contract_id"] = data["contract_id"]
        if "contract_versions" in data:
            values["contract_versions"] = [SourceContractVersion.from_dict(item) for item in data["contract_versions"]]
        if "dataset_versions" in data:
            values["dataset_versions"] = [SourceDatasetVersion.from_dict(item) for item in data["dataset_versions"]]
        if "datasets" in data:
            values["datasets"] = [SourceDataset.from_dict(item) for item in data["datasets"]]
        if "providers" in data:
            values["providers"] = [Provider.from_dict(item) for item in data["providers"]]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["adapters"] = [item.to_dict() for item in self.adapters]
        data["contract_id"] = self.contract_id
        data["contract_versions"] = [item.to_dict() for item in self.contract_versions]
        data["dataset_versions"] = [item.to_dict() for item in self.dataset_versions]
        data["datasets"] = [item.to_dict() for item in self.datasets]
        data["providers"] = [item.to_dict() for item in self.providers]
        return data

