# Generated by packages/oday_data_contracts_client/codegen.py -- do not edit.
#
# Contract:  oday.store-reference.v1 (internal_analytical, v1.0.0)
# Release:   oday-data-foundation-contracts.v0.4.1
# Producer:  alfloop-dev/oday-data-platform@3f0bd995bbd2248a9cff9176f27ed0e39d25948f
# Schema:    schemas/store-reference.schema.json
# Digest:    b434a7d2436d440025985bae45dd70c5ef11b59ce1a09b781acbad629d421c60
"""Effective-dated store identity published to contract consumers."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from enum import StrEnum
from typing import Any

CONTRACT_ID = "oday.store-reference.v1"
CONTRACT_VERSION = "1.0.0"
CONTRACT_CATEGORY = "internal_analytical"
SCHEMA_FILE = "schemas/store-reference.schema.json"
SCHEMA_SHA256 = "b434a7d2436d440025985bae45dd70c5ef11b59ce1a09b781acbad629d421c60"
ROOT_MODEL = "StoreReference"


class MaterializationEnvironment(StrEnum):
    """MaterializationEnvironment"""

    development = "development"
    test = "test"
    production = "production"


class MaterializationKind(StrEnum):
    """MaterializationKind"""

    observation = "observation"
    feature = "feature"
    label = "label"


@dataclass(frozen=True, slots=True)
class StoreGeolocation:
    """WGS84 point published for a store, or explicitly absent."""

    latitude: float
    longitude: float
    geometry_type: str | None = None
    srid: int = 4326

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> StoreGeolocation:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["latitude"] = data["latitude"]
        values["longitude"] = data["longitude"]
        if "geometry_type" in data:
            values["geometry_type"] = data["geometry_type"]
        if "srid" in data:
            values["srid"] = data["srid"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["latitude"] = self.latitude
        data["longitude"] = self.longitude
        if self.geometry_type is not None:
            data["geometry_type"] = self.geometry_type
        data["srid"] = self.srid
        return data


@dataclass(frozen=True, slots=True)
class TimeContract:
    """Versioned temporal envelope shared by EMGI contracts. Observation fields are optional because providers do not expose every timestamp. Their absence remains explicit. Feature and label envelopes impose stronger requirements, and production materializations always need explicit knowledge and build cutoffs."""

    available_at: str | None = None
    build_at: str | None = None
    business_day_boundary: str = "00:00:00"
    contract_version: str = "emgi.time-contract.v4"
    effective_from: str | None = None
    effective_to: str | None = None
    event_time: str | None = None
    fetched_at: str | None = None
    ingested_at: str | None = None
    knowledge_as_of: str | None = None
    label_maturity_time: str | None = None
    materialization_environment: MaterializationEnvironment = MaterializationEnvironment.development
    materialization_kind: MaterializationKind = MaterializationKind.observation
    observed_at: str | None = None
    prediction_origin_time: str | None = None
    retracted_at: str | None = None
    source_published_at: str | None = None
    store_timezone: str = "Asia/Taipei"

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> TimeContract:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        if "available_at" in data:
            values["available_at"] = data["available_at"]
        if "build_at" in data:
            values["build_at"] = data["build_at"]
        if "business_day_boundary" in data:
            values["business_day_boundary"] = data["business_day_boundary"]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "effective_from" in data:
            values["effective_from"] = data["effective_from"]
        if "effective_to" in data:
            values["effective_to"] = data["effective_to"]
        if "event_time" in data:
            values["event_time"] = data["event_time"]
        if "fetched_at" in data:
            values["fetched_at"] = data["fetched_at"]
        if "ingested_at" in data:
            values["ingested_at"] = data["ingested_at"]
        if "knowledge_as_of" in data:
            values["knowledge_as_of"] = data["knowledge_as_of"]
        if "label_maturity_time" in data:
            values["label_maturity_time"] = data["label_maturity_time"]
        if "materialization_environment" in data:
            values["materialization_environment"] = MaterializationEnvironment(data["materialization_environment"])
        if "materialization_kind" in data:
            values["materialization_kind"] = MaterializationKind(data["materialization_kind"])
        if "observed_at" in data:
            values["observed_at"] = data["observed_at"]
        if "prediction_origin_time" in data:
            values["prediction_origin_time"] = data["prediction_origin_time"]
        if "retracted_at" in data:
            values["retracted_at"] = data["retracted_at"]
        if "source_published_at" in data:
            values["source_published_at"] = data["source_published_at"]
        if "store_timezone" in data:
            values["store_timezone"] = data["store_timezone"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        if self.available_at is not None:
            data["available_at"] = self.available_at
        if self.build_at is not None:
            data["build_at"] = self.build_at
        data["business_day_boundary"] = self.business_day_boundary
        data["contract_version"] = self.contract_version
        if self.effective_from is not None:
            data["effective_from"] = self.effective_from
        if self.effective_to is not None:
            data["effective_to"] = self.effective_to
        if self.event_time is not None:
            data["event_time"] = self.event_time
        if self.fetched_at is not None:
            data["fetched_at"] = self.fetched_at
        if self.ingested_at is not None:
            data["ingested_at"] = self.ingested_at
        if self.knowledge_as_of is not None:
            data["knowledge_as_of"] = self.knowledge_as_of
        if self.label_maturity_time is not None:
            data["label_maturity_time"] = self.label_maturity_time
        data["materialization_environment"] = self.materialization_environment.value
        data["materialization_kind"] = self.materialization_kind.value
        if self.observed_at is not None:
            data["observed_at"] = self.observed_at
        if self.prediction_origin_time is not None:
            data["prediction_origin_time"] = self.prediction_origin_time
        if self.retracted_at is not None:
            data["retracted_at"] = self.retracted_at
        if self.source_published_at is not None:
            data["source_published_at"] = self.source_published_at
        data["store_timezone"] = self.store_timezone
        return data


@dataclass(frozen=True, slots=True)
class StoreReference:
    """Effective-dated store identity published to contract consumers.

    Root model of contract `oday.store-reference.v1`
    (internal_analytical, version 1.0.0).
    """

    effective_from: str
    registered_at: str
    source_row_digest: str
    store_id: str
    store_name: str
    time_contract: TimeContract
    business_day_boundary: str = "00:00:00"
    contract_id: str = "oday.store-reference.v1"
    contract_version: str = "1.0.0"
    effective_to: str | None = None
    entity_type: str = "store"
    geolocation: StoreGeolocation | None = None
    merchant_country: str | None = None
    merchant_id: str | None = None
    merchant_name: str | None = None
    merchant_registered_at: str | None = None
    registered_business_date: str | None = None
    store_timezone: str = "Asia/Taipei"

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> StoreReference:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["effective_from"] = data["effective_from"]
        values["registered_at"] = data["registered_at"]
        values["source_row_digest"] = data["source_row_digest"]
        values["store_id"] = data["store_id"]
        values["store_name"] = data["store_name"]
        values["time_contract"] = TimeContract.from_dict(data["time_contract"])
        if "business_day_boundary" in data:
            values["business_day_boundary"] = data["business_day_boundary"]
        if "contract_id" in data:
            values["contract_id"] = data["contract_id"]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "effective_to" in data:
            values["effective_to"] = data["effective_to"]
        if "entity_type" in data:
            values["entity_type"] = data["entity_type"]
        if "geolocation" in data:
            values["geolocation"] = None if data["geolocation"] is None else StoreGeolocation.from_dict(data["geolocation"])
        if "merchant_country" in data:
            values["merchant_country"] = data["merchant_country"]
        if "merchant_id" in data:
            values["merchant_id"] = data["merchant_id"]
        if "merchant_name" in data:
            values["merchant_name"] = data["merchant_name"]
        if "merchant_registered_at" in data:
            values["merchant_registered_at"] = data["merchant_registered_at"]
        if "registered_business_date" in data:
            values["registered_business_date"] = data["registered_business_date"]
        if "store_timezone" in data:
            values["store_timezone"] = data["store_timezone"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["effective_from"] = self.effective_from
        data["registered_at"] = self.registered_at
        data["source_row_digest"] = self.source_row_digest
        data["store_id"] = self.store_id
        data["store_name"] = self.store_name
        data["time_contract"] = self.time_contract.to_dict()
        data["business_day_boundary"] = self.business_day_boundary
        data["contract_id"] = self.contract_id
        data["contract_version"] = self.contract_version
        if self.effective_to is not None:
            data["effective_to"] = self.effective_to
        data["entity_type"] = self.entity_type
        if self.geolocation is not None:
            data["geolocation"] = self.geolocation.to_dict()
        if self.merchant_country is not None:
            data["merchant_country"] = self.merchant_country
        if self.merchant_id is not None:
            data["merchant_id"] = self.merchant_id
        if self.merchant_name is not None:
            data["merchant_name"] = self.merchant_name
        if self.merchant_registered_at is not None:
            data["merchant_registered_at"] = self.merchant_registered_at
        if self.registered_business_date is not None:
            data["registered_business_date"] = self.registered_business_date
        data["store_timezone"] = self.store_timezone
        return data

