# Generated by packages/oday_data_contracts_client/codegen.py -- do not edit.
#
# Contract:  oday.store-coverage.v1 (internal_analytical, v1.0.0)
# Release:   oday-data-foundation-contracts.v0.4.1
# Producer:  alfloop-dev/oday-data-platform@3f0bd995bbd2248a9cff9176f27ed0e39d25948f
# Schema:    schemas/store-coverage.schema.json
# Digest:    0899467a76a97a6dd334327f78f1fa1b049db1b6ebc01497250368cac3d29e6e
"""Coverage proof for one store on one business date."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

CONTRACT_ID = "oday.store-coverage.v1"
CONTRACT_VERSION = "1.0.0"
CONTRACT_CATEGORY = "internal_analytical"
SCHEMA_FILE = "schemas/store-coverage.schema.json"
SCHEMA_SHA256 = "0899467a76a97a6dd334327f78f1fa1b049db1b6ebc01497250368cac3d29e6e"
ROOT_MODEL = "StoreDayCoverage"


class CoverageState(StrEnum):
    """Distinct partition coverage evaluation states. Maintains crisp separation between: - COMPLETE: fully observed, tested, and complete partition with >= 1 items. - EMPTY: fully observed and complete partition with 0 items (affirmative negative evidence). - SATURATED: upstream capacity, bbox POI cap, or rate limit hit; sub-partition refinement required. - TRUNCATED: pagination limit or record cutoff hit; result set is incomplete. - PARTIAL: partial coverage or unobserved sub-partitions; cannot claim full partition coverage. - SOURCE_ERROR: provider or network error encountered during partition extraction. - UNKNOWN: uncollected, unobserved, or unverified partition state."""

    complete = "complete"
    empty = "empty"
    saturated = "saturated"
    truncated = "truncated"
    partial = "partial"
    source_error = "source_error"
    unknown = "unknown"


class GeometryType(StrEnum):
    """Geometry representation kind for spatial search queries."""

    POINT = "POINT"
    POLYGON = "POLYGON"
    MULTIPOLYGON = "MULTIPOLYGON"
    BBOX = "BBOX"
    H3_CELL = "H3_CELL"
    ADMIN_CODE = "ADMIN_CODE"
    NONE = "NONE"


@dataclass(frozen=True, slots=True)
class EntityPartitionCoverage:
    """Canonical record proving entity-partition coverage and valid-zero evidence. Implements `emgi.coverage.v4.1` contract."""

    coverage_id: str
    dataset_id: str
    is_complete: bool
    scope_principal_id: str
    state: CoverageState
    available_at: str | None = None
    business_date: Any = None
    contract_version: str = "emgi.coverage.v4.1"
    dataset_version_id: str | None = None
    entity_id: str | None = None
    entity_type: str | None = None
    error_detail: str | None = None
    expected_count: int | None = None
    knowledge_as_of: str | None = None
    metadata: dict[str, Any] | None = None
    negative_evidence_valid: bool = False
    observation_ids: list[str] = field(default_factory=list)
    observed_count: int = 0
    quarantine_reason: str | None = None
    query_geometry: QueryGeometry | None = None
    reconciled_at: str | None = None
    reconciliation_run_id: str | None = None
    saturation_limit: Any = None
    search_execution_ids: list[str] = field(default_factory=list)
    store_timezone: str = "Asia/Taipei"
    sub_partitions: list[SubPartitionSummary] = field(default_factory=list)
    tenant_id: str | None = None
    time_window: TimeWindow | None = None
    truncation_limit: int | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> EntityPartitionCoverage:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["coverage_id"] = data["coverage_id"]
        values["dataset_id"] = data["dataset_id"]
        values["is_complete"] = data["is_complete"]
        values["scope_principal_id"] = data["scope_principal_id"]
        values["state"] = CoverageState(data["state"])
        if "available_at" in data:
            values["available_at"] = data["available_at"]
        if "business_date" in data:
            values["business_date"] = data["business_date"]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "dataset_version_id" in data:
            values["dataset_version_id"] = data["dataset_version_id"]
        if "entity_id" in data:
            values["entity_id"] = data["entity_id"]
        if "entity_type" in data:
            values["entity_type"] = data["entity_type"]
        if "error_detail" in data:
            values["error_detail"] = data["error_detail"]
        if "expected_count" in data:
            values["expected_count"] = data["expected_count"]
        if "knowledge_as_of" in data:
            values["knowledge_as_of"] = data["knowledge_as_of"]
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        if "negative_evidence_valid" in data:
            values["negative_evidence_valid"] = data["negative_evidence_valid"]
        if "observation_ids" in data:
            values["observation_ids"] = list(data["observation_ids"])
        if "observed_count" in data:
            values["observed_count"] = data["observed_count"]
        if "quarantine_reason" in data:
            values["quarantine_reason"] = data["quarantine_reason"]
        if "query_geometry" in data:
            values["query_geometry"] = None if data["query_geometry"] is None else QueryGeometry.from_dict(data["query_geometry"])
        if "reconciled_at" in data:
            values["reconciled_at"] = data["reconciled_at"]
        if "reconciliation_run_id" in data:
            values["reconciliation_run_id"] = data["reconciliation_run_id"]
        if "saturation_limit" in data:
            values["saturation_limit"] = data["saturation_limit"]
        if "search_execution_ids" in data:
            values["search_execution_ids"] = list(data["search_execution_ids"])
        if "store_timezone" in data:
            values["store_timezone"] = data["store_timezone"]
        if "sub_partitions" in data:
            values["sub_partitions"] = [SubPartitionSummary.from_dict(item) for item in data["sub_partitions"]]
        if "tenant_id" in data:
            values["tenant_id"] = data["tenant_id"]
        if "time_window" in data:
            values["time_window"] = None if data["time_window"] is None else TimeWindow.from_dict(data["time_window"])
        if "truncation_limit" in data:
            values["truncation_limit"] = data["truncation_limit"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["coverage_id"] = self.coverage_id
        data["dataset_id"] = self.dataset_id
        data["is_complete"] = self.is_complete
        data["scope_principal_id"] = self.scope_principal_id
        data["state"] = self.state.value
        if self.available_at is not None:
            data["available_at"] = self.available_at
        if self.business_date is not None:
            data["business_date"] = self.business_date
        data["contract_version"] = self.contract_version
        if self.dataset_version_id is not None:
            data["dataset_version_id"] = self.dataset_version_id
        if self.entity_id is not None:
            data["entity_id"] = self.entity_id
        if self.entity_type is not None:
            data["entity_type"] = self.entity_type
        if self.error_detail is not None:
            data["error_detail"] = self.error_detail
        if self.expected_count is not None:
            data["expected_count"] = self.expected_count
        if self.knowledge_as_of is not None:
            data["knowledge_as_of"] = self.knowledge_as_of
        if self.metadata is not None:
            data["metadata"] = self.metadata
        data["negative_evidence_valid"] = self.negative_evidence_valid
        data["observation_ids"] = list(self.observation_ids)
        data["observed_count"] = self.observed_count
        if self.quarantine_reason is not None:
            data["quarantine_reason"] = self.quarantine_reason
        if self.query_geometry is not None:
            data["query_geometry"] = self.query_geometry.to_dict()
        if self.reconciled_at is not None:
            data["reconciled_at"] = self.reconciled_at
        if self.reconciliation_run_id is not None:
            data["reconciliation_run_id"] = self.reconciliation_run_id
        if self.saturation_limit is not None:
            data["saturation_limit"] = self.saturation_limit
        data["search_execution_ids"] = list(self.search_execution_ids)
        data["store_timezone"] = self.store_timezone
        data["sub_partitions"] = [item.to_dict() for item in self.sub_partitions]
        if self.tenant_id is not None:
            data["tenant_id"] = self.tenant_id
        if self.time_window is not None:
            data["time_window"] = self.time_window.to_dict()
        if self.truncation_limit is not None:
            data["truncation_limit"] = self.truncation_limit
        return data


@dataclass(frozen=True, slots=True)
class QueryGeometry:
    """Geometry and coordinate reference envelope for spatial searches."""

    admin_code: str | None = None
    coordinates: Any = None
    geometry_type: GeometryType = GeometryType.NONE
    h3_index: str | None = None
    srid: int = 4326

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> QueryGeometry:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        if "admin_code" in data:
            values["admin_code"] = data["admin_code"]
        if "coordinates" in data:
            values["coordinates"] = data["coordinates"]
        if "geometry_type" in data:
            values["geometry_type"] = GeometryType(data["geometry_type"])
        if "h3_index" in data:
            values["h3_index"] = data["h3_index"]
        if "srid" in data:
            values["srid"] = data["srid"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        if self.admin_code is not None:
            data["admin_code"] = self.admin_code
        if self.coordinates is not None:
            data["coordinates"] = self.coordinates
        data["geometry_type"] = self.geometry_type.value
        if self.h3_index is not None:
            data["h3_index"] = self.h3_index
        data["srid"] = self.srid
        return data


@dataclass(frozen=True, slots=True)
class SubPartitionSummary:
    """Summary status of a sub-partition in a spatial or hierarchical composition."""

    state: CoverageState
    sub_partition_key: str
    error_detail: str | None = None
    geometry: QueryGeometry | None = None
    is_complete: bool = False
    observed_count: int = 0
    saturation_limit: Any = None
    truncation_limit: int | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SubPartitionSummary:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["state"] = CoverageState(data["state"])
        values["sub_partition_key"] = data["sub_partition_key"]
        if "error_detail" in data:
            values["error_detail"] = data["error_detail"]
        if "geometry" in data:
            values["geometry"] = None if data["geometry"] is None else QueryGeometry.from_dict(data["geometry"])
        if "is_complete" in data:
            values["is_complete"] = data["is_complete"]
        if "observed_count" in data:
            values["observed_count"] = data["observed_count"]
        if "saturation_limit" in data:
            values["saturation_limit"] = data["saturation_limit"]
        if "truncation_limit" in data:
            values["truncation_limit"] = data["truncation_limit"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["state"] = self.state.value
        data["sub_partition_key"] = self.sub_partition_key
        if self.error_detail is not None:
            data["error_detail"] = self.error_detail
        if self.geometry is not None:
            data["geometry"] = self.geometry.to_dict()
        data["is_complete"] = self.is_complete
        data["observed_count"] = self.observed_count
        if self.saturation_limit is not None:
            data["saturation_limit"] = self.saturation_limit
        if self.truncation_limit is not None:
            data["truncation_limit"] = self.truncation_limit
        return data


@dataclass(frozen=True, slots=True)
class TimeWindow:
    """Explicit temporal window for partition coverage evaluation."""

    window_end: str
    window_start: str
    effective_from: str | None = None
    effective_to: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> TimeWindow:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["window_end"] = data["window_end"]
        values["window_start"] = data["window_start"]
        if "effective_from" in data:
            values["effective_from"] = data["effective_from"]
        if "effective_to" in data:
            values["effective_to"] = data["effective_to"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["window_end"] = self.window_end
        data["window_start"] = self.window_start
        if self.effective_from is not None:
            data["effective_from"] = self.effective_from
        if self.effective_to is not None:
            data["effective_to"] = self.effective_to
        return data


@dataclass(frozen=True, slots=True)
class StoreDayCoverage:
    """Coverage proof for one store on one business date.

    Root model of contract `oday.store-coverage.v1`
    (internal_analytical, version 1.0.0).
    """

    business_date: str
    coverage: EntityPartitionCoverage
    raw_contract_fingerprint: str
    store_id: str
    window_end: str
    window_start: str
    business_day_boundary: str = "00:00:00"
    contract_id: str = "oday.store-coverage.v1"
    contract_version: str = "1.0.0"
    raw_source_table: str = "transactions"
    store_timezone: str = "Asia/Taipei"

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> StoreDayCoverage:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["business_date"] = data["business_date"]
        values["coverage"] = EntityPartitionCoverage.from_dict(data["coverage"])
        values["raw_contract_fingerprint"] = data["raw_contract_fingerprint"]
        values["store_id"] = data["store_id"]
        values["window_end"] = data["window_end"]
        values["window_start"] = data["window_start"]
        if "business_day_boundary" in data:
            values["business_day_boundary"] = data["business_day_boundary"]
        if "contract_id" in data:
            values["contract_id"] = data["contract_id"]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "raw_source_table" in data:
            values["raw_source_table"] = data["raw_source_table"]
        if "store_timezone" in data:
            values["store_timezone"] = data["store_timezone"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["business_date"] = self.business_date
        data["coverage"] = self.coverage.to_dict()
        data["raw_contract_fingerprint"] = self.raw_contract_fingerprint
        data["store_id"] = self.store_id
        data["window_end"] = self.window_end
        data["window_start"] = self.window_start
        data["business_day_boundary"] = self.business_day_boundary
        data["contract_id"] = self.contract_id
        data["contract_version"] = self.contract_version
        data["raw_source_table"] = self.raw_source_table
        data["store_timezone"] = self.store_timezone
        return data

