# Generated by packages/oday_data_contracts_client/codegen.py -- do not edit.
#
# Contract:  emgi.time-contract.v4.1 (kernel, v4.1.0)
# Release:   oday-data-foundation-contracts.v0.4.1
# Producer:  alfloop-dev/oday-data-platform@3f0bd995bbd2248a9cff9176f27ed0e39d25948f
# Schema:    schemas/time-contract.schema.json
# Digest:    d1e4a7e51c5c819dcdbe4cc4faf895779b078dbd4455cd395133b0a27c3fa7b4
"""Separate effective, evidence, knowledge, feature, label, retraction, build, and store-local business time."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

CONTRACT_ID = "emgi.time-contract.v4.1"
CONTRACT_VERSION = "4.1.0"
CONTRACT_CATEGORY = "kernel"
SCHEMA_FILE = "schemas/time-contract.schema.json"
SCHEMA_SHA256 = "d1e4a7e51c5c819dcdbe4cc4faf895779b078dbd4455cd395133b0a27c3fa7b4"
ROOT_MODEL = "TimeContract"


Timestamp = str


NullableTimestamp = Timestamp | None


@dataclass(frozen=True, slots=True)
class TimeContract:
    """Separate effective, evidence, knowledge, feature, label, retraction, build, and store-local business time.

    Root model of contract `emgi.time-contract.v4.1`
    (kernel, version 4.1.0).
    """

    available_at: NullableTimestamp = None
    build_at: NullableTimestamp = None
    business_day_boundary: str = "00:00:00"
    contract_version: str = "emgi.time-contract.v4"
    effective_from: NullableTimestamp = None
    effective_to: NullableTimestamp = None
    event_time: NullableTimestamp = None
    fetched_at: NullableTimestamp = None
    ingested_at: NullableTimestamp = None
    knowledge_as_of: NullableTimestamp = None
    label_maturity_time: NullableTimestamp = None
    materialization_environment: str = "development"
    materialization_kind: str = "observation"
    observed_at: NullableTimestamp = None
    prediction_origin_time: NullableTimestamp = None
    retracted_at: NullableTimestamp = None
    source_published_at: NullableTimestamp = None
    store_timezone: str = "Asia/Taipei"

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> TimeContract:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        if "available_at" in data:
            values["available_at"] = data["available_at"]
        if "build_at" in data:
            values["build_at"] = data["build_at"]
        if "business_day_boundary" in data:
            values["business_day_boundary"] = data["business_day_boundary"]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "effective_from" in data:
            values["effective_from"] = data["effective_from"]
        if "effective_to" in data:
            values["effective_to"] = data["effective_to"]
        if "event_time" in data:
            values["event_time"] = data["event_time"]
        if "fetched_at" in data:
            values["fetched_at"] = data["fetched_at"]
        if "ingested_at" in data:
            values["ingested_at"] = data["ingested_at"]
        if "knowledge_as_of" in data:
            values["knowledge_as_of"] = data["knowledge_as_of"]
        if "label_maturity_time" in data:
            values["label_maturity_time"] = data["label_maturity_time"]
        if "materialization_environment" in data:
            values["materialization_environment"] = data["materialization_environment"]
        if "materialization_kind" in data:
            values["materialization_kind"] = data["materialization_kind"]
        if "observed_at" in data:
            values["observed_at"] = data["observed_at"]
        if "prediction_origin_time" in data:
            values["prediction_origin_time"] = data["prediction_origin_time"]
        if "retracted_at" in data:
            values["retracted_at"] = data["retracted_at"]
        if "source_published_at" in data:
            values["source_published_at"] = data["source_published_at"]
        if "store_timezone" in data:
            values["store_timezone"] = data["store_timezone"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["available_at"] = self.available_at
        data["build_at"] = self.build_at
        data["business_day_boundary"] = self.business_day_boundary
        data["contract_version"] = self.contract_version
        data["effective_from"] = self.effective_from
        data["effective_to"] = self.effective_to
        data["event_time"] = self.event_time
        data["fetched_at"] = self.fetched_at
        data["ingested_at"] = self.ingested_at
        data["knowledge_as_of"] = self.knowledge_as_of
        data["label_maturity_time"] = self.label_maturity_time
        data["materialization_environment"] = self.materialization_environment
        data["materialization_kind"] = self.materialization_kind
        data["observed_at"] = self.observed_at
        data["prediction_origin_time"] = self.prediction_origin_time
        data["retracted_at"] = self.retracted_at
        data["source_published_at"] = self.source_published_at
        data["store_timezone"] = self.store_timezone
        return data

