# Generated by packages/oday_data_product_contracts_client/codegen.py -- do not edit.
#
# Contract:  emgi.catchment-profile.v1 (decision_product, v1.0.0)
# Release:   oday-data-product-contracts.v0.4.1
# Producer:  alfloop-dev/oday-data-platform@245aa00e417b6f8450baa608e8976584e00be6fc
# Schema:    schemas/catchment-profile.schema.json
# Digest:    a4e20c9d01a7db4680d3363f78e302bae2955aec1a63c45e486a5de310b04aee
"""Canonical contract schemas for published versioned catchment profiles (emgi.catchment-profile.v1) aggregating multi-domain observations over versioned route/catchment geometry, preserving routing provider, graph snapshot and quality flags, and returning explicit unavailable states in EMGI v0.4.1."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

CONTRACT_ID = "emgi.catchment-profile.v1"
CONTRACT_VERSION = "1.0.0"
CONTRACT_CATEGORY = "decision_product"
SCHEMA_FILE = "schemas/catchment-profile.schema.json"
SCHEMA_SHA256 = "a4e20c9d01a7db4680d3363f78e302bae2955aec1a63c45e486a5de310b04aee"
ROOT_MODEL = "CatchmentProfileDocument"


class CoverageState(StrEnum):
    """Coverage state of a specific domain for this catchment."""

    complete = "complete"
    partial = "partial"
    empty = "empty"
    missing = "missing"
    withheld = "withheld"
    quarantined = "quarantined"
    stale = "stale"
    degraded = "degraded"
    unobserved = "unobserved"


class DomainStatus(StrEnum):
    """Availability state of a specific domain aggregation."""

    available = "available"
    partial = "partial"
    unavailable = "unavailable"


class FreshnessState(StrEnum):
    """Freshness verdict relative to declared SLA."""

    fresh = "fresh"
    stale = "stale"
    unknown = "unknown"
    not_applicable = "not_applicable"


class PeriodGrain(StrEnum):
    """Temporal aggregation grain of the catchment profile."""

    HOURLY = "HOURLY"
    DAILY = "DAILY"
    WEEKDAY = "WEEKDAY"
    WEEKEND = "WEEKEND"
    PEAK_AM = "PEAK_AM"
    PEAK_PM = "PEAK_PM"
    OFF_PEAK = "OFF_PEAK"
    NIGHT = "NIGHT"
    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    ANNUAL = "ANNUAL"


class ProductComponentKind(StrEnum):
    """Component domain kind composing a published data product."""

    GEOGRAPHY = "GEOGRAPHY"
    DEMOGRAPHICS = "DEMOGRAPHICS"
    POI = "POI"
    COMPETITOR = "COMPETITOR"
    RENT = "RENT"
    TRANSPORT = "TRANSPORT"
    MOBILITY = "MOBILITY"
    EVENTS = "EVENTS"
    COVERAGE = "COVERAGE"
    ACQUISITION = "ACQUISITION"
    FEATURE_SET = "FEATURE_SET"
    MODEL_PREDICTION = "MODEL_PREDICTION"
    CUSTOM = "CUSTOM"


class ReadinessLevel(StrEnum):
    """Categorical readiness level for consuming this catchment profile."""

    ready = "ready"
    usable_with_gaps = "usable_with_gaps"
    blocked = "blocked"
    unknown = "unknown"


class ReasonSeverity(StrEnum):
    """Severity of a readiness explanation reason."""

    blocking = "blocking"
    degrading = "degrading"
    informational = "informational"


class TravelMode(StrEnum):
    """Supported travel modes for catchment boundary generation."""

    car = "car"
    motorcycle = "motorcycle"
    pedestrian = "pedestrian"
    bicycle = "bicycle"
    transit = "transit"
    truck = "truck"


@dataclass(frozen=True, slots=True)
class CatchmentBoundary:
    """Released contract model CatchmentBoundary."""

    catchment_id: str
    cutoff_seconds: int
    geom: dict[str, Any]
    graph_version: str
    h3_cells: list[str]
    h3_resolution: int
    routing_engine: str
    total_cells_count: int
    travel_mode: TravelMode
    area_sq_meters: float | None = None
    created_at: str | None = None
    estimation_status: str = "exact"
    is_scooter_estimated: bool = False
    isochrone_cutoff_minutes: float | None = None
    quality_flags: list[str] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> CatchmentBoundary:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["catchment_id"] = data["catchment_id"]
        values["cutoff_seconds"] = data["cutoff_seconds"]
        values["geom"] = data["geom"]
        values["graph_version"] = data["graph_version"]
        values["h3_cells"] = list(data["h3_cells"])
        values["h3_resolution"] = data["h3_resolution"]
        values["routing_engine"] = data["routing_engine"]
        values["total_cells_count"] = data["total_cells_count"]
        values["travel_mode"] = TravelMode(data["travel_mode"])
        if "area_sq_meters" in data:
            values["area_sq_meters"] = data["area_sq_meters"]
        if "created_at" in data:
            values["created_at"] = data["created_at"]
        if "estimation_status" in data:
            values["estimation_status"] = data["estimation_status"]
        if "is_scooter_estimated" in data:
            values["is_scooter_estimated"] = data["is_scooter_estimated"]
        if "isochrone_cutoff_minutes" in data:
            values["isochrone_cutoff_minutes"] = data["isochrone_cutoff_minutes"]
        if "quality_flags" in data:
            values["quality_flags"] = list(data["quality_flags"])
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["catchment_id"] = self.catchment_id
        data["cutoff_seconds"] = self.cutoff_seconds
        data["geom"] = self.geom
        data["graph_version"] = self.graph_version
        data["h3_cells"] = list(self.h3_cells)
        data["h3_resolution"] = self.h3_resolution
        data["routing_engine"] = self.routing_engine
        data["total_cells_count"] = self.total_cells_count
        data["travel_mode"] = self.travel_mode.value
        if self.area_sq_meters is not None:
            data["area_sq_meters"] = self.area_sq_meters
        if self.created_at is not None:
            data["created_at"] = self.created_at
        data["estimation_status"] = self.estimation_status
        data["is_scooter_estimated"] = self.is_scooter_estimated
        if self.isochrone_cutoff_minutes is not None:
            data["isochrone_cutoff_minutes"] = self.isochrone_cutoff_minutes
        data["quality_flags"] = list(self.quality_flags)
        return data


@dataclass(frozen=True, slots=True)
class CatchmentCompetitors:
    """Released contract model CatchmentCompetitors."""

    status: DomainStatus
    active_competitors: int | None = None
    average_capacity: float | None = None
    brands_present: list[str] = field(default_factory=list)
    capacity_sample_count: int = 0
    competitor_density_per_sq_km: float | None = None
    price_tier_distribution: dict[str, Any] | None = None
    source_support: SourceSupportSummary | None = None
    stores_by_brand: dict[str, Any] = field(default_factory=dict)
    stores_by_category: dict[str, Any] = field(default_factory=dict)
    total_capacity: float | None = None
    total_competitors: int | None = None
    unavailable_reason: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> CatchmentCompetitors:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["status"] = DomainStatus(data["status"])
        if "active_competitors" in data:
            values["active_competitors"] = data["active_competitors"]
        if "average_capacity" in data:
            values["average_capacity"] = data["average_capacity"]
        if "brands_present" in data:
            values["brands_present"] = list(data["brands_present"])
        if "capacity_sample_count" in data:
            values["capacity_sample_count"] = data["capacity_sample_count"]
        if "competitor_density_per_sq_km" in data:
            values["competitor_density_per_sq_km"] = data["competitor_density_per_sq_km"]
        if "price_tier_distribution" in data:
            values["price_tier_distribution"] = data["price_tier_distribution"]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "stores_by_brand" in data:
            values["stores_by_brand"] = data["stores_by_brand"]
        if "stores_by_category" in data:
            values["stores_by_category"] = data["stores_by_category"]
        if "total_capacity" in data:
            values["total_capacity"] = data["total_capacity"]
        if "total_competitors" in data:
            values["total_competitors"] = data["total_competitors"]
        if "unavailable_reason" in data:
            values["unavailable_reason"] = data["unavailable_reason"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["status"] = self.status.value
        if self.active_competitors is not None:
            data["active_competitors"] = self.active_competitors
        if self.average_capacity is not None:
            data["average_capacity"] = self.average_capacity
        data["brands_present"] = list(self.brands_present)
        data["capacity_sample_count"] = self.capacity_sample_count
        if self.competitor_density_per_sq_km is not None:
            data["competitor_density_per_sq_km"] = self.competitor_density_per_sq_km
        if self.price_tier_distribution is not None:
            data["price_tier_distribution"] = self.price_tier_distribution
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        data["stores_by_brand"] = self.stores_by_brand
        data["stores_by_category"] = self.stores_by_category
        if self.total_capacity is not None:
            data["total_capacity"] = self.total_capacity
        if self.total_competitors is not None:
            data["total_competitors"] = self.total_competitors
        if self.unavailable_reason is not None:
            data["unavailable_reason"] = self.unavailable_reason
        return data


@dataclass(frozen=True, slots=True)
class CatchmentCoverage:
    """Released contract model CatchmentCoverage."""

    domain_coverage: dict[str, Any]
    overall_readiness: ReadinessLevel
    blocked_domains: list[str] = field(default_factory=list)
    domain_freshness: dict[str, Any] = field(default_factory=dict)
    has_gaps: bool = False
    readiness_reasons: list[ReadinessReason] = field(default_factory=list)
    source_support: SourceSupportSummary | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> CatchmentCoverage:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["domain_coverage"] = data["domain_coverage"]
        values["overall_readiness"] = ReadinessLevel(data["overall_readiness"])
        if "blocked_domains" in data:
            values["blocked_domains"] = list(data["blocked_domains"])
        if "domain_freshness" in data:
            values["domain_freshness"] = data["domain_freshness"]
        if "has_gaps" in data:
            values["has_gaps"] = data["has_gaps"]
        if "readiness_reasons" in data:
            values["readiness_reasons"] = [ReadinessReason.from_dict(item) for item in data["readiness_reasons"]]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["domain_coverage"] = self.domain_coverage
        data["overall_readiness"] = self.overall_readiness.value
        data["blocked_domains"] = list(self.blocked_domains)
        data["domain_freshness"] = self.domain_freshness
        data["has_gaps"] = self.has_gaps
        data["readiness_reasons"] = [item.to_dict() for item in self.readiness_reasons]
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        return data


@dataclass(frozen=True, slots=True)
class CatchmentDemographics:
    """Released contract model CatchmentDemographics."""

    status: DomainStatus
    age_distribution: dict[str, Any] | None = None
    daytime_population_ratio: float | None = None
    density_per_sq_km: float | None = None
    female_population: float | None = None
    household_count: float | None = None
    male_population: float | None = None
    source_support: SourceSupportSummary | None = None
    total_population: float | None = None
    unavailable_reason: str | None = None
    uncertainty_pct: float | None = None
    weight_methods: list[str] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> CatchmentDemographics:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["status"] = DomainStatus(data["status"])
        if "age_distribution" in data:
            values["age_distribution"] = data["age_distribution"]
        if "daytime_population_ratio" in data:
            values["daytime_population_ratio"] = data["daytime_population_ratio"]
        if "density_per_sq_km" in data:
            values["density_per_sq_km"] = data["density_per_sq_km"]
        if "female_population" in data:
            values["female_population"] = data["female_population"]
        if "household_count" in data:
            values["household_count"] = data["household_count"]
        if "male_population" in data:
            values["male_population"] = data["male_population"]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "total_population" in data:
            values["total_population"] = data["total_population"]
        if "unavailable_reason" in data:
            values["unavailable_reason"] = data["unavailable_reason"]
        if "uncertainty_pct" in data:
            values["uncertainty_pct"] = data["uncertainty_pct"]
        if "weight_methods" in data:
            values["weight_methods"] = list(data["weight_methods"])
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["status"] = self.status.value
        if self.age_distribution is not None:
            data["age_distribution"] = self.age_distribution
        if self.daytime_population_ratio is not None:
            data["daytime_population_ratio"] = self.daytime_population_ratio
        if self.density_per_sq_km is not None:
            data["density_per_sq_km"] = self.density_per_sq_km
        if self.female_population is not None:
            data["female_population"] = self.female_population
        if self.household_count is not None:
            data["household_count"] = self.household_count
        if self.male_population is not None:
            data["male_population"] = self.male_population
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        if self.total_population is not None:
            data["total_population"] = self.total_population
        if self.unavailable_reason is not None:
            data["unavailable_reason"] = self.unavailable_reason
        if self.uncertainty_pct is not None:
            data["uncertainty_pct"] = self.uncertainty_pct
        data["weight_methods"] = list(self.weight_methods)
        return data


@dataclass(frozen=True, slots=True)
class CatchmentMobility:
    """Released contract model CatchmentMobility."""

    status: DomainStatus
    activity_population: float | None = None
    dominant_archetype: str | None = None
    dwell_time_minutes: float | None = None
    hourly_distribution: dict[str, Any] | None = None
    is_calibrated: bool = False
    resident_population: float | None = None
    source_support: SourceSupportSummary | None = None
    unavailable_reason: str | None = None
    uncertainty_pct: float | None = None
    visitor_population: float | None = None
    worker_population: float | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> CatchmentMobility:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["status"] = DomainStatus(data["status"])
        if "activity_population" in data:
            values["activity_population"] = data["activity_population"]
        if "dominant_archetype" in data:
            values["dominant_archetype"] = data["dominant_archetype"]
        if "dwell_time_minutes" in data:
            values["dwell_time_minutes"] = data["dwell_time_minutes"]
        if "hourly_distribution" in data:
            values["hourly_distribution"] = data["hourly_distribution"]
        if "is_calibrated" in data:
            values["is_calibrated"] = data["is_calibrated"]
        if "resident_population" in data:
            values["resident_population"] = data["resident_population"]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "unavailable_reason" in data:
            values["unavailable_reason"] = data["unavailable_reason"]
        if "uncertainty_pct" in data:
            values["uncertainty_pct"] = data["uncertainty_pct"]
        if "visitor_population" in data:
            values["visitor_population"] = data["visitor_population"]
        if "worker_population" in data:
            values["worker_population"] = data["worker_population"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["status"] = self.status.value
        if self.activity_population is not None:
            data["activity_population"] = self.activity_population
        if self.dominant_archetype is not None:
            data["dominant_archetype"] = self.dominant_archetype
        if self.dwell_time_minutes is not None:
            data["dwell_time_minutes"] = self.dwell_time_minutes
        if self.hourly_distribution is not None:
            data["hourly_distribution"] = self.hourly_distribution
        data["is_calibrated"] = self.is_calibrated
        if self.resident_population is not None:
            data["resident_population"] = self.resident_population
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        if self.unavailable_reason is not None:
            data["unavailable_reason"] = self.unavailable_reason
        if self.uncertainty_pct is not None:
            data["uncertainty_pct"] = self.uncertainty_pct
        if self.visitor_population is not None:
            data["visitor_population"] = self.visitor_population
        if self.worker_population is not None:
            data["worker_population"] = self.worker_population
        return data


@dataclass(frozen=True, slots=True)
class CatchmentOrigin:
    """Released contract model CatchmentOrigin."""

    latitude: float
    longitude: float
    origin_geom: dict[str, Any]
    origin_h3: str
    origin_id: str
    address: str | None = None
    admin_code: str | None = None
    county: str | None = None
    district: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> CatchmentOrigin:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["latitude"] = data["latitude"]
        values["longitude"] = data["longitude"]
        values["origin_geom"] = data["origin_geom"]
        values["origin_h3"] = data["origin_h3"]
        values["origin_id"] = data["origin_id"]
        if "address" in data:
            values["address"] = data["address"]
        if "admin_code" in data:
            values["admin_code"] = data["admin_code"]
        if "county" in data:
            values["county"] = data["county"]
        if "district" in data:
            values["district"] = data["district"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["latitude"] = self.latitude
        data["longitude"] = self.longitude
        data["origin_geom"] = self.origin_geom
        data["origin_h3"] = self.origin_h3
        data["origin_id"] = self.origin_id
        if self.address is not None:
            data["address"] = self.address
        if self.admin_code is not None:
            data["admin_code"] = self.admin_code
        if self.county is not None:
            data["county"] = self.county
        if self.district is not None:
            data["district"] = self.district
        return data


@dataclass(frozen=True, slots=True)
class CatchmentProfile:
    """Released contract model CatchmentProfile."""

    boundary: CatchmentBoundary
    competitors: CatchmentCompetitors
    coverage: CatchmentCoverage
    demographics: CatchmentDemographics
    mobility: CatchmentMobility
    origin: CatchmentOrigin
    period_grain: PeriodGrain
    period_key: str
    profile_id: str
    rent: CatchmentRent
    source_support: SourceSupportSummary
    traffic: CatchmentTrafficAccess
    component_manifest_refs: list[ProductComponentRef] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> CatchmentProfile:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["boundary"] = CatchmentBoundary.from_dict(data["boundary"])
        values["competitors"] = CatchmentCompetitors.from_dict(data["competitors"])
        values["coverage"] = CatchmentCoverage.from_dict(data["coverage"])
        values["demographics"] = CatchmentDemographics.from_dict(data["demographics"])
        values["mobility"] = CatchmentMobility.from_dict(data["mobility"])
        values["origin"] = CatchmentOrigin.from_dict(data["origin"])
        values["period_grain"] = PeriodGrain(data["period_grain"])
        values["period_key"] = data["period_key"]
        values["profile_id"] = data["profile_id"]
        values["rent"] = CatchmentRent.from_dict(data["rent"])
        values["source_support"] = SourceSupportSummary.from_dict(data["source_support"])
        values["traffic"] = CatchmentTrafficAccess.from_dict(data["traffic"])
        if "component_manifest_refs" in data:
            values["component_manifest_refs"] = [ProductComponentRef.from_dict(item) for item in data["component_manifest_refs"]]
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["boundary"] = self.boundary.to_dict()
        data["competitors"] = self.competitors.to_dict()
        data["coverage"] = self.coverage.to_dict()
        data["demographics"] = self.demographics.to_dict()
        data["mobility"] = self.mobility.to_dict()
        data["origin"] = self.origin.to_dict()
        data["period_grain"] = self.period_grain.value
        data["period_key"] = self.period_key
        data["profile_id"] = self.profile_id
        data["rent"] = self.rent.to_dict()
        data["source_support"] = self.source_support.to_dict()
        data["traffic"] = self.traffic.to_dict()
        data["component_manifest_refs"] = [item.to_dict() for item in self.component_manifest_refs]
        data["metadata"] = self.metadata
        return data


@dataclass(frozen=True, slots=True)
class CatchmentProfileDocument:
    """Released contract model CatchmentProfileDocument."""

    document_id: str
    generated_at: str
    period_grain: PeriodGrain
    period_key: str
    profiles: list[CatchmentProfile]
    source_support: SourceSupportSummary
    component_manifest_refs: list[ProductComponentRef] = field(default_factory=list)
    contract_version: str = "emgi.catchment-profile.v1"
    effective_as_of: str | None = None
    knowledge_as_of: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    product_version: str = "0.4.1"
    scope_principal_id: str | None = None
    tenant_id: str | None = "default"

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> CatchmentProfileDocument:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["document_id"] = data["document_id"]
        values["generated_at"] = data["generated_at"]
        values["period_grain"] = PeriodGrain(data["period_grain"])
        values["period_key"] = data["period_key"]
        values["profiles"] = [CatchmentProfile.from_dict(item) for item in data["profiles"]]
        values["source_support"] = SourceSupportSummary.from_dict(data["source_support"])
        if "component_manifest_refs" in data:
            values["component_manifest_refs"] = [ProductComponentRef.from_dict(item) for item in data["component_manifest_refs"]]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "effective_as_of" in data:
            values["effective_as_of"] = data["effective_as_of"]
        if "knowledge_as_of" in data:
            values["knowledge_as_of"] = data["knowledge_as_of"]
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        if "product_version" in data:
            values["product_version"] = data["product_version"]
        if "scope_principal_id" in data:
            values["scope_principal_id"] = data["scope_principal_id"]
        if "tenant_id" in data:
            values["tenant_id"] = data["tenant_id"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["document_id"] = self.document_id
        data["generated_at"] = self.generated_at
        data["period_grain"] = self.period_grain.value
        data["period_key"] = self.period_key
        data["profiles"] = [item.to_dict() for item in self.profiles]
        data["source_support"] = self.source_support.to_dict()
        data["component_manifest_refs"] = [item.to_dict() for item in self.component_manifest_refs]
        data["contract_version"] = self.contract_version
        if self.effective_as_of is not None:
            data["effective_as_of"] = self.effective_as_of
        if self.knowledge_as_of is not None:
            data["knowledge_as_of"] = self.knowledge_as_of
        data["metadata"] = self.metadata
        data["product_version"] = self.product_version
        if self.scope_principal_id is not None:
            data["scope_principal_id"] = self.scope_principal_id
        if self.tenant_id is not None:
            data["tenant_id"] = self.tenant_id
        return data


@dataclass(frozen=True, slots=True)
class CatchmentProfileRelease:
    """Released contract model CatchmentProfileRelease."""

    component_manifest_refs: list[ProductComponentRef]
    document: CatchmentProfileDocument
    release_id: str
    released_at: str
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> CatchmentProfileRelease:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["component_manifest_refs"] = [ProductComponentRef.from_dict(item) for item in data["component_manifest_refs"]]
        values["document"] = CatchmentProfileDocument.from_dict(data["document"])
        values["release_id"] = data["release_id"]
        values["released_at"] = data["released_at"]
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["component_manifest_refs"] = [item.to_dict() for item in self.component_manifest_refs]
        data["document"] = self.document.to_dict()
        data["release_id"] = self.release_id
        data["released_at"] = self.released_at
        data["metadata"] = self.metadata
        return data


@dataclass(frozen=True, slots=True)
class CatchmentRent:
    """Released contract model CatchmentRent."""

    status: DomainStatus
    confidence_pct: float | None = None
    fallback_level: str | None = None
    mean_rent_per_ping: float | None = None
    median_rent_per_ping: float | None = None
    p25_rent_per_ping: float | None = None
    p75_rent_per_ping: float | None = None
    property_tier: str | None = None
    sample_count: int = 0
    source_support: SourceSupportSummary | None = None
    unavailable_reason: str | None = None
    uncertainty_pct: float | None = None
    weighted_sample_count: float | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> CatchmentRent:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["status"] = DomainStatus(data["status"])
        if "confidence_pct" in data:
            values["confidence_pct"] = data["confidence_pct"]
        if "fallback_level" in data:
            values["fallback_level"] = data["fallback_level"]
        if "mean_rent_per_ping" in data:
            values["mean_rent_per_ping"] = data["mean_rent_per_ping"]
        if "median_rent_per_ping" in data:
            values["median_rent_per_ping"] = data["median_rent_per_ping"]
        if "p25_rent_per_ping" in data:
            values["p25_rent_per_ping"] = data["p25_rent_per_ping"]
        if "p75_rent_per_ping" in data:
            values["p75_rent_per_ping"] = data["p75_rent_per_ping"]
        if "property_tier" in data:
            values["property_tier"] = data["property_tier"]
        if "sample_count" in data:
            values["sample_count"] = data["sample_count"]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "unavailable_reason" in data:
            values["unavailable_reason"] = data["unavailable_reason"]
        if "uncertainty_pct" in data:
            values["uncertainty_pct"] = data["uncertainty_pct"]
        if "weighted_sample_count" in data:
            values["weighted_sample_count"] = data["weighted_sample_count"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["status"] = self.status.value
        if self.confidence_pct is not None:
            data["confidence_pct"] = self.confidence_pct
        if self.fallback_level is not None:
            data["fallback_level"] = self.fallback_level
        if self.mean_rent_per_ping is not None:
            data["mean_rent_per_ping"] = self.mean_rent_per_ping
        if self.median_rent_per_ping is not None:
            data["median_rent_per_ping"] = self.median_rent_per_ping
        if self.p25_rent_per_ping is not None:
            data["p25_rent_per_ping"] = self.p25_rent_per_ping
        if self.p75_rent_per_ping is not None:
            data["p75_rent_per_ping"] = self.p75_rent_per_ping
        if self.property_tier is not None:
            data["property_tier"] = self.property_tier
        data["sample_count"] = self.sample_count
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        if self.unavailable_reason is not None:
            data["unavailable_reason"] = self.unavailable_reason
        if self.uncertainty_pct is not None:
            data["uncertainty_pct"] = self.uncertainty_pct
        if self.weighted_sample_count is not None:
            data["weighted_sample_count"] = self.weighted_sample_count
        return data


@dataclass(frozen=True, slots=True)
class CatchmentTrafficAccess:
    """Released contract model CatchmentTrafficAccess."""

    status: DomainStatus
    hourly_volume_vph: int | None = None
    level_of_service: str | None = None
    mean_speed_kph: float | None = None
    motorcycle_hourly_volume: int | None = None
    motorcycle_ratio: float | None = None
    parking_facilities_count: int | None = None
    scooter_density_level: str | None = None
    source_support: SourceSupportSummary | None = None
    speed_ratio: float | None = None
    total_parking_spaces: int | None = None
    transit_daily_boardings: int | None = None
    transit_lines_count: int | None = None
    transit_stops_count: int | None = None
    unavailable_reason: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> CatchmentTrafficAccess:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["status"] = DomainStatus(data["status"])
        if "hourly_volume_vph" in data:
            values["hourly_volume_vph"] = data["hourly_volume_vph"]
        if "level_of_service" in data:
            values["level_of_service"] = data["level_of_service"]
        if "mean_speed_kph" in data:
            values["mean_speed_kph"] = data["mean_speed_kph"]
        if "motorcycle_hourly_volume" in data:
            values["motorcycle_hourly_volume"] = data["motorcycle_hourly_volume"]
        if "motorcycle_ratio" in data:
            values["motorcycle_ratio"] = data["motorcycle_ratio"]
        if "parking_facilities_count" in data:
            values["parking_facilities_count"] = data["parking_facilities_count"]
        if "scooter_density_level" in data:
            values["scooter_density_level"] = data["scooter_density_level"]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "speed_ratio" in data:
            values["speed_ratio"] = data["speed_ratio"]
        if "total_parking_spaces" in data:
            values["total_parking_spaces"] = data["total_parking_spaces"]
        if "transit_daily_boardings" in data:
            values["transit_daily_boardings"] = data["transit_daily_boardings"]
        if "transit_lines_count" in data:
            values["transit_lines_count"] = data["transit_lines_count"]
        if "transit_stops_count" in data:
            values["transit_stops_count"] = data["transit_stops_count"]
        if "unavailable_reason" in data:
            values["unavailable_reason"] = data["unavailable_reason"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["status"] = self.status.value
        if self.hourly_volume_vph is not None:
            data["hourly_volume_vph"] = self.hourly_volume_vph
        if self.level_of_service is not None:
            data["level_of_service"] = self.level_of_service
        if self.mean_speed_kph is not None:
            data["mean_speed_kph"] = self.mean_speed_kph
        if self.motorcycle_hourly_volume is not None:
            data["motorcycle_hourly_volume"] = self.motorcycle_hourly_volume
        if self.motorcycle_ratio is not None:
            data["motorcycle_ratio"] = self.motorcycle_ratio
        if self.parking_facilities_count is not None:
            data["parking_facilities_count"] = self.parking_facilities_count
        if self.scooter_density_level is not None:
            data["scooter_density_level"] = self.scooter_density_level
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        if self.speed_ratio is not None:
            data["speed_ratio"] = self.speed_ratio
        if self.total_parking_spaces is not None:
            data["total_parking_spaces"] = self.total_parking_spaces
        if self.transit_daily_boardings is not None:
            data["transit_daily_boardings"] = self.transit_daily_boardings
        if self.transit_lines_count is not None:
            data["transit_lines_count"] = self.transit_lines_count
        if self.transit_stops_count is not None:
            data["transit_stops_count"] = self.transit_stops_count
        if self.unavailable_reason is not None:
            data["unavailable_reason"] = self.unavailable_reason
        return data


@dataclass(frozen=True, slots=True)
class ProductComponentRef:
    """Released contract model ProductComponentRef."""

    component_id: str
    component_kind: ProductComponentKind
    contract_id: str
    sha256: str
    feature_manifest_id: str | None = None
    row_count: int | None = None
    size_bytes: int | None = None
    source_manifest_id: str | None = None
    storage_uri: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> ProductComponentRef:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["component_id"] = data["component_id"]
        values["component_kind"] = ProductComponentKind(data["component_kind"])
        values["contract_id"] = data["contract_id"]
        values["sha256"] = data["sha256"]
        if "feature_manifest_id" in data:
            values["feature_manifest_id"] = data["feature_manifest_id"]
        if "row_count" in data:
            values["row_count"] = data["row_count"]
        if "size_bytes" in data:
            values["size_bytes"] = data["size_bytes"]
        if "source_manifest_id" in data:
            values["source_manifest_id"] = data["source_manifest_id"]
        if "storage_uri" in data:
            values["storage_uri"] = data["storage_uri"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["component_id"] = self.component_id
        data["component_kind"] = self.component_kind.value
        data["contract_id"] = self.contract_id
        data["sha256"] = self.sha256
        if self.feature_manifest_id is not None:
            data["feature_manifest_id"] = self.feature_manifest_id
        if self.row_count is not None:
            data["row_count"] = self.row_count
        if self.size_bytes is not None:
            data["size_bytes"] = self.size_bytes
        if self.source_manifest_id is not None:
            data["source_manifest_id"] = self.source_manifest_id
        if self.storage_uri is not None:
            data["storage_uri"] = self.storage_uri
        return data


@dataclass(frozen=True, slots=True)
class ReadinessReason:
    """Released contract model ReadinessReason."""

    code: str
    detail: str
    severity: ReasonSeverity
    cell_id: str | None = None
    domain: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> ReadinessReason:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["code"] = data["code"]
        values["detail"] = data["detail"]
        values["severity"] = ReasonSeverity(data["severity"])
        if "cell_id" in data:
            values["cell_id"] = data["cell_id"]
        if "domain" in data:
            values["domain"] = data["domain"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["code"] = self.code
        data["detail"] = self.detail
        data["severity"] = self.severity.value
        if self.cell_id is not None:
            data["cell_id"] = self.cell_id
        if self.domain is not None:
            data["domain"] = self.domain
        return data


@dataclass(frozen=True, slots=True)
class SourceSupportSummary:
    """Released contract model SourceSupportSummary."""

    observation_count: int
    sample_count: int
    first_observed_at: str | None = None
    last_observed_at: str | None = None
    source_dataset_ids: list[str] = field(default_factory=list)
    source_manifest_ids: list[str] = field(default_factory=list)
    uncertainty_pct: float | None = None
    weight_methods: list[str] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SourceSupportSummary:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["observation_count"] = data["observation_count"]
        values["sample_count"] = data["sample_count"]
        if "first_observed_at" in data:
            values["first_observed_at"] = data["first_observed_at"]
        if "last_observed_at" in data:
            values["last_observed_at"] = data["last_observed_at"]
        if "source_dataset_ids" in data:
            values["source_dataset_ids"] = list(data["source_dataset_ids"])
        if "source_manifest_ids" in data:
            values["source_manifest_ids"] = list(data["source_manifest_ids"])
        if "uncertainty_pct" in data:
            values["uncertainty_pct"] = data["uncertainty_pct"]
        if "weight_methods" in data:
            values["weight_methods"] = list(data["weight_methods"])
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["observation_count"] = self.observation_count
        data["sample_count"] = self.sample_count
        if self.first_observed_at is not None:
            data["first_observed_at"] = self.first_observed_at
        if self.last_observed_at is not None:
            data["last_observed_at"] = self.last_observed_at
        data["source_dataset_ids"] = list(self.source_dataset_ids)
        data["source_manifest_ids"] = list(self.source_manifest_ids)
        if self.uncertainty_pct is not None:
            data["uncertainty_pct"] = self.uncertainty_pct
        data["weight_methods"] = list(self.weight_methods)
        return data

