# Generated by packages/oday_data_product_contracts_client/codegen.py -- do not edit.
#
# Contract:  emgi.field-survey.v1 (source_evidence, v1.0.0)
# Release:   oday-data-product-contracts.v0.4.1
# Producer:  alfloop-dev/oday-data-platform@245aa00e417b6f8450baa608e8976584e00be6fc
# Schema:    schemas/field-survey.schema.json
# Digest:    b9ac0d8e09a29d4f040f225b4f53ac4bc06c317d8b95ca9d97016da8bb938f4c
"""Portable, versioned document snapshot of governed field-survey observations and retractions."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

CONTRACT_ID = "emgi.field-survey.v1"
CONTRACT_VERSION = "1.0.0"
CONTRACT_CATEGORY = "source_evidence"
SCHEMA_FILE = "schemas/field-survey.schema.json"
SCHEMA_SHA256 = "b9ac0d8e09a29d4f040f225b4f53ac4bc06c317d8b95ca9d97016da8bb938f4c"
ROOT_MODEL = "FieldSurveyDocument"


class MediaKind(StrEnum):
    """Kind of media attachment associated with the survey."""

    PHOTO = "PHOTO"
    VIDEO = "VIDEO"
    AUDIO = "AUDIO"
    DOCUMENT = "DOCUMENT"
    SIGNATURE = "SIGNATURE"
    OTHER = "OTHER"


class ReviewStatus(StrEnum):
    """Governance review status of a field survey submission."""

    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    NEEDS_REVISION = "NEEDS_REVISION"


class SurveyLifecycleKind(StrEnum):
    """Evidentiary lifecycle action represented by this observation."""

    INITIAL = "INITIAL"
    CORRECTION = "CORRECTION"
    RESURVEY = "RESURVEY"


class SurveyType(StrEnum):
    """Functional classification of the survey campaign or questionnaire."""

    PHYSICAL_FEASIBILITY = "PHYSICAL_FEASIBILITY"
    STORE_AUDIT = "STORE_AUDIT"
    CANDIDATE_SITE = "CANDIDATE_SITE"
    COMPETITOR_POLL = "COMPETITOR_POLL"
    FOOT_TRAFFIC = "FOOT_TRAFFIC"
    MERCHANT_VERIFICATION = "MERCHANT_VERIFICATION"
    CUSTOM = "CUSTOM"


class TargetEntityKind(StrEnum):
    """Category of entity targeted by the field survey observation."""

    CANDIDATE_SITE = "CANDIDATE_SITE"
    STORE = "STORE"
    POI = "POI"
    PROPERTY = "PROPERTY"
    STREET_SEGMENT = "STREET_SEGMENT"
    COMPETITOR = "COMPETITOR"
    CUSTOM = "CUSTOM"


@dataclass(frozen=True, slots=True)
class FieldSurveyObservation:
    """Governed field-survey observation capturing verified on-site evidence and lineage."""

    blob_id: str
    campaign_id: str
    effective_from: str
    location: SurveyLocation
    observation_id: str
    review: SurveyReview
    scope_principal_id: str
    submission_id: str
    submitted_at: str
    submitter_id: str
    survey_id: str
    survey_type: SurveyType
    surveyed_at: str
    target_entity_id: str
    target_entity_kind: TargetEntityKind
    attributes: dict[str, Any] = field(default_factory=dict)
    confidence: float | None = 1.0
    effective_to: str | None = None
    lifecycle_kind: SurveyLifecycleKind = SurveyLifecycleKind.INITIAL
    media_attachments: list[MediaAttachment] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    replaces_observation_id: str | None = None
    replaces_survey_id: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> FieldSurveyObservation:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["blob_id"] = data["blob_id"]
        values["campaign_id"] = data["campaign_id"]
        values["effective_from"] = data["effective_from"]
        values["location"] = SurveyLocation.from_dict(data["location"])
        values["observation_id"] = data["observation_id"]
        values["review"] = SurveyReview.from_dict(data["review"])
        values["scope_principal_id"] = data["scope_principal_id"]
        values["submission_id"] = data["submission_id"]
        values["submitted_at"] = data["submitted_at"]
        values["submitter_id"] = data["submitter_id"]
        values["survey_id"] = data["survey_id"]
        values["survey_type"] = SurveyType(data["survey_type"])
        values["surveyed_at"] = data["surveyed_at"]
        values["target_entity_id"] = data["target_entity_id"]
        values["target_entity_kind"] = TargetEntityKind(data["target_entity_kind"])
        if "attributes" in data:
            values["attributes"] = data["attributes"]
        if "confidence" in data:
            values["confidence"] = data["confidence"]
        if "effective_to" in data:
            values["effective_to"] = data["effective_to"]
        if "lifecycle_kind" in data:
            values["lifecycle_kind"] = SurveyLifecycleKind(data["lifecycle_kind"])
        if "media_attachments" in data:
            values["media_attachments"] = [MediaAttachment.from_dict(item) for item in data["media_attachments"]]
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        if "replaces_observation_id" in data:
            values["replaces_observation_id"] = data["replaces_observation_id"]
        if "replaces_survey_id" in data:
            values["replaces_survey_id"] = data["replaces_survey_id"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["blob_id"] = self.blob_id
        data["campaign_id"] = self.campaign_id
        data["effective_from"] = self.effective_from
        data["location"] = self.location.to_dict()
        data["observation_id"] = self.observation_id
        data["review"] = self.review.to_dict()
        data["scope_principal_id"] = self.scope_principal_id
        data["submission_id"] = self.submission_id
        data["submitted_at"] = self.submitted_at
        data["submitter_id"] = self.submitter_id
        data["survey_id"] = self.survey_id
        data["survey_type"] = self.survey_type.value
        data["surveyed_at"] = self.surveyed_at
        data["target_entity_id"] = self.target_entity_id
        data["target_entity_kind"] = self.target_entity_kind.value
        data["attributes"] = self.attributes
        if self.confidence is not None:
            data["confidence"] = self.confidence
        if self.effective_to is not None:
            data["effective_to"] = self.effective_to
        data["lifecycle_kind"] = self.lifecycle_kind.value
        data["media_attachments"] = [item.to_dict() for item in self.media_attachments]
        data["metadata"] = self.metadata
        if self.replaces_observation_id is not None:
            data["replaces_observation_id"] = self.replaces_observation_id
        if self.replaces_survey_id is not None:
            data["replaces_survey_id"] = self.replaces_survey_id
        return data


@dataclass(frozen=True, slots=True)
class MediaAttachment:
    """Evidentiary media artifact attached to the survey submission."""

    blob_id: str
    captured_at: str
    media_id: str
    media_kind: MediaKind
    sha256: str
    storage_uri: str
    caption: str | None = None
    media_type: str = "image/jpeg"
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> MediaAttachment:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["blob_id"] = data["blob_id"]
        values["captured_at"] = data["captured_at"]
        values["media_id"] = data["media_id"]
        values["media_kind"] = MediaKind(data["media_kind"])
        values["sha256"] = data["sha256"]
        values["storage_uri"] = data["storage_uri"]
        if "caption" in data:
            values["caption"] = data["caption"]
        if "media_type" in data:
            values["media_type"] = data["media_type"]
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["blob_id"] = self.blob_id
        data["captured_at"] = self.captured_at
        data["media_id"] = self.media_id
        data["media_kind"] = self.media_kind.value
        data["sha256"] = self.sha256
        data["storage_uri"] = self.storage_uri
        if self.caption is not None:
            data["caption"] = self.caption
        data["media_type"] = self.media_type
        data["metadata"] = self.metadata
        return data


@dataclass(frozen=True, slots=True)
class SurveyLocation:
    """Spatial coordinate and address anchor for the field survey."""

    latitude: float
    longitude: float
    address: str | None = None
    h3_index: str | None = None
    srid: int = 4326

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SurveyLocation:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["latitude"] = data["latitude"]
        values["longitude"] = data["longitude"]
        if "address" in data:
            values["address"] = data["address"]
        if "h3_index" in data:
            values["h3_index"] = data["h3_index"]
        if "srid" in data:
            values["srid"] = data["srid"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["latitude"] = self.latitude
        data["longitude"] = self.longitude
        if self.address is not None:
            data["address"] = self.address
        if self.h3_index is not None:
            data["h3_index"] = self.h3_index
        data["srid"] = self.srid
        return data


@dataclass(frozen=True, slots=True)
class SurveyReview:
    """Independent review and governance lineage record for a survey submission."""

    review_status: ReviewStatus
    reviewed_at: str
    reviewer_id: str
    review_checklist: dict[str, Any] = field(default_factory=dict)
    review_comment: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SurveyReview:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["review_status"] = ReviewStatus(data["review_status"])
        values["reviewed_at"] = data["reviewed_at"]
        values["reviewer_id"] = data["reviewer_id"]
        if "review_checklist" in data:
            values["review_checklist"] = data["review_checklist"]
        if "review_comment" in data:
            values["review_comment"] = data["review_comment"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["review_status"] = self.review_status.value
        data["reviewed_at"] = self.reviewed_at
        data["reviewer_id"] = self.reviewer_id
        data["review_checklist"] = self.review_checklist
        if self.review_comment is not None:
            data["review_comment"] = self.review_comment
        return data


@dataclass(frozen=True, slots=True)
class FieldSurveyDocument:
    """Portable, versioned document snapshot of governed field-survey observations and retractions.

    Root model of contract `emgi.field-survey.v1`
    (source_evidence, version 1.0.0).
    """

    contract_id: str = "emgi.field-survey.v1"
    field_surveys: list[FieldSurveyObservation] = field(default_factory=list)
    retractions: list[dict[str, Any]] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> FieldSurveyDocument:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        if "contract_id" in data:
            values["contract_id"] = data["contract_id"]
        if "field_surveys" in data:
            values["field_surveys"] = [FieldSurveyObservation.from_dict(item) for item in data["field_surveys"]]
        if "retractions" in data:
            values["retractions"] = list(data["retractions"])
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["contract_id"] = self.contract_id
        data["field_surveys"] = [item.to_dict() for item in self.field_surveys]
        data["retractions"] = list(self.retractions)
        return data

