# Generated by packages/oday_data_product_contracts_client/codegen.py -- do not edit.
#
# Contract:  emgi.market-cell-profile.v1 (decision_product, v1.0.0)
# Release:   oday-data-product-contracts.v0.4.1
# Producer:  alfloop-dev/oday-data-platform@245aa00e417b6f8450baa608e8976584e00be6fc
# Schema:    schemas/market-cell-profile.schema.json
# Digest:    d239e2aa294cd0a8382b5d653147b653b367cc4d3e695a5c9a7a76c38b91f103
"""Canonical contract schemas for published market cell profiles (emgi.market-cell-profile.v1) and market zone profiles across H3 space, period grain, multi-domain observations, source support, and component manifests in EMGI v0.4.1."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

CONTRACT_ID = "emgi.market-cell-profile.v1"
CONTRACT_VERSION = "1.0.0"
CONTRACT_CATEGORY = "decision_product"
SCHEMA_FILE = "schemas/market-cell-profile.schema.json"
SCHEMA_SHA256 = "d239e2aa294cd0a8382b5d653147b653b367cc4d3e695a5c9a7a76c38b91f103"
ROOT_MODEL = "MarketCellProfileDocument"


class CoverageState(StrEnum):
    """Coverage state of a specific domain for this cell."""

    complete = "complete"
    partial = "partial"
    empty = "empty"
    missing = "missing"
    withheld = "withheld"
    quarantined = "quarantined"
    stale = "stale"
    degraded = "degraded"
    unobserved = "unobserved"


class FreshnessState(StrEnum):
    """Freshness verdict relative to declared SLA."""

    fresh = "fresh"
    stale = "stale"
    unknown = "unknown"
    not_applicable = "not_applicable"


class PeriodGrain(StrEnum):
    """Temporal aggregation grain of the market cell or zone profile."""

    HOURLY = "HOURLY"
    DAILY = "DAILY"
    WEEKDAY = "WEEKDAY"
    WEEKEND = "WEEKEND"
    PEAK_AM = "PEAK_AM"
    PEAK_PM = "PEAK_PM"
    OFF_PEAK = "OFF_PEAK"
    NIGHT = "NIGHT"
    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    ANNUAL = "ANNUAL"


class ProductComponentKind(StrEnum):
    """Component domain kind composing a published data product."""

    GEOGRAPHY = "GEOGRAPHY"
    DEMOGRAPHICS = "DEMOGRAPHICS"
    POI = "POI"
    COMPETITOR = "COMPETITOR"
    RENT = "RENT"
    TRANSPORT = "TRANSPORT"
    MOBILITY = "MOBILITY"
    EVENTS = "EVENTS"
    COVERAGE = "COVERAGE"
    ACQUISITION = "ACQUISITION"
    FEATURE_SET = "FEATURE_SET"
    MODEL_PREDICTION = "MODEL_PREDICTION"
    CUSTOM = "CUSTOM"


class ReadinessLevel(StrEnum):
    """Categorical readiness level for consuming this market cell."""

    ready = "ready"
    usable_with_gaps = "usable_with_gaps"
    blocked = "blocked"
    unknown = "unknown"


class ReasonSeverity(StrEnum):
    """Severity of a readiness explanation reason."""

    blocking = "blocking"
    degrading = "degrading"
    informational = "informational"


@dataclass(frozen=True, slots=True)
class MarketCellCompetitors:
    """Released contract model MarketCellCompetitors."""

    active_competitors: int
    brands_present: list[str]
    stores_by_brand: dict[str, Any]
    stores_by_category: dict[str, Any]
    total_competitors: int
    average_capacity: float | None = None
    capacity_sample_count: int = 0
    competitor_density: float | None = None
    price_tier_distribution: dict[str, Any] | None = None
    source_support: SourceSupportSummary | None = None
    total_capacity: float | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> MarketCellCompetitors:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["active_competitors"] = data["active_competitors"]
        values["brands_present"] = list(data["brands_present"])
        values["stores_by_brand"] = data["stores_by_brand"]
        values["stores_by_category"] = data["stores_by_category"]
        values["total_competitors"] = data["total_competitors"]
        if "average_capacity" in data:
            values["average_capacity"] = data["average_capacity"]
        if "capacity_sample_count" in data:
            values["capacity_sample_count"] = data["capacity_sample_count"]
        if "competitor_density" in data:
            values["competitor_density"] = data["competitor_density"]
        if "price_tier_distribution" in data:
            values["price_tier_distribution"] = data["price_tier_distribution"]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "total_capacity" in data:
            values["total_capacity"] = data["total_capacity"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["active_competitors"] = self.active_competitors
        data["brands_present"] = list(self.brands_present)
        data["stores_by_brand"] = self.stores_by_brand
        data["stores_by_category"] = self.stores_by_category
        data["total_competitors"] = self.total_competitors
        if self.average_capacity is not None:
            data["average_capacity"] = self.average_capacity
        data["capacity_sample_count"] = self.capacity_sample_count
        if self.competitor_density is not None:
            data["competitor_density"] = self.competitor_density
        if self.price_tier_distribution is not None:
            data["price_tier_distribution"] = self.price_tier_distribution
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        if self.total_capacity is not None:
            data["total_capacity"] = self.total_capacity
        return data


@dataclass(frozen=True, slots=True)
class MarketCellCoverage:
    """Released contract model MarketCellCoverage."""

    domain_coverage: dict[str, Any]
    overall_readiness: ReadinessLevel
    domain_freshness: dict[str, Any] = field(default_factory=dict)
    has_gaps: bool = False
    readiness_reasons: list[ReadinessReason] = field(default_factory=list)
    source_support: SourceSupportSummary | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> MarketCellCoverage:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["domain_coverage"] = data["domain_coverage"]
        values["overall_readiness"] = ReadinessLevel(data["overall_readiness"])
        if "domain_freshness" in data:
            values["domain_freshness"] = data["domain_freshness"]
        if "has_gaps" in data:
            values["has_gaps"] = data["has_gaps"]
        if "readiness_reasons" in data:
            values["readiness_reasons"] = [ReadinessReason.from_dict(item) for item in data["readiness_reasons"]]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["domain_coverage"] = self.domain_coverage
        data["overall_readiness"] = self.overall_readiness.value
        data["domain_freshness"] = self.domain_freshness
        data["has_gaps"] = self.has_gaps
        data["readiness_reasons"] = [item.to_dict() for item in self.readiness_reasons]
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        return data


@dataclass(frozen=True, slots=True)
class MarketCellDemographics:
    """Released contract model MarketCellDemographics."""

    total_population: Any
    age_distribution: dict[str, Any] | None = None
    daytime_population_ratio: float | None = None
    female_population: Any = None
    household_count: Any = None
    male_population: Any = None
    source_support: SourceSupportSummary | None = None
    uncertainty_pct: float | None = None
    weight_method: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> MarketCellDemographics:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["total_population"] = data["total_population"]
        if "age_distribution" in data:
            values["age_distribution"] = data["age_distribution"]
        if "daytime_population_ratio" in data:
            values["daytime_population_ratio"] = data["daytime_population_ratio"]
        if "female_population" in data:
            values["female_population"] = data["female_population"]
        if "household_count" in data:
            values["household_count"] = data["household_count"]
        if "male_population" in data:
            values["male_population"] = data["male_population"]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "uncertainty_pct" in data:
            values["uncertainty_pct"] = data["uncertainty_pct"]
        if "weight_method" in data:
            values["weight_method"] = data["weight_method"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["total_population"] = self.total_population
        if self.age_distribution is not None:
            data["age_distribution"] = self.age_distribution
        if self.daytime_population_ratio is not None:
            data["daytime_population_ratio"] = self.daytime_population_ratio
        if self.female_population is not None:
            data["female_population"] = self.female_population
        if self.household_count is not None:
            data["household_count"] = self.household_count
        if self.male_population is not None:
            data["male_population"] = self.male_population
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        if self.uncertainty_pct is not None:
            data["uncertainty_pct"] = self.uncertainty_pct
        if self.weight_method is not None:
            data["weight_method"] = self.weight_method
        return data


@dataclass(frozen=True, slots=True)
class MarketCellMobility:
    """Released contract model MarketCellMobility."""

    activity_population: float | None = None
    dwell_time_minutes: float | None = None
    hourly_distribution: dict[str, Any] | None = None
    is_calibrated: bool = False
    resident_population: float | None = None
    source_support: SourceSupportSummary | None = None
    uncertainty_pct: float | None = None
    visitor_population: float | None = None
    worker_population: float | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> MarketCellMobility:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        if "activity_population" in data:
            values["activity_population"] = data["activity_population"]
        if "dwell_time_minutes" in data:
            values["dwell_time_minutes"] = data["dwell_time_minutes"]
        if "hourly_distribution" in data:
            values["hourly_distribution"] = data["hourly_distribution"]
        if "is_calibrated" in data:
            values["is_calibrated"] = data["is_calibrated"]
        if "resident_population" in data:
            values["resident_population"] = data["resident_population"]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "uncertainty_pct" in data:
            values["uncertainty_pct"] = data["uncertainty_pct"]
        if "visitor_population" in data:
            values["visitor_population"] = data["visitor_population"]
        if "worker_population" in data:
            values["worker_population"] = data["worker_population"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        if self.activity_population is not None:
            data["activity_population"] = self.activity_population
        if self.dwell_time_minutes is not None:
            data["dwell_time_minutes"] = self.dwell_time_minutes
        if self.hourly_distribution is not None:
            data["hourly_distribution"] = self.hourly_distribution
        data["is_calibrated"] = self.is_calibrated
        if self.resident_population is not None:
            data["resident_population"] = self.resident_population
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        if self.uncertainty_pct is not None:
            data["uncertainty_pct"] = self.uncertainty_pct
        if self.visitor_population is not None:
            data["visitor_population"] = self.visitor_population
        if self.worker_population is not None:
            data["worker_population"] = self.worker_population
        return data


@dataclass(frozen=True, slots=True)
class MarketCellProfile:
    """Released contract model MarketCellProfile."""

    cell_id: str
    competitors: MarketCellCompetitors
    coverage: MarketCellCoverage
    demographics: MarketCellDemographics
    h3_index: str
    h3_resolution: int
    mobility: MarketCellMobility
    period_grain: PeriodGrain
    period_key: str
    rent: MarketCellRent
    source_support: SourceSupportSummary
    admin_code: str | None = None
    centroid_lat: float | None = None
    centroid_lng: float | None = None
    component_manifest_refs: list[ProductComponentRef] = field(default_factory=list)
    county: str | None = None
    district: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> MarketCellProfile:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["cell_id"] = data["cell_id"]
        values["competitors"] = MarketCellCompetitors.from_dict(data["competitors"])
        values["coverage"] = MarketCellCoverage.from_dict(data["coverage"])
        values["demographics"] = MarketCellDemographics.from_dict(data["demographics"])
        values["h3_index"] = data["h3_index"]
        values["h3_resolution"] = data["h3_resolution"]
        values["mobility"] = MarketCellMobility.from_dict(data["mobility"])
        values["period_grain"] = PeriodGrain(data["period_grain"])
        values["period_key"] = data["period_key"]
        values["rent"] = MarketCellRent.from_dict(data["rent"])
        values["source_support"] = SourceSupportSummary.from_dict(data["source_support"])
        if "admin_code" in data:
            values["admin_code"] = data["admin_code"]
        if "centroid_lat" in data:
            values["centroid_lat"] = data["centroid_lat"]
        if "centroid_lng" in data:
            values["centroid_lng"] = data["centroid_lng"]
        if "component_manifest_refs" in data:
            values["component_manifest_refs"] = [ProductComponentRef.from_dict(item) for item in data["component_manifest_refs"]]
        if "county" in data:
            values["county"] = data["county"]
        if "district" in data:
            values["district"] = data["district"]
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["cell_id"] = self.cell_id
        data["competitors"] = self.competitors.to_dict()
        data["coverage"] = self.coverage.to_dict()
        data["demographics"] = self.demographics.to_dict()
        data["h3_index"] = self.h3_index
        data["h3_resolution"] = self.h3_resolution
        data["mobility"] = self.mobility.to_dict()
        data["period_grain"] = self.period_grain.value
        data["period_key"] = self.period_key
        data["rent"] = self.rent.to_dict()
        data["source_support"] = self.source_support.to_dict()
        if self.admin_code is not None:
            data["admin_code"] = self.admin_code
        if self.centroid_lat is not None:
            data["centroid_lat"] = self.centroid_lat
        if self.centroid_lng is not None:
            data["centroid_lng"] = self.centroid_lng
        data["component_manifest_refs"] = [item.to_dict() for item in self.component_manifest_refs]
        if self.county is not None:
            data["county"] = self.county
        if self.district is not None:
            data["district"] = self.district
        data["metadata"] = self.metadata
        return data


@dataclass(frozen=True, slots=True)
class MarketCellProfileDocument:
    """Released contract model MarketCellProfileDocument."""

    cells: list[MarketCellProfile]
    generated_at: str
    h3_resolution: int
    period_grain: PeriodGrain
    period_key: str
    profile_id: str
    source_support: SourceSupportSummary
    component_manifest_refs: list[ProductComponentRef] = field(default_factory=list)
    contract_version: str = "emgi.market-cell-profile.v1"
    effective_as_of: str | None = None
    knowledge_as_of: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    product_version: str = "0.4.1"
    scope_principal_id: str | None = None
    tenant_id: str | None = "default"
    zones: list[MarketZoneProfile] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> MarketCellProfileDocument:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["cells"] = [MarketCellProfile.from_dict(item) for item in data["cells"]]
        values["generated_at"] = data["generated_at"]
        values["h3_resolution"] = data["h3_resolution"]
        values["period_grain"] = PeriodGrain(data["period_grain"])
        values["period_key"] = data["period_key"]
        values["profile_id"] = data["profile_id"]
        values["source_support"] = SourceSupportSummary.from_dict(data["source_support"])
        if "component_manifest_refs" in data:
            values["component_manifest_refs"] = [ProductComponentRef.from_dict(item) for item in data["component_manifest_refs"]]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "effective_as_of" in data:
            values["effective_as_of"] = data["effective_as_of"]
        if "knowledge_as_of" in data:
            values["knowledge_as_of"] = data["knowledge_as_of"]
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        if "product_version" in data:
            values["product_version"] = data["product_version"]
        if "scope_principal_id" in data:
            values["scope_principal_id"] = data["scope_principal_id"]
        if "tenant_id" in data:
            values["tenant_id"] = data["tenant_id"]
        if "zones" in data:
            values["zones"] = [MarketZoneProfile.from_dict(item) for item in data["zones"]]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["cells"] = [item.to_dict() for item in self.cells]
        data["generated_at"] = self.generated_at
        data["h3_resolution"] = self.h3_resolution
        data["period_grain"] = self.period_grain.value
        data["period_key"] = self.period_key
        data["profile_id"] = self.profile_id
        data["source_support"] = self.source_support.to_dict()
        data["component_manifest_refs"] = [item.to_dict() for item in self.component_manifest_refs]
        data["contract_version"] = self.contract_version
        if self.effective_as_of is not None:
            data["effective_as_of"] = self.effective_as_of
        if self.knowledge_as_of is not None:
            data["knowledge_as_of"] = self.knowledge_as_of
        data["metadata"] = self.metadata
        data["product_version"] = self.product_version
        if self.scope_principal_id is not None:
            data["scope_principal_id"] = self.scope_principal_id
        if self.tenant_id is not None:
            data["tenant_id"] = self.tenant_id
        data["zones"] = [item.to_dict() for item in self.zones]
        return data


@dataclass(frozen=True, slots=True)
class MarketCellProfileRelease:
    """Released contract model MarketCellProfileRelease."""

    component_manifest_refs: list[ProductComponentRef]
    document: MarketCellProfileDocument
    release_id: str
    released_at: str
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> MarketCellProfileRelease:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["component_manifest_refs"] = [ProductComponentRef.from_dict(item) for item in data["component_manifest_refs"]]
        values["document"] = MarketCellProfileDocument.from_dict(data["document"])
        values["release_id"] = data["release_id"]
        values["released_at"] = data["released_at"]
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["component_manifest_refs"] = [item.to_dict() for item in self.component_manifest_refs]
        data["document"] = self.document.to_dict()
        data["release_id"] = self.release_id
        data["released_at"] = self.released_at
        data["metadata"] = self.metadata
        return data


@dataclass(frozen=True, slots=True)
class MarketCellRent:
    """Released contract model MarketCellRent."""

    confidence_pct: float | None = None
    fallback_level: str | None = None
    mean_rent_per_ping: Any = None
    median_rent_per_ping: Any = None
    p25_rent_per_ping: Any = None
    p75_rent_per_ping: Any = None
    property_tier: str | None = None
    sample_count: int = 0
    source_support: SourceSupportSummary | None = None
    uncertainty_pct: float | None = None
    weighted_sample_count: Any = 0.0

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> MarketCellRent:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        if "confidence_pct" in data:
            values["confidence_pct"] = data["confidence_pct"]
        if "fallback_level" in data:
            values["fallback_level"] = data["fallback_level"]
        if "mean_rent_per_ping" in data:
            values["mean_rent_per_ping"] = data["mean_rent_per_ping"]
        if "median_rent_per_ping" in data:
            values["median_rent_per_ping"] = data["median_rent_per_ping"]
        if "p25_rent_per_ping" in data:
            values["p25_rent_per_ping"] = data["p25_rent_per_ping"]
        if "p75_rent_per_ping" in data:
            values["p75_rent_per_ping"] = data["p75_rent_per_ping"]
        if "property_tier" in data:
            values["property_tier"] = data["property_tier"]
        if "sample_count" in data:
            values["sample_count"] = data["sample_count"]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "uncertainty_pct" in data:
            values["uncertainty_pct"] = data["uncertainty_pct"]
        if "weighted_sample_count" in data:
            values["weighted_sample_count"] = data["weighted_sample_count"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        if self.confidence_pct is not None:
            data["confidence_pct"] = self.confidence_pct
        if self.fallback_level is not None:
            data["fallback_level"] = self.fallback_level
        if self.mean_rent_per_ping is not None:
            data["mean_rent_per_ping"] = self.mean_rent_per_ping
        if self.median_rent_per_ping is not None:
            data["median_rent_per_ping"] = self.median_rent_per_ping
        if self.p25_rent_per_ping is not None:
            data["p25_rent_per_ping"] = self.p25_rent_per_ping
        if self.p75_rent_per_ping is not None:
            data["p75_rent_per_ping"] = self.p75_rent_per_ping
        if self.property_tier is not None:
            data["property_tier"] = self.property_tier
        data["sample_count"] = self.sample_count
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        if self.uncertainty_pct is not None:
            data["uncertainty_pct"] = self.uncertainty_pct
        data["weighted_sample_count"] = self.weighted_sample_count
        return data


@dataclass(frozen=True, slots=True)
class MarketZoneProfile:
    """Released contract model MarketZoneProfile."""

    aggregated_competitors: MarketCellCompetitors
    aggregated_demographics: MarketCellDemographics
    aggregated_mobility: MarketCellMobility
    aggregated_rent: MarketCellRent
    h3_cells: list[str]
    h3_resolution: int
    period_grain: PeriodGrain
    period_key: str
    source_support: SourceSupportSummary
    total_cells_count: int
    zone_coverage: MarketCellCoverage
    zone_id: str
    zone_name: str
    admin_code: str | None = None
    component_manifest_refs: list[ProductComponentRef] = field(default_factory=list)
    county: str | None = None
    district: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> MarketZoneProfile:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["aggregated_competitors"] = MarketCellCompetitors.from_dict(data["aggregated_competitors"])
        values["aggregated_demographics"] = MarketCellDemographics.from_dict(data["aggregated_demographics"])
        values["aggregated_mobility"] = MarketCellMobility.from_dict(data["aggregated_mobility"])
        values["aggregated_rent"] = MarketCellRent.from_dict(data["aggregated_rent"])
        values["h3_cells"] = list(data["h3_cells"])
        values["h3_resolution"] = data["h3_resolution"]
        values["period_grain"] = PeriodGrain(data["period_grain"])
        values["period_key"] = data["period_key"]
        values["source_support"] = SourceSupportSummary.from_dict(data["source_support"])
        values["total_cells_count"] = data["total_cells_count"]
        values["zone_coverage"] = MarketCellCoverage.from_dict(data["zone_coverage"])
        values["zone_id"] = data["zone_id"]
        values["zone_name"] = data["zone_name"]
        if "admin_code" in data:
            values["admin_code"] = data["admin_code"]
        if "component_manifest_refs" in data:
            values["component_manifest_refs"] = [ProductComponentRef.from_dict(item) for item in data["component_manifest_refs"]]
        if "county" in data:
            values["county"] = data["county"]
        if "district" in data:
            values["district"] = data["district"]
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["aggregated_competitors"] = self.aggregated_competitors.to_dict()
        data["aggregated_demographics"] = self.aggregated_demographics.to_dict()
        data["aggregated_mobility"] = self.aggregated_mobility.to_dict()
        data["aggregated_rent"] = self.aggregated_rent.to_dict()
        data["h3_cells"] = list(self.h3_cells)
        data["h3_resolution"] = self.h3_resolution
        data["period_grain"] = self.period_grain.value
        data["period_key"] = self.period_key
        data["source_support"] = self.source_support.to_dict()
        data["total_cells_count"] = self.total_cells_count
        data["zone_coverage"] = self.zone_coverage.to_dict()
        data["zone_id"] = self.zone_id
        data["zone_name"] = self.zone_name
        if self.admin_code is not None:
            data["admin_code"] = self.admin_code
        data["component_manifest_refs"] = [item.to_dict() for item in self.component_manifest_refs]
        if self.county is not None:
            data["county"] = self.county
        if self.district is not None:
            data["district"] = self.district
        data["metadata"] = self.metadata
        return data


@dataclass(frozen=True, slots=True)
class ProductComponentRef:
    """Released contract model ProductComponentRef."""

    component_id: str
    component_kind: ProductComponentKind
    contract_id: str
    sha256: str
    feature_manifest_id: str | None = None
    row_count: int | None = None
    size_bytes: int | None = None
    source_manifest_id: str | None = None
    storage_uri: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> ProductComponentRef:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["component_id"] = data["component_id"]
        values["component_kind"] = ProductComponentKind(data["component_kind"])
        values["contract_id"] = data["contract_id"]
        values["sha256"] = data["sha256"]
        if "feature_manifest_id" in data:
            values["feature_manifest_id"] = data["feature_manifest_id"]
        if "row_count" in data:
            values["row_count"] = data["row_count"]
        if "size_bytes" in data:
            values["size_bytes"] = data["size_bytes"]
        if "source_manifest_id" in data:
            values["source_manifest_id"] = data["source_manifest_id"]
        if "storage_uri" in data:
            values["storage_uri"] = data["storage_uri"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["component_id"] = self.component_id
        data["component_kind"] = self.component_kind.value
        data["contract_id"] = self.contract_id
        data["sha256"] = self.sha256
        if self.feature_manifest_id is not None:
            data["feature_manifest_id"] = self.feature_manifest_id
        if self.row_count is not None:
            data["row_count"] = self.row_count
        if self.size_bytes is not None:
            data["size_bytes"] = self.size_bytes
        if self.source_manifest_id is not None:
            data["source_manifest_id"] = self.source_manifest_id
        if self.storage_uri is not None:
            data["storage_uri"] = self.storage_uri
        return data


@dataclass(frozen=True, slots=True)
class ReadinessReason:
    """Released contract model ReadinessReason."""

    code: str
    detail: str
    severity: ReasonSeverity
    cell_id: str | None = None
    domain: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> ReadinessReason:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["code"] = data["code"]
        values["detail"] = data["detail"]
        values["severity"] = ReasonSeverity(data["severity"])
        if "cell_id" in data:
            values["cell_id"] = data["cell_id"]
        if "domain" in data:
            values["domain"] = data["domain"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["code"] = self.code
        data["detail"] = self.detail
        data["severity"] = self.severity.value
        if self.cell_id is not None:
            data["cell_id"] = self.cell_id
        if self.domain is not None:
            data["domain"] = self.domain
        return data


@dataclass(frozen=True, slots=True)
class SourceSupportSummary:
    """Released contract model SourceSupportSummary."""

    observation_count: int
    sample_count: int
    first_observed_at: str | None = None
    last_observed_at: str | None = None
    source_dataset_ids: list[str] = field(default_factory=list)
    source_manifest_ids: list[str] = field(default_factory=list)
    uncertainty_pct: float | None = None
    weight_methods: list[str] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SourceSupportSummary:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["observation_count"] = data["observation_count"]
        values["sample_count"] = data["sample_count"]
        if "first_observed_at" in data:
            values["first_observed_at"] = data["first_observed_at"]
        if "last_observed_at" in data:
            values["last_observed_at"] = data["last_observed_at"]
        if "source_dataset_ids" in data:
            values["source_dataset_ids"] = list(data["source_dataset_ids"])
        if "source_manifest_ids" in data:
            values["source_manifest_ids"] = list(data["source_manifest_ids"])
        if "uncertainty_pct" in data:
            values["uncertainty_pct"] = data["uncertainty_pct"]
        if "weight_methods" in data:
            values["weight_methods"] = list(data["weight_methods"])
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["observation_count"] = self.observation_count
        data["sample_count"] = self.sample_count
        if self.first_observed_at is not None:
            data["first_observed_at"] = self.first_observed_at
        if self.last_observed_at is not None:
            data["last_observed_at"] = self.last_observed_at
        data["source_dataset_ids"] = list(self.source_dataset_ids)
        data["source_manifest_ids"] = list(self.source_manifest_ids)
        if self.uncertainty_pct is not None:
            data["uncertainty_pct"] = self.uncertainty_pct
        data["weight_methods"] = list(self.weight_methods)
        return data

