# Generated by packages/oday_data_product_contracts_client/codegen.py -- do not edit.
#
# Contract:  emgi.site-market-context.v1 (decision_product, v1.0.0)
# Release:   oday-data-product-contracts.v0.4.1
# Producer:  alfloop-dev/oday-data-platform@245aa00e417b6f8450baa608e8976584e00be6fc
# Schema:    schemas/site-market-context.schema.json
# Digest:    4b433cf747c0f89d423e42a2ba3bd53119e2af1cacc2b2e83045214aab5c0300
"""Canonical contract schemas for published componentized product-neutral site market context (emgi.site-market-context.v1) across identity, catchment, demand, POI, competitor, rent, listing, mobility, traffic, event, and coverage components in EMGI v0.4.1."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

CONTRACT_ID = "emgi.site-market-context.v1"
CONTRACT_VERSION = "1.0.0"
CONTRACT_CATEGORY = "decision_product"
SCHEMA_FILE = "schemas/site-market-context.schema.json"
SCHEMA_SHA256 = "4b433cf747c0f89d423e42a2ba3bd53119e2af1cacc2b2e83045214aab5c0300"
ROOT_MODEL = "SiteMarketContextDocument"


class CoverageState(StrEnum):
    """Coverage state of a specific domain for this site."""

    complete = "complete"
    partial = "partial"
    empty = "empty"
    missing = "missing"
    withheld = "withheld"
    quarantined = "quarantined"
    stale = "stale"
    degraded = "degraded"
    unobserved = "unobserved"


class DomainStatus(StrEnum):
    """Availability state of a specific domain aggregation."""

    available = "available"
    partial = "partial"
    unavailable = "unavailable"


class EventStatus(StrEnum):
    """Lifecycle status of a market event."""

    DRAFT = "DRAFT"
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"


class FreshnessState(StrEnum):
    """Freshness verdict relative to declared SLA."""

    fresh = "fresh"
    stale = "stale"
    unknown = "unknown"
    not_applicable = "not_applicable"


class MarketEventType(StrEnum):
    """Categorization of market events."""

    STORE_OPENING = "STORE_OPENING"
    STORE_CLOSURE = "STORE_CLOSURE"
    BRAND_ENTRY = "BRAND_ENTRY"
    TRANSPORT_INFRASTRUCTURE = "TRANSPORT_INFRASTRUCTURE"
    URBAN_REDEVELOPMENT = "URBAN_REDEVELOPMENT"
    COMMERCIAL_COMPLEX = "COMMERCIAL_COMPLEX"
    ZONING_CHANGE = "ZONING_CHANGE"
    DEMOGRAPHIC_SHIFT_ALERT = "DEMOGRAPHIC_SHIFT_ALERT"
    COMPETITOR_ACTION = "COMPETITOR_ACTION"
    MAJOR_EVENT_FESTIVAL = "MAJOR_EVENT_FESTIVAL"
    OTHER = "OTHER"


class MilestonePhase(StrEnum):
    """Milestone phase of a market event."""

    PLANNING = "PLANNING"
    DETAILED_DESIGN = "DETAILED_DESIGN"
    PERMITTING = "PERMITTING"
    CONSTRUCTION = "CONSTRUCTION"
    FIT_OUT = "FIT_OUT"
    TRIAL_OPERATION = "TRIAL_OPERATION"
    OPENED = "OPENED"
    OPERATING = "OPERATING"
    SUSPENDED = "SUSPENDED"
    CLOSED = "CLOSED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class PeriodGrain(StrEnum):
    """Temporal aggregation grain of the site market context."""

    HOURLY = "HOURLY"
    DAILY = "DAILY"
    WEEKDAY = "WEEKDAY"
    WEEKEND = "WEEKEND"
    PEAK_AM = "PEAK_AM"
    PEAK_PM = "PEAK_PM"
    OFF_PEAK = "OFF_PEAK"
    NIGHT = "NIGHT"
    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    ANNUAL = "ANNUAL"


class ProductComponentKind(StrEnum):
    """Component domain kind composing a published data product."""

    GEOGRAPHY = "GEOGRAPHY"
    DEMOGRAPHICS = "DEMOGRAPHICS"
    POI = "POI"
    COMPETITOR = "COMPETITOR"
    RENT = "RENT"
    TRANSPORT = "TRANSPORT"
    MOBILITY = "MOBILITY"
    EVENTS = "EVENTS"
    COVERAGE = "COVERAGE"
    ACQUISITION = "ACQUISITION"
    FEATURE_SET = "FEATURE_SET"
    MODEL_PREDICTION = "MODEL_PREDICTION"
    CUSTOM = "CUSTOM"


class ReadinessLevel(StrEnum):
    """Categorical readiness level for consuming this site context."""

    ready = "ready"
    usable_with_gaps = "usable_with_gaps"
    blocked = "blocked"
    unknown = "unknown"


class ReasonSeverity(StrEnum):
    """Severity of a readiness explanation reason."""

    blocking = "blocking"
    degrading = "degrading"
    informational = "informational"


class TravelMode(StrEnum):
    """Supported travel modes for catchment boundary generation."""

    car = "car"
    motorcycle = "motorcycle"
    pedestrian = "pedestrian"
    bicycle = "bicycle"
    transit = "transit"
    truck = "truck"


@dataclass(frozen=True, slots=True)
class ProductComponentRef:
    """Released contract model ProductComponentRef."""

    component_id: str
    component_kind: ProductComponentKind
    contract_id: str
    sha256: str
    feature_manifest_id: str | None = None
    row_count: int | None = None
    size_bytes: int | None = None
    source_manifest_id: str | None = None
    storage_uri: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> ProductComponentRef:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["component_id"] = data["component_id"]
        values["component_kind"] = ProductComponentKind(data["component_kind"])
        values["contract_id"] = data["contract_id"]
        values["sha256"] = data["sha256"]
        if "feature_manifest_id" in data:
            values["feature_manifest_id"] = data["feature_manifest_id"]
        if "row_count" in data:
            values["row_count"] = data["row_count"]
        if "size_bytes" in data:
            values["size_bytes"] = data["size_bytes"]
        if "source_manifest_id" in data:
            values["source_manifest_id"] = data["source_manifest_id"]
        if "storage_uri" in data:
            values["storage_uri"] = data["storage_uri"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["component_id"] = self.component_id
        data["component_kind"] = self.component_kind.value
        data["contract_id"] = self.contract_id
        data["sha256"] = self.sha256
        if self.feature_manifest_id is not None:
            data["feature_manifest_id"] = self.feature_manifest_id
        if self.row_count is not None:
            data["row_count"] = self.row_count
        if self.size_bytes is not None:
            data["size_bytes"] = self.size_bytes
        if self.source_manifest_id is not None:
            data["source_manifest_id"] = self.source_manifest_id
        if self.storage_uri is not None:
            data["storage_uri"] = self.storage_uri
        return data


@dataclass(frozen=True, slots=True)
class ReadinessReason:
    """Released contract model ReadinessReason."""

    code: str
    detail: str
    severity: ReasonSeverity
    cell_id: str | None = None
    domain: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> ReadinessReason:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["code"] = data["code"]
        values["detail"] = data["detail"]
        values["severity"] = ReasonSeverity(data["severity"])
        if "cell_id" in data:
            values["cell_id"] = data["cell_id"]
        if "domain" in data:
            values["domain"] = data["domain"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["code"] = self.code
        data["detail"] = self.detail
        data["severity"] = self.severity.value
        if self.cell_id is not None:
            data["cell_id"] = self.cell_id
        if self.domain is not None:
            data["domain"] = self.domain
        return data


@dataclass(frozen=True, slots=True)
class SiteCatchment:
    """Released contract model SiteCatchment."""

    catchment_id: str
    cutoff_seconds: int
    geom: dict[str, Any]
    graph_version: str
    routing_engine: str
    status: DomainStatus
    travel_mode: TravelMode
    area_sq_meters: float | None = None
    estimation_status: str = "exact"
    h3_cells: list[str] = field(default_factory=list)
    h3_resolution: int = 9
    is_scooter_estimated: bool = False
    isochrone_cutoff_minutes: float = 0.0
    quality_flags: list[str] = field(default_factory=list)
    source_support: SourceSupportSummary | None = None
    total_cells_count: int = 0
    unavailable_reason: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SiteCatchment:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["catchment_id"] = data["catchment_id"]
        values["cutoff_seconds"] = data["cutoff_seconds"]
        values["geom"] = data["geom"]
        values["graph_version"] = data["graph_version"]
        values["routing_engine"] = data["routing_engine"]
        values["status"] = DomainStatus(data["status"])
        values["travel_mode"] = TravelMode(data["travel_mode"])
        if "area_sq_meters" in data:
            values["area_sq_meters"] = data["area_sq_meters"]
        if "estimation_status" in data:
            values["estimation_status"] = data["estimation_status"]
        if "h3_cells" in data:
            values["h3_cells"] = list(data["h3_cells"])
        if "h3_resolution" in data:
            values["h3_resolution"] = data["h3_resolution"]
        if "is_scooter_estimated" in data:
            values["is_scooter_estimated"] = data["is_scooter_estimated"]
        if "isochrone_cutoff_minutes" in data:
            values["isochrone_cutoff_minutes"] = data["isochrone_cutoff_minutes"]
        if "quality_flags" in data:
            values["quality_flags"] = list(data["quality_flags"])
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "total_cells_count" in data:
            values["total_cells_count"] = data["total_cells_count"]
        if "unavailable_reason" in data:
            values["unavailable_reason"] = data["unavailable_reason"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["catchment_id"] = self.catchment_id
        data["cutoff_seconds"] = self.cutoff_seconds
        data["geom"] = self.geom
        data["graph_version"] = self.graph_version
        data["routing_engine"] = self.routing_engine
        data["status"] = self.status.value
        data["travel_mode"] = self.travel_mode.value
        if self.area_sq_meters is not None:
            data["area_sq_meters"] = self.area_sq_meters
        data["estimation_status"] = self.estimation_status
        data["h3_cells"] = list(self.h3_cells)
        data["h3_resolution"] = self.h3_resolution
        data["is_scooter_estimated"] = self.is_scooter_estimated
        data["isochrone_cutoff_minutes"] = self.isochrone_cutoff_minutes
        data["quality_flags"] = list(self.quality_flags)
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        data["total_cells_count"] = self.total_cells_count
        if self.unavailable_reason is not None:
            data["unavailable_reason"] = self.unavailable_reason
        return data


@dataclass(frozen=True, slots=True)
class SiteCompetitor:
    """Released contract model SiteCompetitor."""

    status: DomainStatus
    active_competitors: int | None = None
    average_capacity: float | None = None
    brands_present: list[str] = field(default_factory=list)
    capacity_sample_count: int = 0
    competitor_density_per_sq_km: float | None = None
    price_tier_distribution: dict[str, Any] | None = None
    source_support: SourceSupportSummary | None = None
    stores_by_brand: dict[str, Any] = field(default_factory=dict)
    stores_by_category: dict[str, Any] = field(default_factory=dict)
    total_capacity: float | None = None
    total_competitors: int | None = None
    unavailable_reason: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SiteCompetitor:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["status"] = DomainStatus(data["status"])
        if "active_competitors" in data:
            values["active_competitors"] = data["active_competitors"]
        if "average_capacity" in data:
            values["average_capacity"] = data["average_capacity"]
        if "brands_present" in data:
            values["brands_present"] = list(data["brands_present"])
        if "capacity_sample_count" in data:
            values["capacity_sample_count"] = data["capacity_sample_count"]
        if "competitor_density_per_sq_km" in data:
            values["competitor_density_per_sq_km"] = data["competitor_density_per_sq_km"]
        if "price_tier_distribution" in data:
            values["price_tier_distribution"] = data["price_tier_distribution"]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "stores_by_brand" in data:
            values["stores_by_brand"] = data["stores_by_brand"]
        if "stores_by_category" in data:
            values["stores_by_category"] = data["stores_by_category"]
        if "total_capacity" in data:
            values["total_capacity"] = data["total_capacity"]
        if "total_competitors" in data:
            values["total_competitors"] = data["total_competitors"]
        if "unavailable_reason" in data:
            values["unavailable_reason"] = data["unavailable_reason"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["status"] = self.status.value
        if self.active_competitors is not None:
            data["active_competitors"] = self.active_competitors
        if self.average_capacity is not None:
            data["average_capacity"] = self.average_capacity
        data["brands_present"] = list(self.brands_present)
        data["capacity_sample_count"] = self.capacity_sample_count
        if self.competitor_density_per_sq_km is not None:
            data["competitor_density_per_sq_km"] = self.competitor_density_per_sq_km
        if self.price_tier_distribution is not None:
            data["price_tier_distribution"] = self.price_tier_distribution
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        data["stores_by_brand"] = self.stores_by_brand
        data["stores_by_category"] = self.stores_by_category
        if self.total_capacity is not None:
            data["total_capacity"] = self.total_capacity
        if self.total_competitors is not None:
            data["total_competitors"] = self.total_competitors
        if self.unavailable_reason is not None:
            data["unavailable_reason"] = self.unavailable_reason
        return data


@dataclass(frozen=True, slots=True)
class SiteCoverage:
    """Released contract model SiteCoverage."""

    domain_coverage: dict[str, Any]
    overall_readiness: ReadinessLevel
    blocked_domains: list[str] = field(default_factory=list)
    domain_freshness: dict[str, Any] = field(default_factory=dict)
    has_gaps: bool = False
    readiness_reasons: list[ReadinessReason] = field(default_factory=list)
    source_support: SourceSupportSummary | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SiteCoverage:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["domain_coverage"] = data["domain_coverage"]
        values["overall_readiness"] = ReadinessLevel(data["overall_readiness"])
        if "blocked_domains" in data:
            values["blocked_domains"] = list(data["blocked_domains"])
        if "domain_freshness" in data:
            values["domain_freshness"] = data["domain_freshness"]
        if "has_gaps" in data:
            values["has_gaps"] = data["has_gaps"]
        if "readiness_reasons" in data:
            values["readiness_reasons"] = [ReadinessReason.from_dict(item) for item in data["readiness_reasons"]]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["domain_coverage"] = self.domain_coverage
        data["overall_readiness"] = self.overall_readiness.value
        data["blocked_domains"] = list(self.blocked_domains)
        data["domain_freshness"] = self.domain_freshness
        data["has_gaps"] = self.has_gaps
        data["readiness_reasons"] = [item.to_dict() for item in self.readiness_reasons]
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        return data


@dataclass(frozen=True, slots=True)
class SiteDemand:
    """Released contract model SiteDemand."""

    status: DomainStatus
    age_distribution: dict[str, Any] | None = None
    daytime_population_ratio: float | None = None
    density_per_sq_km: float | None = None
    female_population: float | None = None
    household_count: float | None = None
    male_population: float | None = None
    source_support: SourceSupportSummary | None = None
    total_population: float | None = None
    unavailable_reason: str | None = None
    uncertainty_pct: float | None = None
    weight_methods: list[str] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SiteDemand:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["status"] = DomainStatus(data["status"])
        if "age_distribution" in data:
            values["age_distribution"] = data["age_distribution"]
        if "daytime_population_ratio" in data:
            values["daytime_population_ratio"] = data["daytime_population_ratio"]
        if "density_per_sq_km" in data:
            values["density_per_sq_km"] = data["density_per_sq_km"]
        if "female_population" in data:
            values["female_population"] = data["female_population"]
        if "household_count" in data:
            values["household_count"] = data["household_count"]
        if "male_population" in data:
            values["male_population"] = data["male_population"]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "total_population" in data:
            values["total_population"] = data["total_population"]
        if "unavailable_reason" in data:
            values["unavailable_reason"] = data["unavailable_reason"]
        if "uncertainty_pct" in data:
            values["uncertainty_pct"] = data["uncertainty_pct"]
        if "weight_methods" in data:
            values["weight_methods"] = list(data["weight_methods"])
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["status"] = self.status.value
        if self.age_distribution is not None:
            data["age_distribution"] = self.age_distribution
        if self.daytime_population_ratio is not None:
            data["daytime_population_ratio"] = self.daytime_population_ratio
        if self.density_per_sq_km is not None:
            data["density_per_sq_km"] = self.density_per_sq_km
        if self.female_population is not None:
            data["female_population"] = self.female_population
        if self.household_count is not None:
            data["household_count"] = self.household_count
        if self.male_population is not None:
            data["male_population"] = self.male_population
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        if self.total_population is not None:
            data["total_population"] = self.total_population
        if self.unavailable_reason is not None:
            data["unavailable_reason"] = self.unavailable_reason
        if self.uncertainty_pct is not None:
            data["uncertainty_pct"] = self.uncertainty_pct
        data["weight_methods"] = list(self.weight_methods)
        return data


@dataclass(frozen=True, slots=True)
class SiteEvent:
    """Released contract model SiteEvent."""

    status: DomainStatus
    active_events_count: int | None = None
    events: list[SiteMarketEventSummary] = field(default_factory=list)
    events_by_type: dict[str, Any] = field(default_factory=dict)
    source_support: SourceSupportSummary | None = None
    unavailable_reason: str | None = None
    upcoming_events_count: int | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SiteEvent:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["status"] = DomainStatus(data["status"])
        if "active_events_count" in data:
            values["active_events_count"] = data["active_events_count"]
        if "events" in data:
            values["events"] = [SiteMarketEventSummary.from_dict(item) for item in data["events"]]
        if "events_by_type" in data:
            values["events_by_type"] = data["events_by_type"]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "unavailable_reason" in data:
            values["unavailable_reason"] = data["unavailable_reason"]
        if "upcoming_events_count" in data:
            values["upcoming_events_count"] = data["upcoming_events_count"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["status"] = self.status.value
        if self.active_events_count is not None:
            data["active_events_count"] = self.active_events_count
        data["events"] = [item.to_dict() for item in self.events]
        data["events_by_type"] = self.events_by_type
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        if self.unavailable_reason is not None:
            data["unavailable_reason"] = self.unavailable_reason
        if self.upcoming_events_count is not None:
            data["upcoming_events_count"] = self.upcoming_events_count
        return data


@dataclass(frozen=True, slots=True)
class SiteIdentity:
    """Released contract model SiteIdentity."""

    h3_resolution: int
    latitude: float
    longitude: float
    primary_h3_index: str
    site_id: str
    address: str | None = None
    admin_code: str | None = None
    county: str | None = None
    district: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    property_type: str | None = None
    site_name: str | None = None
    site_type: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SiteIdentity:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["h3_resolution"] = data["h3_resolution"]
        values["latitude"] = data["latitude"]
        values["longitude"] = data["longitude"]
        values["primary_h3_index"] = data["primary_h3_index"]
        values["site_id"] = data["site_id"]
        if "address" in data:
            values["address"] = data["address"]
        if "admin_code" in data:
            values["admin_code"] = data["admin_code"]
        if "county" in data:
            values["county"] = data["county"]
        if "district" in data:
            values["district"] = data["district"]
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        if "property_type" in data:
            values["property_type"] = data["property_type"]
        if "site_name" in data:
            values["site_name"] = data["site_name"]
        if "site_type" in data:
            values["site_type"] = data["site_type"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["h3_resolution"] = self.h3_resolution
        data["latitude"] = self.latitude
        data["longitude"] = self.longitude
        data["primary_h3_index"] = self.primary_h3_index
        data["site_id"] = self.site_id
        if self.address is not None:
            data["address"] = self.address
        if self.admin_code is not None:
            data["admin_code"] = self.admin_code
        if self.county is not None:
            data["county"] = self.county
        if self.district is not None:
            data["district"] = self.district
        data["metadata"] = self.metadata
        if self.property_type is not None:
            data["property_type"] = self.property_type
        if self.site_name is not None:
            data["site_name"] = self.site_name
        if self.site_type is not None:
            data["site_type"] = self.site_type
        return data


@dataclass(frozen=True, slots=True)
class SiteListing:
    """Released contract model SiteListing."""

    status: DomainStatus
    active_listings_count: int | None = None
    average_area_ping: float | None = None
    listings_by_property_type: dict[str, Any] = field(default_factory=dict)
    mean_asking_rent_per_ping: float | None = None
    median_asking_rent_per_ping: float | None = None
    median_days_on_market: float | None = None
    p25_asking_rent_per_ping: float | None = None
    p75_asking_rent_per_ping: float | None = None
    source_support: SourceSupportSummary | None = None
    unavailable_reason: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SiteListing:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["status"] = DomainStatus(data["status"])
        if "active_listings_count" in data:
            values["active_listings_count"] = data["active_listings_count"]
        if "average_area_ping" in data:
            values["average_area_ping"] = data["average_area_ping"]
        if "listings_by_property_type" in data:
            values["listings_by_property_type"] = data["listings_by_property_type"]
        if "mean_asking_rent_per_ping" in data:
            values["mean_asking_rent_per_ping"] = data["mean_asking_rent_per_ping"]
        if "median_asking_rent_per_ping" in data:
            values["median_asking_rent_per_ping"] = data["median_asking_rent_per_ping"]
        if "median_days_on_market" in data:
            values["median_days_on_market"] = data["median_days_on_market"]
        if "p25_asking_rent_per_ping" in data:
            values["p25_asking_rent_per_ping"] = data["p25_asking_rent_per_ping"]
        if "p75_asking_rent_per_ping" in data:
            values["p75_asking_rent_per_ping"] = data["p75_asking_rent_per_ping"]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "unavailable_reason" in data:
            values["unavailable_reason"] = data["unavailable_reason"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["status"] = self.status.value
        if self.active_listings_count is not None:
            data["active_listings_count"] = self.active_listings_count
        if self.average_area_ping is not None:
            data["average_area_ping"] = self.average_area_ping
        data["listings_by_property_type"] = self.listings_by_property_type
        if self.mean_asking_rent_per_ping is not None:
            data["mean_asking_rent_per_ping"] = self.mean_asking_rent_per_ping
        if self.median_asking_rent_per_ping is not None:
            data["median_asking_rent_per_ping"] = self.median_asking_rent_per_ping
        if self.median_days_on_market is not None:
            data["median_days_on_market"] = self.median_days_on_market
        if self.p25_asking_rent_per_ping is not None:
            data["p25_asking_rent_per_ping"] = self.p25_asking_rent_per_ping
        if self.p75_asking_rent_per_ping is not None:
            data["p75_asking_rent_per_ping"] = self.p75_asking_rent_per_ping
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        if self.unavailable_reason is not None:
            data["unavailable_reason"] = self.unavailable_reason
        return data


@dataclass(frozen=True, slots=True)
class SiteMarketContext:
    """Released contract model SiteMarketContext."""

    catchment: SiteCatchment
    competitor: SiteCompetitor
    context_id: str
    coverage: SiteCoverage
    demand: SiteDemand
    event: SiteEvent
    identity: SiteIdentity
    listing: SiteListing
    mobility: SiteMobility
    period_grain: PeriodGrain
    period_key: str
    poi: SitePOI
    rent: SiteRent
    source_support: SourceSupportSummary
    traffic: SiteTraffic
    component_manifest_refs: list[ProductComponentRef] = field(default_factory=list)
    effective_as_of: str | None = None
    knowledge_as_of: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SiteMarketContext:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["catchment"] = SiteCatchment.from_dict(data["catchment"])
        values["competitor"] = SiteCompetitor.from_dict(data["competitor"])
        values["context_id"] = data["context_id"]
        values["coverage"] = SiteCoverage.from_dict(data["coverage"])
        values["demand"] = SiteDemand.from_dict(data["demand"])
        values["event"] = SiteEvent.from_dict(data["event"])
        values["identity"] = SiteIdentity.from_dict(data["identity"])
        values["listing"] = SiteListing.from_dict(data["listing"])
        values["mobility"] = SiteMobility.from_dict(data["mobility"])
        values["period_grain"] = PeriodGrain(data["period_grain"])
        values["period_key"] = data["period_key"]
        values["poi"] = SitePOI.from_dict(data["poi"])
        values["rent"] = SiteRent.from_dict(data["rent"])
        values["source_support"] = SourceSupportSummary.from_dict(data["source_support"])
        values["traffic"] = SiteTraffic.from_dict(data["traffic"])
        if "component_manifest_refs" in data:
            values["component_manifest_refs"] = [ProductComponentRef.from_dict(item) for item in data["component_manifest_refs"]]
        if "effective_as_of" in data:
            values["effective_as_of"] = data["effective_as_of"]
        if "knowledge_as_of" in data:
            values["knowledge_as_of"] = data["knowledge_as_of"]
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["catchment"] = self.catchment.to_dict()
        data["competitor"] = self.competitor.to_dict()
        data["context_id"] = self.context_id
        data["coverage"] = self.coverage.to_dict()
        data["demand"] = self.demand.to_dict()
        data["event"] = self.event.to_dict()
        data["identity"] = self.identity.to_dict()
        data["listing"] = self.listing.to_dict()
        data["mobility"] = self.mobility.to_dict()
        data["period_grain"] = self.period_grain.value
        data["period_key"] = self.period_key
        data["poi"] = self.poi.to_dict()
        data["rent"] = self.rent.to_dict()
        data["source_support"] = self.source_support.to_dict()
        data["traffic"] = self.traffic.to_dict()
        data["component_manifest_refs"] = [item.to_dict() for item in self.component_manifest_refs]
        if self.effective_as_of is not None:
            data["effective_as_of"] = self.effective_as_of
        if self.knowledge_as_of is not None:
            data["knowledge_as_of"] = self.knowledge_as_of
        data["metadata"] = self.metadata
        return data


@dataclass(frozen=True, slots=True)
class SiteMarketContextDocument:
    """Released contract model SiteMarketContextDocument."""

    contexts: list[SiteMarketContext]
    document_id: str
    generated_at: str
    period_grain: PeriodGrain
    period_key: str
    source_support: SourceSupportSummary
    component_manifest_refs: list[ProductComponentRef] = field(default_factory=list)
    contract_version: str = "emgi.site-market-context.v1"
    effective_as_of: str | None = None
    knowledge_as_of: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    product_version: str = "0.4.1"
    scope_principal_id: str | None = None
    tenant_id: str | None = "default"

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SiteMarketContextDocument:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["contexts"] = [SiteMarketContext.from_dict(item) for item in data["contexts"]]
        values["document_id"] = data["document_id"]
        values["generated_at"] = data["generated_at"]
        values["period_grain"] = PeriodGrain(data["period_grain"])
        values["period_key"] = data["period_key"]
        values["source_support"] = SourceSupportSummary.from_dict(data["source_support"])
        if "component_manifest_refs" in data:
            values["component_manifest_refs"] = [ProductComponentRef.from_dict(item) for item in data["component_manifest_refs"]]
        if "contract_version" in data:
            values["contract_version"] = data["contract_version"]
        if "effective_as_of" in data:
            values["effective_as_of"] = data["effective_as_of"]
        if "knowledge_as_of" in data:
            values["knowledge_as_of"] = data["knowledge_as_of"]
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        if "product_version" in data:
            values["product_version"] = data["product_version"]
        if "scope_principal_id" in data:
            values["scope_principal_id"] = data["scope_principal_id"]
        if "tenant_id" in data:
            values["tenant_id"] = data["tenant_id"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["contexts"] = [item.to_dict() for item in self.contexts]
        data["document_id"] = self.document_id
        data["generated_at"] = self.generated_at
        data["period_grain"] = self.period_grain.value
        data["period_key"] = self.period_key
        data["source_support"] = self.source_support.to_dict()
        data["component_manifest_refs"] = [item.to_dict() for item in self.component_manifest_refs]
        data["contract_version"] = self.contract_version
        if self.effective_as_of is not None:
            data["effective_as_of"] = self.effective_as_of
        if self.knowledge_as_of is not None:
            data["knowledge_as_of"] = self.knowledge_as_of
        data["metadata"] = self.metadata
        data["product_version"] = self.product_version
        if self.scope_principal_id is not None:
            data["scope_principal_id"] = self.scope_principal_id
        if self.tenant_id is not None:
            data["tenant_id"] = self.tenant_id
        return data


@dataclass(frozen=True, slots=True)
class SiteMarketContextRelease:
    """Released contract model SiteMarketContextRelease."""

    component_manifest_refs: list[ProductComponentRef]
    document: SiteMarketContextDocument
    release_id: str
    released_at: str
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SiteMarketContextRelease:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["component_manifest_refs"] = [ProductComponentRef.from_dict(item) for item in data["component_manifest_refs"]]
        values["document"] = SiteMarketContextDocument.from_dict(data["document"])
        values["release_id"] = data["release_id"]
        values["released_at"] = data["released_at"]
        if "metadata" in data:
            values["metadata"] = data["metadata"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["component_manifest_refs"] = [item.to_dict() for item in self.component_manifest_refs]
        data["document"] = self.document.to_dict()
        data["release_id"] = self.release_id
        data["released_at"] = self.released_at
        data["metadata"] = self.metadata
        return data


@dataclass(frozen=True, slots=True)
class SiteMarketEventSummary:
    """Released contract model SiteMarketEventSummary."""

    event_id: str
    event_type: MarketEventType
    start_date: str
    status: EventStatus
    title: str
    affected_h3: list[str] = field(default_factory=list)
    confidence: float = 0.9
    current_milestone_phase: MilestonePhase | None = None
    distance_meters: float | None = None
    end_date: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SiteMarketEventSummary:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["event_id"] = data["event_id"]
        values["event_type"] = MarketEventType(data["event_type"])
        values["start_date"] = data["start_date"]
        values["status"] = EventStatus(data["status"])
        values["title"] = data["title"]
        if "affected_h3" in data:
            values["affected_h3"] = list(data["affected_h3"])
        if "confidence" in data:
            values["confidence"] = data["confidence"]
        if "current_milestone_phase" in data:
            values["current_milestone_phase"] = None if data["current_milestone_phase"] is None else MilestonePhase(data["current_milestone_phase"])
        if "distance_meters" in data:
            values["distance_meters"] = data["distance_meters"]
        if "end_date" in data:
            values["end_date"] = data["end_date"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["event_id"] = self.event_id
        data["event_type"] = self.event_type.value
        data["start_date"] = self.start_date
        data["status"] = self.status.value
        data["title"] = self.title
        data["affected_h3"] = list(self.affected_h3)
        data["confidence"] = self.confidence
        if self.current_milestone_phase is not None:
            data["current_milestone_phase"] = self.current_milestone_phase.value
        if self.distance_meters is not None:
            data["distance_meters"] = self.distance_meters
        if self.end_date is not None:
            data["end_date"] = self.end_date
        return data


@dataclass(frozen=True, slots=True)
class SiteMobility:
    """Released contract model SiteMobility."""

    status: DomainStatus
    activity_population: float | None = None
    dominant_archetype: str | None = None
    dwell_time_minutes: float | None = None
    hourly_distribution: dict[str, Any] | None = None
    is_calibrated: bool = False
    resident_population: float | None = None
    source_support: SourceSupportSummary | None = None
    unavailable_reason: str | None = None
    uncertainty_pct: float | None = None
    visitor_population: float | None = None
    worker_population: float | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SiteMobility:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["status"] = DomainStatus(data["status"])
        if "activity_population" in data:
            values["activity_population"] = data["activity_population"]
        if "dominant_archetype" in data:
            values["dominant_archetype"] = data["dominant_archetype"]
        if "dwell_time_minutes" in data:
            values["dwell_time_minutes"] = data["dwell_time_minutes"]
        if "hourly_distribution" in data:
            values["hourly_distribution"] = data["hourly_distribution"]
        if "is_calibrated" in data:
            values["is_calibrated"] = data["is_calibrated"]
        if "resident_population" in data:
            values["resident_population"] = data["resident_population"]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "unavailable_reason" in data:
            values["unavailable_reason"] = data["unavailable_reason"]
        if "uncertainty_pct" in data:
            values["uncertainty_pct"] = data["uncertainty_pct"]
        if "visitor_population" in data:
            values["visitor_population"] = data["visitor_population"]
        if "worker_population" in data:
            values["worker_population"] = data["worker_population"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["status"] = self.status.value
        if self.activity_population is not None:
            data["activity_population"] = self.activity_population
        if self.dominant_archetype is not None:
            data["dominant_archetype"] = self.dominant_archetype
        if self.dwell_time_minutes is not None:
            data["dwell_time_minutes"] = self.dwell_time_minutes
        if self.hourly_distribution is not None:
            data["hourly_distribution"] = self.hourly_distribution
        data["is_calibrated"] = self.is_calibrated
        if self.resident_population is not None:
            data["resident_population"] = self.resident_population
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        if self.unavailable_reason is not None:
            data["unavailable_reason"] = self.unavailable_reason
        if self.uncertainty_pct is not None:
            data["uncertainty_pct"] = self.uncertainty_pct
        if self.visitor_population is not None:
            data["visitor_population"] = self.visitor_population
        if self.worker_population is not None:
            data["worker_population"] = self.worker_population
        return data


@dataclass(frozen=True, slots=True)
class SitePOI:
    """Released contract model SitePOI."""

    status: DomainStatus
    commercial_centers_count: int = 0
    convenience_stores_count: int = 0
    density_per_sq_km: float | None = None
    hospitals_count: int = 0
    poi_by_category: dict[str, Any] = field(default_factory=dict)
    restaurants_count: int = 0
    schools_count: int = 0
    source_support: SourceSupportSummary | None = None
    total_poi_count: int | None = None
    transit_stations_count: int = 0
    unavailable_reason: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SitePOI:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["status"] = DomainStatus(data["status"])
        if "commercial_centers_count" in data:
            values["commercial_centers_count"] = data["commercial_centers_count"]
        if "convenience_stores_count" in data:
            values["convenience_stores_count"] = data["convenience_stores_count"]
        if "density_per_sq_km" in data:
            values["density_per_sq_km"] = data["density_per_sq_km"]
        if "hospitals_count" in data:
            values["hospitals_count"] = data["hospitals_count"]
        if "poi_by_category" in data:
            values["poi_by_category"] = data["poi_by_category"]
        if "restaurants_count" in data:
            values["restaurants_count"] = data["restaurants_count"]
        if "schools_count" in data:
            values["schools_count"] = data["schools_count"]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "total_poi_count" in data:
            values["total_poi_count"] = data["total_poi_count"]
        if "transit_stations_count" in data:
            values["transit_stations_count"] = data["transit_stations_count"]
        if "unavailable_reason" in data:
            values["unavailable_reason"] = data["unavailable_reason"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["status"] = self.status.value
        data["commercial_centers_count"] = self.commercial_centers_count
        data["convenience_stores_count"] = self.convenience_stores_count
        if self.density_per_sq_km is not None:
            data["density_per_sq_km"] = self.density_per_sq_km
        data["hospitals_count"] = self.hospitals_count
        data["poi_by_category"] = self.poi_by_category
        data["restaurants_count"] = self.restaurants_count
        data["schools_count"] = self.schools_count
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        if self.total_poi_count is not None:
            data["total_poi_count"] = self.total_poi_count
        data["transit_stations_count"] = self.transit_stations_count
        if self.unavailable_reason is not None:
            data["unavailable_reason"] = self.unavailable_reason
        return data


@dataclass(frozen=True, slots=True)
class SiteRent:
    """Released contract model SiteRent."""

    status: DomainStatus
    confidence_pct: float | None = None
    fallback_level: str | None = None
    mean_rent_per_ping: float | None = None
    median_rent_per_ping: float | None = None
    p25_rent_per_ping: float | None = None
    p75_rent_per_ping: float | None = None
    property_tier: str | None = None
    sample_count: int = 0
    source_support: SourceSupportSummary | None = None
    unavailable_reason: str | None = None
    uncertainty_pct: float | None = None
    weighted_sample_count: float | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SiteRent:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["status"] = DomainStatus(data["status"])
        if "confidence_pct" in data:
            values["confidence_pct"] = data["confidence_pct"]
        if "fallback_level" in data:
            values["fallback_level"] = data["fallback_level"]
        if "mean_rent_per_ping" in data:
            values["mean_rent_per_ping"] = data["mean_rent_per_ping"]
        if "median_rent_per_ping" in data:
            values["median_rent_per_ping"] = data["median_rent_per_ping"]
        if "p25_rent_per_ping" in data:
            values["p25_rent_per_ping"] = data["p25_rent_per_ping"]
        if "p75_rent_per_ping" in data:
            values["p75_rent_per_ping"] = data["p75_rent_per_ping"]
        if "property_tier" in data:
            values["property_tier"] = data["property_tier"]
        if "sample_count" in data:
            values["sample_count"] = data["sample_count"]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "unavailable_reason" in data:
            values["unavailable_reason"] = data["unavailable_reason"]
        if "uncertainty_pct" in data:
            values["uncertainty_pct"] = data["uncertainty_pct"]
        if "weighted_sample_count" in data:
            values["weighted_sample_count"] = data["weighted_sample_count"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["status"] = self.status.value
        if self.confidence_pct is not None:
            data["confidence_pct"] = self.confidence_pct
        if self.fallback_level is not None:
            data["fallback_level"] = self.fallback_level
        if self.mean_rent_per_ping is not None:
            data["mean_rent_per_ping"] = self.mean_rent_per_ping
        if self.median_rent_per_ping is not None:
            data["median_rent_per_ping"] = self.median_rent_per_ping
        if self.p25_rent_per_ping is not None:
            data["p25_rent_per_ping"] = self.p25_rent_per_ping
        if self.p75_rent_per_ping is not None:
            data["p75_rent_per_ping"] = self.p75_rent_per_ping
        if self.property_tier is not None:
            data["property_tier"] = self.property_tier
        data["sample_count"] = self.sample_count
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        if self.unavailable_reason is not None:
            data["unavailable_reason"] = self.unavailable_reason
        if self.uncertainty_pct is not None:
            data["uncertainty_pct"] = self.uncertainty_pct
        if self.weighted_sample_count is not None:
            data["weighted_sample_count"] = self.weighted_sample_count
        return data


@dataclass(frozen=True, slots=True)
class SiteTraffic:
    """Released contract model SiteTraffic."""

    status: DomainStatus
    hourly_volume_vph: int | None = None
    level_of_service: str | None = None
    mean_speed_kph: float | None = None
    motorcycle_hourly_volume: int | None = None
    motorcycle_ratio: float | None = None
    parking_facilities_count: int | None = None
    scooter_density_level: str | None = None
    source_support: SourceSupportSummary | None = None
    speed_ratio: float | None = None
    total_parking_spaces: int | None = None
    transit_daily_boardings: int | None = None
    transit_lines_count: int | None = None
    transit_stops_count: int | None = None
    unavailable_reason: str | None = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SiteTraffic:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["status"] = DomainStatus(data["status"])
        if "hourly_volume_vph" in data:
            values["hourly_volume_vph"] = data["hourly_volume_vph"]
        if "level_of_service" in data:
            values["level_of_service"] = data["level_of_service"]
        if "mean_speed_kph" in data:
            values["mean_speed_kph"] = data["mean_speed_kph"]
        if "motorcycle_hourly_volume" in data:
            values["motorcycle_hourly_volume"] = data["motorcycle_hourly_volume"]
        if "motorcycle_ratio" in data:
            values["motorcycle_ratio"] = data["motorcycle_ratio"]
        if "parking_facilities_count" in data:
            values["parking_facilities_count"] = data["parking_facilities_count"]
        if "scooter_density_level" in data:
            values["scooter_density_level"] = data["scooter_density_level"]
        if "source_support" in data:
            values["source_support"] = None if data["source_support"] is None else SourceSupportSummary.from_dict(data["source_support"])
        if "speed_ratio" in data:
            values["speed_ratio"] = data["speed_ratio"]
        if "total_parking_spaces" in data:
            values["total_parking_spaces"] = data["total_parking_spaces"]
        if "transit_daily_boardings" in data:
            values["transit_daily_boardings"] = data["transit_daily_boardings"]
        if "transit_lines_count" in data:
            values["transit_lines_count"] = data["transit_lines_count"]
        if "transit_stops_count" in data:
            values["transit_stops_count"] = data["transit_stops_count"]
        if "unavailable_reason" in data:
            values["unavailable_reason"] = data["unavailable_reason"]
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["status"] = self.status.value
        if self.hourly_volume_vph is not None:
            data["hourly_volume_vph"] = self.hourly_volume_vph
        if self.level_of_service is not None:
            data["level_of_service"] = self.level_of_service
        if self.mean_speed_kph is not None:
            data["mean_speed_kph"] = self.mean_speed_kph
        if self.motorcycle_hourly_volume is not None:
            data["motorcycle_hourly_volume"] = self.motorcycle_hourly_volume
        if self.motorcycle_ratio is not None:
            data["motorcycle_ratio"] = self.motorcycle_ratio
        if self.parking_facilities_count is not None:
            data["parking_facilities_count"] = self.parking_facilities_count
        if self.scooter_density_level is not None:
            data["scooter_density_level"] = self.scooter_density_level
        if self.source_support is not None:
            data["source_support"] = self.source_support.to_dict()
        if self.speed_ratio is not None:
            data["speed_ratio"] = self.speed_ratio
        if self.total_parking_spaces is not None:
            data["total_parking_spaces"] = self.total_parking_spaces
        if self.transit_daily_boardings is not None:
            data["transit_daily_boardings"] = self.transit_daily_boardings
        if self.transit_lines_count is not None:
            data["transit_lines_count"] = self.transit_lines_count
        if self.transit_stops_count is not None:
            data["transit_stops_count"] = self.transit_stops_count
        if self.unavailable_reason is not None:
            data["unavailable_reason"] = self.unavailable_reason
        return data


@dataclass(frozen=True, slots=True)
class SourceSupportSummary:
    """Released contract model SourceSupportSummary."""

    observation_count: int
    sample_count: int
    first_observed_at: str | None = None
    last_observed_at: str | None = None
    source_dataset_ids: list[str] = field(default_factory=list)
    source_manifest_ids: list[str] = field(default_factory=list)
    uncertainty_pct: float | None = None
    weight_methods: list[str] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> SourceSupportSummary:
        """Build the model from one released-contract JSON object."""
        values: dict[str, Any] = {}
        values["observation_count"] = data["observation_count"]
        values["sample_count"] = data["sample_count"]
        if "first_observed_at" in data:
            values["first_observed_at"] = data["first_observed_at"]
        if "last_observed_at" in data:
            values["last_observed_at"] = data["last_observed_at"]
        if "source_dataset_ids" in data:
            values["source_dataset_ids"] = list(data["source_dataset_ids"])
        if "source_manifest_ids" in data:
            values["source_manifest_ids"] = list(data["source_manifest_ids"])
        if "uncertainty_pct" in data:
            values["uncertainty_pct"] = data["uncertainty_pct"]
        if "weight_methods" in data:
            values["weight_methods"] = list(data["weight_methods"])
        return cls(**values)

    def to_dict(self) -> dict[str, Any]:
        """Render the model back to its wire form.

        Schema-optional fields that are `None` are omitted rather than
        emitted as nulls, because not every optional field is nullable.
        """
        data: dict[str, Any] = {}
        data["observation_count"] = self.observation_count
        data["sample_count"] = self.sample_count
        if self.first_observed_at is not None:
            data["first_observed_at"] = self.first_observed_at
        if self.last_observed_at is not None:
            data["last_observed_at"] = self.last_observed_at
        data["source_dataset_ids"] = list(self.source_dataset_ids)
        data["source_manifest_ids"] = list(self.source_manifest_ids)
        if self.uncertainty_pct is not None:
            data["uncertainty_pct"] = self.uncertainty_pct
        data["weight_methods"] = list(self.weight_methods)
        return data

