"""AdLift public API: ad incrementality evaluation and evidence grading."""

from modules.adlift.application import AdLiftResult, AdLiftService
from modules.adlift.domain import (
    ADLIFT_EVIDENCE_POLICY_VERSION,
    ADLIFT_FEATURE_VERSION,
    ADLIFT_MEASUREMENT_METHOD,
    ADLIFT_MODEL_VERSION,
    AdCampaign,
    ContaminationFinding,
    EffectInterval,
    EvidenceLevel,
    IncrementalityEstimate,
    IncrementalityReport,
    MatchedControl,
    PreTrendResult,
    PreTrendStatus,
    Recommendation,
    StoreDayMetric,
    assign_evidence_level,
    detect_contamination,
    evaluate_campaigns,
    evaluate_pre_trend,
    is_causal_evidence,
    match_controls,
    recommend,
    run_incrementality,
)
from modules.adlift.infrastructure import (
    CausalChallengerAdapter,
    CausalChallengerCapability,
    CausalChallengerEstimate,
    CausalChallengerRequest,
    ChallengerUnavailableError,
    DoubleMLStyleAdapter,
    EconMLStyleAdapter,
    InMemoryAdLiftRepository,
)
from modules.adlift.workers import (
    AdLiftBatchResult,
    AdLiftIncrementalityWorker,
    run_adlift_incrementality_batch,
)

__all__ = [
    "ADLIFT_EVIDENCE_POLICY_VERSION",
    "ADLIFT_FEATURE_VERSION",
    "ADLIFT_MEASUREMENT_METHOD",
    "ADLIFT_MODEL_VERSION",
    "AdCampaign",
    "AdLiftBatchResult",
    "AdLiftIncrementalityWorker",
    "AdLiftResult",
    "AdLiftService",
    "CausalChallengerAdapter",
    "CausalChallengerCapability",
    "CausalChallengerEstimate",
    "CausalChallengerRequest",
    "ChallengerUnavailableError",
    "ContaminationFinding",
    "DoubleMLStyleAdapter",
    "EconMLStyleAdapter",
    "EffectInterval",
    "EvidenceLevel",
    "InMemoryAdLiftRepository",
    "IncrementalityEstimate",
    "IncrementalityReport",
    "MatchedControl",
    "PreTrendResult",
    "PreTrendStatus",
    "Recommendation",
    "StoreDayMetric",
    "assign_evidence_level",
    "detect_contamination",
    "evaluate_campaigns",
    "evaluate_pre_trend",
    "is_causal_evidence",
    "match_controls",
    "recommend",
    "run_adlift_incrementality_batch",
    "run_incrementality",
]
