import { expect, test } from "@playwright/test";

const EXPANSION_ROUTES = [
  "/expansion",
  "/w/expansion/heatzone?selected=hz-0773&drawer=zone",
  "/w/expansion/listings?selected=lst-9003&drawer=listing",
  "/w/expansion/candidates?selected=cs-4109&drawer=candidate",
  "/w/expansion/sitescore?selected=ssr-7001&drawer=report",
  "/w/expansion/sitescore/ssr-7001",
];

test("Expansion workflow routes render inside the OpsBoard shell", async ({ page }) => {
  for (const route of EXPANSION_ROUTES) {
    const res = await page.goto(route);
    expect(res?.status(), `GET ${route}`).toBeLessThan(400);
    await expect(page.getByTestId("app-shell")).toBeVisible();
    await expect(page.getByTestId("page-header")).toBeVisible();
    await expect(page.getByTestId("expansion-data-status")).toBeVisible();
  }

  await page.goto("/expansion");
  await expect(page.getByTestId("external-freshness-lineage")).toContainText("snap-expansion-20260628-0100");
  await expect(page.getByTestId("external-freshness-lineage")).toContainText("corr-expansion-freshness-001");
});

test("HeatZone Radar exposes map, ranked list, drawer, freshness, and low confidence guard", async ({ page }) => {
  await page.goto("/w/expansion/heatzone?selected=hz-0773&drawer=zone");
  await expect(page.getByTestId("exp-heatzone-page")).toBeVisible();
  await expect(page.getByLabel("Interactive HeatZone map")).toHaveAttribute("data-selected-zone", "hz-0773");
  await expect(page.getByLabel("Map legend")).toContainText("low confidence");
  await expect(page.getByLabel("Ranked HeatZone list")).toContainText("SUPPRESSED_LOW_CONFIDENCE");
  await expect(page.getByTestId("heatzone-drawer")).toContainText("低信心 guard");
  await expect(page.getByText("source snap-expansion-20260628-0100")).toBeVisible();
});

test("Listing and Candidate screens show required operational columns and drawers", async ({ page }) => {
  await page.goto("/w/expansion/listings?selected=lst-9003&drawer=listing");
  await expect(page.getByTestId("exp-listings-page")).toContainText("FAILED_HARD_RULE");
  await expect(page.getByTestId("listing-drawer")).toContainText("field lineage");
  await expect(page.getByTestId("listing-drawer")).toContainText("correlation_id");

  await page.goto("/w/expansion/candidates?selected=cs-4109&drawer=candidate");
  await expect(page.getByTestId("exp-candidates-page")).toContainText("Rent / Area / Frontage");
  await expect(page.getByTestId("candidate-site-card")).toContainText("Nearby evidence");
  await expect(page.getByTestId("candidate-site-card")).toContainText("樓層不符硬規則");
});

test("SiteScore list and detail separate recommendation, evidence, decision, and audit", async ({ page }) => {
  await page.goto("/w/expansion/sitescore?selected=ssr-7001&drawer=report");
  await expect(page.getByTestId("exp-sitescore-page")).toContainText("M1/M3/M6/M12");
  await expect(page.getByTestId("sitescore-preview-drawer")).toContainText("開啟完整報告");

  await page.goto("/w/expansion/sitescore/ssr-7001");
  await expect(page.getByTestId("sitescore-summary")).toContainText("P10");
  await expect(page.getByTestId("evidence-panel")).toContainText("Positive factors");
  await expect(page.getByText("Generated by system, not a human decision.")).toBeVisible();
  await expect(page.getByTestId("approval-panel")).toContainText("never optimistic");
  await expect(page.getByText("decision_id dec-20260628-7001")).toBeVisible();
  await expect(page.getByText("correlation id")).toBeVisible();
});
