"""NetPlan public API.

Scenario building, constrained network optimization, alternatives,
infeasibility diagnosis, approval lifecycle, execution, and outcome tracking.
"""

from modules.netplan.application import (
    NetPlanApprovalError,
    NetPlanConstraintDisclosureError,
    NetPlanNotFoundError,
    NetPlanProductionExecution,
    NetPlanProductionExecutionError,
    NetPlanProductionExecutor,
    NetPlanService,
    ScenarioBuildRequest,
)
from modules.netplan.domain import (
    NETPLAN_FEATURE_VERSION,
    NETPLAN_MODEL_VERSION,
    NETPLAN_SOLVER_VERSION,
    VALID_TRANSITIONS,
    ApprovalRecord,
    CandidateSiteInput,
    ConstraintDisclosureAcknowledgement,
    ExecutionRecord,
    ExistingStoreInput,
    InvalidNetPlanTransitionError,
    NetPlanScenario,
    NetPlanScenarioStatus,
    OutcomeRecord,
    ScenarioSolveRecord,
    StatusTransition,
    build_outcome_record,
    build_scenario_options,
)
from modules.netplan.infrastructure import (
    ImmutableRecordError,
    InMemoryNetPlanRepository,
)
from modules.netplan.workers import (
    NetPlanBatchResult,
    NetPlanSolverWorker,
    run_netplan_solver_batch,
)
from solver.netplan import (
    BUSINESS_UAT_UNVERIFIED,
    BUSINESS_UAT_VERIFIED,
    GOVERNED_DISABLED,
    GOVERNED_ENABLED,
    ActionOption,
    ConstraintClass,
    FixedManagementApprovalReceiptVerifier,
    ManagementApprovalExpectation,
    ManagementApprovalReceipt,
    ManagementApprovalReceiptVerifier,
    ManagementApprovalVerification,
    ManagementBaselineComparisonReceipt,
    ManagementBaselineInput,
    NetPlanConstraints,
    NetworkAction,
    compare_solver_against_management_baseline,
    compute_solver_problem_hash,
)

__all__ = [
    "BUSINESS_UAT_UNVERIFIED",
    "BUSINESS_UAT_VERIFIED",
    "GOVERNED_DISABLED",
    "GOVERNED_ENABLED",
    "NETPLAN_FEATURE_VERSION",
    "NETPLAN_MODEL_VERSION",
    "NETPLAN_SOLVER_VERSION",
    "VALID_TRANSITIONS",
    "ActionOption",
    "ApprovalRecord",
    "CandidateSiteInput",
    "ConstraintClass",
    "ConstraintDisclosureAcknowledgement",
    "ExecutionRecord",
    "ExistingStoreInput",
    "FixedManagementApprovalReceiptVerifier",
    "ImmutableRecordError",
    "InMemoryNetPlanRepository",
    "InvalidNetPlanTransitionError",
    "ManagementApprovalExpectation",
    "ManagementApprovalReceipt",
    "ManagementApprovalReceiptVerifier",
    "ManagementApprovalVerification",
    "ManagementBaselineComparisonReceipt",
    "ManagementBaselineInput",
    "NetPlanApprovalError",
    "NetPlanConstraintDisclosureError",
    "NetPlanBatchResult",
    "NetPlanConstraints",
    "NetPlanNotFoundError",
    "NetPlanProductionExecution",
    "NetPlanProductionExecutionError",
    "NetPlanProductionExecutor",
    "NetPlanScenario",
    "NetPlanScenarioStatus",
    "NetPlanService",
    "NetPlanSolverWorker",
    "NetworkAction",
    "OutcomeRecord",
    "ScenarioBuildRequest",
    "ScenarioSolveRecord",
    "StatusTransition",
    "build_outcome_record",
    "build_scenario_options",
    "compare_solver_against_management_baseline",
    "compute_solver_problem_hash",
    "run_netplan_solver_batch",
]
