"""Canonical production training-to-runtime model contracts.

This registry names only models that the production training command can
actually produce. A capability without a trainer or mature data contract stays
explicitly unavailable instead of inventing an MLflow alias for it.

Governed-disabled capabilities are an auditable first-class state: their
observed/eligible label counts come from the release-bound PG16 model-ready
inventory receipt (``model_ready_inventory_receipt.json``, generated by
``scripts/models/model_ready_receipt.py`` from the persisted
``model_ready.view_contracts`` inventory), never from source-code constants.
Each binding carries the inventory observation time and version, plus a
separate policy activation threshold, so the runtime can report
``productionBindingsReady=True`` while still failing closed for the disabled
service.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from types import MappingProxyType
from typing import Any

from models.shared_ml.model_ready_receipt import (
    ModelReadyReceiptError,
    load_model_ready_receipt,
)

# Fails closed at import: a missing or tampered receipt must stop the runtime
# from composing governed-disabled evidence, not degrade to invented counts.
MODEL_READY_RECEIPT: Mapping[str, Any] = MappingProxyType(load_model_ready_receipt())


@dataclass(frozen=True)
class GovernedDisabledBinding:
    """Evidence record for a capability that is explicitly disabled by governance.

    Counts and lineage fields come from the release-bound PG16 model-ready
    inventory receipt; the activation threshold is governance policy and is
    deliberately a separate field from the observed/eligible counts.
    """

    reason_code: str
    """Canonical SCREAMING_SNAKE reason code (e.g. DATA_CONTRACT_NOT_MATURE)."""

    observed_count: int
    """Real observed rows with a non-null real label, from the inventory receipt."""

    eligible_count: int
    """Real training-eligible rows, from the inventory receipt."""

    activation_threshold: int
    """Policy minimum eligible labeled rows required to activate (not a count)."""

    source_contract: str
    """Model-ready relation@view_version that owns the eligibility gate."""

    owner: str
    """Team or service that owns the activation decision."""

    activation_gate: str
    """Human-readable description of what must be true to move to active."""

    observed_at: str
    """Database-clock timestamp at which the inventory was observed."""

    inventory_version: str
    """Immutable version identifier of the inventory receipt."""

    auto_seeded: bool = False
    """Must remain False; synthetic seed substitution is forbidden."""

    def __post_init__(self) -> None:
        if self.auto_seeded is not False:
            raise ModelReadyReceiptError(
                f"governed-disabled evidence for {self.source_contract} must have "
                "auto_seeded=False; synthetic seeding is forbidden"
            )
        if self.observed_count < 0 or self.eligible_count < 0:
            raise ModelReadyReceiptError(
                "governed-disabled counts must be non-negative real observations"
            )
        if self.activation_threshold <= 0:
            raise ModelReadyReceiptError("activation_threshold must be a positive policy value")
        for field_name in ("reason_code", "source_contract", "owner", "activation_gate",
                           "observed_at", "inventory_version"):
            if not str(getattr(self, field_name) or "").strip():
                raise ModelReadyReceiptError(
                    f"governed-disabled evidence field {field_name} is missing"
                )

    def to_audit_dict(self) -> dict[str, Any]:
        return {
            "reasonCode": self.reason_code,
            "observedCount": self.observed_count,
            "eligibleCount": self.eligible_count,
            "activationThreshold": self.activation_threshold,
            "sourceContract": self.source_contract,
            "owner": self.owner,
            "activationGate": self.activation_gate,
            "observedAt": self.observed_at,
            "inventoryVersion": self.inventory_version,
            "autoSeeded": self.auto_seeded,
        }


@dataclass(frozen=True)
class ProductionModelContract:
    service: str
    model_name: str | None
    training_spec_key: str | None
    required_for_platform_readiness: bool
    outcome_contract_required: bool
    unavailable_reason: str | None = None
    governed_disabled_binding: GovernedDisabledBinding | None = None

    def __post_init__(self) -> None:
        # The capability record's reason and the evidence reason must be the
        # same fact; the live gate enforces the equality end to end.
        if (
            self.governed_disabled_binding is not None
            and self.governed_disabled_binding.reason_code != self.unavailable_reason
        ):
            raise ModelReadyReceiptError(
                f"{self.service}: capability reason {self.unavailable_reason!r} does not "
                f"match evidence reason {self.governed_disabled_binding.reason_code!r}"
            )

    @property
    def trainable(self) -> bool:
        return self.model_name is not None and self.training_spec_key is not None

    @property
    def is_governed_disabled(self) -> bool:
        """True when this capability has explicit governed-disabled evidence."""
        return self.governed_disabled_binding is not None


def _governed_disabled_binding(
    service: str,
    *,
    reason_code: str,
    activation_threshold: int,
    owner: str,
    activation_gate: str,
) -> GovernedDisabledBinding:
    """Build governed-disabled evidence from the inventory receipt, fail closed."""
    capability = MODEL_READY_RECEIPT["capabilities"].get(service)
    if not isinstance(capability, Mapping):
        raise ModelReadyReceiptError(
            f"model-ready inventory receipt has no capability entry for {service!r}"
        )
    return GovernedDisabledBinding(
        reason_code=reason_code,
        observed_count=int(capability["observed_count"]),
        eligible_count=int(capability["eligible_count"]),
        activation_threshold=activation_threshold,
        source_contract=f"{capability['relation']}@{capability['view_version']}",
        owner=owner,
        activation_gate=activation_gate,
        observed_at=str(MODEL_READY_RECEIPT["observed_at"]),
        inventory_version=str(MODEL_READY_RECEIPT["inventory_version"]),
        auto_seeded=bool(MODEL_READY_RECEIPT["auto_seeded"]),
    )


# Canonical production capability registry.
#
# ForecastOps: trains from PIT-safe PG16 rows (receipt records the observed
#   count); binds a real MLflow production alias at startup.
#
# AVM, HeatZone, SiteScore: the PG16 model-ready inventory reports zero
#   eligible labeled rows, below each activation threshold, so they are
#   governed-disabled with receipt-backed evidence; the runtime must not
#   fabricate a production alias for them. Activation thresholds mirror
#   ``scripts.models.contracts.MODEL_SPECS[*].minimum_rows`` (anti-drift
#   tested); they are policy values, distinct from the observed counts.
PRODUCTION_MODEL_CONTRACTS: Mapping[str, ProductionModelContract] = (
    MappingProxyType(
        {
            "forecastops": ProductionModelContract(
                service="forecastops",
                model_name="forecast_revenue_interval",
                training_spec_key="forecastops",
                required_for_platform_readiness=True,
                outcome_contract_required=True,
            ),
            "avm": ProductionModelContract(
                service="avm",
                model_name="dealroom_avm",
                training_spec_key="avm",
                required_for_platform_readiness=True,
                outcome_contract_required=True,
                unavailable_reason="DATA_CONTRACT_NOT_MATURE",
                governed_disabled_binding=_governed_disabled_binding(
                    "avm",
                    reason_code="DATA_CONTRACT_NOT_MATURE",
                    activation_threshold=120,
                    owner="avm-platform-team",
                    activation_gate=(
                        "Requires >= 120 eligible labeled PG16 rows in "
                        "model_ready.valuation_view (mature realized transaction "
                        "outcomes) and independent label-authority approval"
                    ),
                ),
            ),
            "sitescore": ProductionModelContract(
                service="sitescore",
                model_name="sitescore_propensity",
                training_spec_key="sitescore",
                required_for_platform_readiness=True,
                outcome_contract_required=True,
                unavailable_reason="DATA_CONTRACT_NOT_MATURE",
                governed_disabled_binding=_governed_disabled_binding(
                    "sitescore",
                    reason_code="DATA_CONTRACT_NOT_MATURE",
                    activation_threshold=200,
                    owner="sitescore-platform-team",
                    activation_gate=(
                        "Requires >= 200 eligible labeled PG16 rows in "
                        "model_ready.candidate_site_view and independent "
                        "label-authority approval"
                    ),
                ),
            ),
            "heatzone": ProductionModelContract(
                service="heatzone",
                model_name="heatzone_priority",
                training_spec_key="heatzone",
                required_for_platform_readiness=True,
                outcome_contract_required=True,
                unavailable_reason="DATA_CONTRACT_NOT_MATURE",
                governed_disabled_binding=_governed_disabled_binding(
                    "heatzone",
                    reason_code="DATA_CONTRACT_NOT_MATURE",
                    activation_threshold=200,
                    owner="heatzone-platform-team",
                    activation_gate=(
                        "Requires >= 200 eligible labeled PG16 rows in "
                        "model_ready.heatzone_training_view (approved immutable "
                        "opened_on authority) and independent label-authority approval"
                    ),
                ),
            ),
        }
    )
)


def production_model_names(
    services: Iterable[str] | None = None,
) -> dict[str, str]:
    """Return service-to-MLflow names for capabilities with real trainers.

    Only returns names for services that are NOT governed-disabled; calling
    code must not fabricate aliases for governed-disabled capabilities.
    """

    requested = tuple(services) if services is not None else tuple(
        PRODUCTION_MODEL_CONTRACTS
    )
    names: dict[str, str] = {}
    for service in requested:
        contract = PRODUCTION_MODEL_CONTRACTS[service]
        if contract.model_name is not None and not contract.is_governed_disabled:
            names[service] = contract.model_name
    return names


def governed_disabled_services() -> frozenset[str]:
    """Return the set of services that are in governed-disabled state."""
    return frozenset(
        service
        for service, contract in PRODUCTION_MODEL_CONTRACTS.items()
        if contract.is_governed_disabled
    )


def required_production_model_services() -> frozenset[str]:
    return frozenset(
        service
        for service, contract in PRODUCTION_MODEL_CONTRACTS.items()
        if contract.required_for_platform_readiness
    )


__all__ = [
    "MODEL_READY_RECEIPT",
    "PRODUCTION_MODEL_CONTRACTS",
    "GovernedDisabledBinding",
    "ModelReadyReceiptError",
    "ProductionModelContract",
    "governed_disabled_services",
    "production_model_names",
    "required_production_model_services",
]
