from __future__ import annotations

import subprocess
from pathlib import Path

from common import (
    agent_config_for,
    command_exists,
    delivery_workspace_root,
    ensure_parent,
    new_runtime_id,
    normalize_agent_id,
    relpath,
)

from adapters.base import BaseAdapter, DeliveryCapability, DeliveryRequest, DeliveryResult


class FileInboxAdapter(BaseAdapter):
    name = "file_inbox"

    def capability(self, agent_id: str) -> DeliveryCapability:
        return DeliveryCapability(
            adapter=self.name,
            supported=True,
            requires_manual_confirmation=True,
            can_auto_deliver=False,
            can_auto_approve_edits=False,
            delivery_mode="file_inbox",
            verified="verified",
            host="workspace file + VS Code CLI",
            notes="Writes a minimal inbox file and can optionally surface it in the current VS Code window.",
        )

    def deliver(self, request: DeliveryRequest) -> DeliveryResult:
        agent = agent_config_for(self.config, request.agent_id)
        provider = self.config.get("providers", {}).get(agent.get("provider", request.provider), {})
        inbox_settings = provider.get("file_inbox", {})
        inbox_map = inbox_settings.get("agent_paths", {}) or {}
        inbox_value = agent.get("file_inbox_path") or inbox_map.get(agent.get("id")) or inbox_settings.get("path")
        inbox_path = Path(inbox_value or f".llm-inbox/{normalize_agent_id(request.agent_id)}.md")
        workspace_root = delivery_workspace_root(self.config, request.metadata)
        if not inbox_path.is_absolute():
            inbox_path = workspace_root / inbox_path
        ensure_parent(inbox_path)
        body = "\n".join(
            [
                "<!-- Generated by .orchestrator. Shared state remains the source of truth. -->",
                f"# Wake-up for {agent.get('display_name', request.agent_id)}",
                "",
                request.message.strip(),
                "",
                "## Context Files",
                *(f"- `{path}`" for path in request.context_files),
            ]
        ).rstrip() + "\n"
        inbox_path.write_text(body, encoding="utf-8")

        command: list[str] = []
        if inbox_settings.get("open_in_vscode", False) and command_exists("code"):
            command = ["code", "-r", str(inbox_path)]
            subprocess.Popen(
                command,
                cwd=str(workspace_root),
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )

        return DeliveryResult(
            ok=True,
            adapter=self.name,
            mode="file_inbox",
            target=agent.get("display_name", request.agent_id),
            auto_delivered=False,
            manual_confirmation_required=True,
            notes=f"Inbox written to {relpath(inbox_path)}",
            command=command,
            payload_path=str(inbox_path),
            run_id=new_runtime_id("inbox"),
        )
