#!/usr/bin/env python3
"""Generate the governed vocabularies, and refuse a second definition of one.

A concept that lives in a Python domain enum, a TypeScript wire contract and an
API payload has three lifecycles and no owner. Each fork is locally reasonable
-- someone needed the type in a layer that did not have it, and wrote one -- and
nothing detects that the same concept now has two definitions.

Evidence Level has four:

    packages/schemas/canonical/index.ts          'L0'..'L5'   (declared authority)
    modules/intervention/domain/lifecycle.py     L0..L5       (its own copy)
    modules/adlift/domain/incrementality.py      L0..L5       (another copy)
    packages/domain-types/src/frontend-contracts.ts
                                                 "high" | "medium" | "low" | "insufficient"
    apps/api/.../priceops.py, .../growth.py      str = "medium"

The last two are a different vocabulary for the same concept, with no conversion
anywhere in the tree.

ODP-EVIDENCE-LEVEL-ALIGNMENT-001 already aligned Evidence Level once, and it
still missed three places -- because alignment was a one-off human sweep, not a
standing constraint. This is the standing constraint.

WHAT IT DOES

``--check`` (the CI mode) fails when:

* the generated Python module is stale relative to vocabularies.json, or
* the canonical TypeScript type no longer matches the declared members, or
* a *new* definition of a governed vocabulary appears anywhere outside the
  generated module and the recorded forks.

The forks that exist today are recorded in vocabularies.json with a note saying
what each one is and why it is wrong. They are not silently tolerated: they are
written down, and nothing new may join them.

``--write`` regenerates the Python module.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCE = REPO_ROOT / "packages" / "schemas" / "canonical" / "vocabularies.json"
GENERATED = REPO_ROOT / "shared" / "governance" / "vocabularies.py"
CANONICAL_TS = REPO_ROOT / "packages" / "schemas" / "canonical" / "index.ts"

SCANNED_ROOTS = ("modules", "shared", "solver", "models", "apps", "packages")

BANNER = (
    "# Generated by delivery_toolchain/governance/generate_vocabularies.py "
    "from packages/schemas/canonical/vocabularies.json -- do not edit.\n"
    "#\n"
    "# These vocabularies cross the Python / TypeScript / API boundary. Editing a\n"
    "# copy instead of the source is how the same concept ends up with two\n"
    "# definitions, which is what this generator exists to stop. Change\n"
    "# vocabularies.json and re-run with --write.\n"
)


@dataclass(frozen=True)
class Fork:
    vocabulary: str
    path: str
    lineno: int

    def describe(self) -> str:
        return (
            f"{self.vocabulary} is defined again at {self.path}:{self.lineno}. "
            f"Import it from shared.governance.vocabularies, or record the fork in "
            f"vocabularies.json under known_forks with a note saying why it exists."
        )


def load() -> dict:
    return json.loads(SOURCE.read_text(encoding="utf-8"))


def render(payload: dict) -> str:
    lines = [BANNER, '"""Governed cross-layer vocabularies."""', "", "from __future__ import annotations", "", "from enum import StrEnum", "", ""]
    names: list[str] = []
    for vocabulary in payload["vocabularies"]:
        name = vocabulary["name"]
        names.append(name)
        lines.append(f"class {name}(StrEnum):")
        doc = vocabulary.get("docstring", "").rstrip()
        if doc:
            indented = "\n".join(
                ("    " + line).rstrip() if line else "" for line in doc.splitlines()
            )
            lines.append('    """' + indented.lstrip() + "\n")
            lines.append(f'    Authority: {vocabulary.get("authority", "unstated")}.')
            lines.append('    """')
            lines.append("")
        for member in vocabulary["members"]:
            comment = member.get("comment", "")
            suffix = f"  # {comment}" if comment else ""
            lines.append(f'    {member["name"]} = "{member["value"]}"{suffix}')
        lines.append("")
        lines.append("")
    lines.append("__all__ = [")
    for name in sorted(names):
        lines.append(f'    "{name}",')
    lines.append("]")
    return "\n".join(lines) + "\n"


def _typescript_mismatch(payload: dict) -> list[str]:
    """Confirm the canonical TS type still lists exactly the declared values."""
    problems: list[str] = []
    source = CANONICAL_TS.read_text(encoding="utf-8")
    for vocabulary in payload["vocabularies"]:
        ts_name = vocabulary.get("typescript_type")
        if not ts_name:
            continue
        match = re.search(rf"export type {re.escape(ts_name)}\s*=\s*([^;]+);", source)
        if match is None:
            problems.append(f"{CANONICAL_TS.name} declares no `export type {ts_name}`")
            continue
        declared = {v.strip().strip("'\"") for v in match.group(1).split("|")}
        expected = {member["value"] for member in vocabulary["members"]}
        if declared != expected:
            problems.append(
                f"{CANONICAL_TS.name} `{ts_name}` is {sorted(declared)}, "
                f"vocabularies.json says {sorted(expected)}"
            )
    return problems


def find_forks(payload: dict) -> list[Fork]:
    """Every Python definition of a governed vocabulary outside the generated module."""
    governed = {v["name"]: v for v in payload["vocabularies"]}
    recorded = {
        (v["name"], fork["location"])
        for v in payload["vocabularies"]
        for fork in v.get("known_forks", [])
        for location in [fork["location"]]
    }
    recorded_paths = {
        (name, part.strip())
        for name, location in recorded
        for part in location.split(",")
    }

    forks: list[Fork] = []
    for root_name in SCANNED_ROOTS:
        root = REPO_ROOT / root_name
        if not root.is_dir():
            continue
        for path in root.rglob("*.py"):
            parts = path.parts
            if "__pycache__" in parts or "node_modules" in parts:
                continue
            if path == GENERATED:
                continue
            try:
                tree = ast.parse(path.read_text(encoding="utf-8"))
            except (OSError, SyntaxError, UnicodeDecodeError):
                continue
            relative = str(path.relative_to(REPO_ROOT))
            for node in ast.walk(tree):
                if not isinstance(node, ast.ClassDef) or node.name not in governed:
                    continue
                if (node.name, relative) in recorded_paths:
                    continue
                forks.append(Fork(vocabulary=node.name, path=relative, lineno=node.lineno))
    return sorted(forks, key=lambda f: (f.path, f.lineno))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="regenerate the Python module")
    group.add_argument("--check", action="store_true", help="fail on staleness, TS mismatch or a new fork")
    parser.add_argument("--show-forks", action="store_true", help="list the forks recorded in the source")
    args = parser.parse_args(argv)

    payload = load()
    rendered = render(payload)

    if args.write:
        GENERATED.parent.mkdir(parents=True, exist_ok=True)
        GENERATED.write_text(rendered, encoding="utf-8")
        print(f"Wrote {GENERATED.relative_to(REPO_ROOT)}")
        return 0

    if args.show_forks:
        for vocabulary in payload["vocabularies"]:
            for fork in vocabulary.get("known_forks", []):
                print(f"{vocabulary['name']} -- {fork['location']}")
                print(f"    {fork['definition']}")
                print(f"    {fork['note']}")
        print()

    problems: list[str] = []
    if not GENERATED.exists():
        problems.append(f"{GENERATED.relative_to(REPO_ROOT)} has not been generated; run with --write")
    elif GENERATED.read_text(encoding="utf-8") != rendered:
        problems.append(
            f"{GENERATED.relative_to(REPO_ROOT)} is stale relative to vocabularies.json; run with --write"
        )
    problems.extend(_typescript_mismatch(payload))
    problems.extend(fork.describe() for fork in find_forks(payload))

    if problems:
        print("Vocabulary checks failed:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1

    recorded = sum(len(v.get("known_forks", [])) for v in payload["vocabularies"])
    print(
        f"Vocabulary checks passed: {len(payload['vocabularies'])} governed, "
        f"{recorded} pre-existing forks recorded, no new ones."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
