"""Generate consumer models from the pinned foundation schemas.

The models under `packages/oday_data_contracts_client/models/` are produced by
this module and checked in. Checking them in is what makes the client usable
without a build step; regenerating them here is what keeps them honest. The
contract test regenerates in memory and compares, so a hand-edited model, or a
pin moved without regeneration, fails CI.

Only the schema documents named by `config/oday_data_contracts.toml` are read.
The producer's `storage-schema.sql` is never an input: these are contract
models, not a copy of the producer's tables.

Usage::

    uv run python -m packages.oday_data_contracts_client.codegen --check
    uv run python -m packages.oday_data_contracts_client.codegen --write
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any

from .errors import GeneratedClientStaleError
from .pin import ContractPin, PinnedContract, load_pin
from .release import FoundationRelease, load_release

GENERATED_HEADER = "# Generated by packages/oday_data_contracts_client/codegen.py -- do not edit."

_PRIMITIVES = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
}


# ---------------------------------------------------------------------------
# Type model
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class PyType:
    """A rendered Python type plus how to move a value across the wire."""

    annotation: str
    kind: str  # raw | alias | enum | model | list | optional
    name: str = ""
    inner: PyType | None = None

    @property
    def converts(self) -> bool:
        if self.kind in {"enum", "model"}:
            return True
        if self.inner is not None:
            return self.inner.converts
        return False


RAW_ANY = PyType(annotation="Any", kind="raw")


def _optional(inner: PyType) -> PyType:
    if inner.kind == "optional":
        return inner
    if inner.kind == "alias" and inner.inner is not None and inner.inner.kind == "optional":
        return inner  # the alias already spells `| None`
    annotation = "Any" if inner.annotation == "Any" else f"{inner.annotation} | None"
    return PyType(annotation=annotation, kind="optional", inner=inner)


def _list_of(inner: PyType) -> PyType:
    return PyType(annotation=f"list[{inner.annotation}]", kind="list", inner=inner)


def decode_expr(py_type: PyType, source: str) -> str:
    """Expression turning a wire value at `source` into the model value."""
    match py_type.kind:
        case "enum":
            return f"{py_type.name}({source})"
        case "model":
            return f"{py_type.name}.from_dict({source})"
        case "list":
            inner = py_type.inner
            assert inner is not None
            if inner.converts:
                return f"[{decode_expr(inner, 'item')} for item in {source}]"
            return f"list({source})"
        case "optional":
            inner = py_type.inner
            assert inner is not None
            if not inner.converts:
                return source
            return f"None if {source} is None else {decode_expr(inner, source)}"
        case _:
            return source


def encode_expr(py_type: PyType, source: str) -> str:
    """Expression turning a model value at `source` back into a wire value."""
    match py_type.kind:
        case "enum":
            return f"{source}.value"
        case "model":
            return f"{source}.to_dict()"
        case "list":
            inner = py_type.inner
            assert inner is not None
            if inner.converts:
                return f"[{encode_expr(inner, 'item')} for item in {source}]"
            return f"list({source})"
        case "optional":
            inner = py_type.inner
            assert inner is not None
            if not inner.converts:
                return source
            return f"None if {source} is None else {encode_expr(inner, source)}"
        case _:
            return source


# ---------------------------------------------------------------------------
# Naming
# ---------------------------------------------------------------------------


def _is_class_identifier(value: str) -> bool:
    return bool(re.fullmatch(r"[A-Z][A-Za-z0-9]*", value))


def pascal_case(value: str) -> str:
    if _is_class_identifier(value):
        return value
    parts = [part for part in re.split(r"[^A-Za-z0-9]+", value) if part]
    return "".join(part[:1].upper() + part[1:] for part in parts)


def root_class_name(schema: Mapping[str, Any], module: str) -> str:
    title = schema.get("title")
    if isinstance(title, str) and _is_class_identifier(title):
        return title
    return pascal_case(module)


# ---------------------------------------------------------------------------
# Schema -> type resolution
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class DefKind:
    class_name: str
    kind: str  # enum | model | alias


class SchemaContext:
    """Resolves `$ref`s within one contract schema document."""

    def __init__(self, schema: Mapping[str, Any], module: str) -> None:
        self.schema = schema
        self.module = module
        self._resolving: set[str] = set()
        self.defs: Mapping[str, Any] = schema.get("$defs", {}) or {}
        self.kinds: dict[str, DefKind] = {}
        for def_name, definition in self.defs.items():
            if "enum" in definition:
                kind = "enum"
            elif definition.get("type") == "object" and "properties" in definition:
                kind = "model"
            else:
                kind = "alias"
            self.kinds[def_name] = DefKind(class_name=pascal_case(def_name), kind=kind)
        self.root_name = root_class_name(schema, module)
        clash = [d.class_name for d in self.kinds.values() if d.class_name == self.root_name]
        if clash:
            raise GeneratedClientStaleError(
                f"{module}: root class {self.root_name!r} collides with a $defs class name"
            )

    def _resolve_alias(self, def_name: str) -> PyType:
        """Resolve what an alias stands for, so `| None` is not applied twice."""
        if def_name in self._resolving:
            return RAW_ANY
        self._resolving.add(def_name)
        try:
            return resolve_type(self.defs[def_name], self)
        finally:
            self._resolving.discard(def_name)

    def resolve_ref(self, ref: str) -> PyType:
        if not ref.startswith("#/$defs/"):
            return RAW_ANY
        def_name = ref.removeprefix("#/$defs/")
        info = self.kinds.get(def_name)
        if info is None:
            return RAW_ANY
        if info.kind == "alias":
            return PyType(
                annotation=info.class_name,
                kind="alias",
                name=info.class_name,
                inner=self._resolve_alias(def_name),
            )
        return PyType(annotation=info.class_name, kind=info.kind, name=info.class_name)


def resolve_type(node: Any, ctx: SchemaContext) -> PyType:
    """Map a schema node onto the closest faithful Python type."""
    if not isinstance(node, Mapping):
        return RAW_ANY

    if "$ref" in node:
        return ctx.resolve_ref(str(node["$ref"]))

    for combinator in ("anyOf", "oneOf"):
        members = node.get(combinator)
        if isinstance(members, Sequence) and not isinstance(members, str):
            return _resolve_union(list(members), ctx)

    all_of = node.get("allOf")
    if isinstance(all_of, Sequence) and not isinstance(all_of, str):
        typed = [m for m in all_of if isinstance(m, Mapping) and ("$ref" in m or "type" in m)]
        if len(typed) == 1:
            return resolve_type(typed[0], ctx)
        return RAW_ANY

    node_type = node.get("type")
    if isinstance(node_type, list):
        names = [str(item) for item in node_type]
        nullable = "null" in names
        rest = [name for name in names if name != "null"]
        if len(rest) != 1:
            return RAW_ANY
        base = resolve_type({**node, "type": rest[0]}, ctx)
        return _optional(base) if nullable else base

    if node_type == "array":
        items = node.get("items")
        if isinstance(items, Mapping):
            return _list_of(resolve_type(items, ctx))
        return _list_of(RAW_ANY)

    if node_type == "object":
        return PyType(annotation="dict[str, Any]", kind="raw")

    if node_type == "null":
        return PyType(annotation="None", kind="raw")

    if isinstance(node_type, str) and node_type in _PRIMITIVES:
        return PyType(annotation=_PRIMITIVES[node_type], kind="raw")

    return RAW_ANY


def _resolve_union(members: list[Any], ctx: SchemaContext) -> PyType:
    nullable = any(isinstance(m, Mapping) and m.get("type") == "null" for m in members)
    rest = [m for m in members if not (isinstance(m, Mapping) and m.get("type") == "null")]
    if len(rest) != 1:
        return RAW_ANY
    base = resolve_type(rest[0], ctx)
    return _optional(base) if nullable else base


# ---------------------------------------------------------------------------
# Literals
# ---------------------------------------------------------------------------


def quote(value: str) -> str:
    """Double-quoted Python string literal, so generated output matches repo style."""
    return json.dumps(value, ensure_ascii=False)


def literal(value: Any) -> str:
    """Render a JSON default as a deterministic Python literal."""
    if value is None:
        return "None"
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, str):
        return quote(value)
    if isinstance(value, int | float):
        return repr(value)
    if isinstance(value, list):
        return "[" + ", ".join(literal(item) for item in value) + "]"
    if isinstance(value, Mapping):
        return "{" + ", ".join(f"{quote(k)}: {literal(v)}" for k, v in value.items()) + "}"
    raise GeneratedClientStaleError(f"unsupported default literal: {value!r}")


def enum_default(py_type: PyType, value: Any) -> str:
    if py_type.kind == "enum" and isinstance(value, str):
        return f"{py_type.name}.{value}"
    if py_type.kind == "optional" and py_type.inner is not None:
        return enum_default(py_type.inner, value)
    return literal(value)


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ModelField:
    name: str
    py_type: PyType
    required: bool
    default: str | None
    description: str


def _doc(node: Mapping[str, Any]) -> str:
    for key in ("description", "title"):
        value = node.get(key)
        if isinstance(value, str) and value.strip():
            return " ".join(value.split())
    return ""


def _model_fields(node: Mapping[str, Any], ctx: SchemaContext) -> list[ModelField]:
    properties = node.get("properties") or {}
    required = set(node.get("required") or ())
    fields: list[ModelField] = []
    for prop_name, prop_schema in properties.items():
        if not isinstance(prop_schema, Mapping):
            continue
        py_type = resolve_type(prop_schema, ctx)
        is_required = prop_name in required
        has_default = "default" in prop_schema
        default: str | None = None
        if has_default:
            raw_default = prop_schema["default"]
            if raw_default is None:
                py_type = _optional(py_type)
            default = enum_default(py_type, raw_default)
        elif not is_required:
            py_type = _optional(py_type)
            default = "None"
        fields.append(
            ModelField(
                name=prop_name,
                py_type=py_type,
                required=is_required,
                default=default,
                description=_doc(prop_schema),
            )
        )
    # Dataclass ordering: everything without a default has to come first.
    return [f for f in fields if f.default is None] + [f for f in fields if f.default is not None]


def _render_enum(class_name: str, definition: Mapping[str, Any]) -> list[str]:
    lines = [f"class {class_name}(StrEnum):"]
    doc = _doc(definition)
    lines.append(f'    """{doc}"""' if doc else f'    """Released enumeration {class_name}."""')
    lines.append("")
    for value in definition.get("enum", []):
        lines.append(f"    {value} = {quote(value)}")
    lines.append("")
    lines.append("")
    return lines


def _render_alias(class_name: str, definition: Mapping[str, Any], ctx: SchemaContext) -> list[str]:
    py_type = resolve_type(definition, ctx)
    doc = _doc(definition)
    lines: list[str] = []
    if doc:
        lines.append(f"# {doc}")
    lines.append(f"{class_name} = {py_type.annotation}")
    lines.append("")
    lines.append("")
    return lines


def _render_model(
    class_name: str,
    definition: Mapping[str, Any],
    ctx: SchemaContext,
    *,
    extra_docs: Sequence[str] = (),
) -> list[str]:
    fields = _model_fields(definition, ctx)
    lines = ["@dataclass(frozen=True, slots=True)", f"class {class_name}:"]
    doc = _doc(definition) or f"Released contract model {class_name}."
    if extra_docs:
        lines.append(f'    """{doc}')
        lines.append("")
        lines.extend(f"    {line}" for line in extra_docs)
        lines.append('    """')
    else:
        lines.append(f'    """{doc}"""')
    lines.append("")

    if not fields:
        lines.append("    pass")
    for model_field in fields:
        annotation = f"    {model_field.name}: {model_field.py_type.annotation}"
        if model_field.default is None:
            lines.append(annotation)
        elif model_field.default == "[]":
            lines.append(f"{annotation} = field(default_factory=list)")
        elif model_field.default == "{}":
            lines.append(f"{annotation} = field(default_factory=dict)")
        elif model_field.default.startswith(("[", "{")):
            lines.append(f"{annotation} = field(default_factory=lambda: {model_field.default})")
        else:
            lines.append(f"{annotation} = {model_field.default}")

    lines.append("")
    lines.append("    @classmethod")
    lines.append(f"    def from_dict(cls, data: Mapping[str, Any]) -> {class_name}:")
    lines.append('        """Build the model from one released-contract JSON object."""')
    lines.append("        values: dict[str, Any] = {}")
    for model_field in fields:
        key = model_field.name
        access = f"data[{quote(key)}]"
        if model_field.default is None:
            lines.append(f"        values[{quote(key)}] = {decode_expr(model_field.py_type, access)}")
        else:
            lines.append(f"        if {quote(key)} in data:")
            lines.append(
                f"            values[{quote(key)}] = {decode_expr(model_field.py_type, access)}"
            )
    lines.append("        return cls(**values)")

    lines.append("")
    lines.append("    def to_dict(self) -> dict[str, Any]:")
    lines.append('        """Render the model back to its wire form.')
    lines.append("")
    lines.append("        Schema-optional fields that are `None` are omitted rather than")
    lines.append("        emitted as nulls, because not every optional field is nullable.")
    lines.append('        """')
    lines.append("        data: dict[str, Any] = {}")
    for model_field in fields:
        key = model_field.name
        source = f"self.{key}"
        if model_field.py_type.kind == "optional":
            inner = model_field.py_type.inner or model_field.py_type
            lines.append(f"        if {source} is not None:")
            lines.append(f"            data[{quote(key)}] = {encode_expr(inner, source)}")
        else:
            lines.append(f"        data[{quote(key)}] = {encode_expr(model_field.py_type, source)}")
    lines.append("        return data")
    lines.append("")
    lines.append("")
    return lines


def _alias_order(ctx: SchemaContext) -> list[str]:
    """Aliases are real module-level assignments, so emit dependencies first."""
    aliases = sorted(name for name, info in ctx.kinds.items() if info.kind == "alias")
    remaining = list(aliases)
    ordered: list[str] = []
    while remaining:
        progressed = False
        for name in list(remaining):
            refs = _referenced_defs(ctx.defs[name])
            pending = {r for r in refs if r in remaining and r != name}
            if not pending:
                ordered.append(name)
                remaining.remove(name)
                progressed = True
        if not progressed:  # cyclic aliases: fall back to a stable order
            ordered.extend(remaining)
            break
    return ordered


def _referenced_defs(node: Any) -> set[str]:
    found: set[str] = set()
    if isinstance(node, Mapping):
        ref = node.get("$ref")
        if isinstance(ref, str) and ref.startswith("#/$defs/"):
            found.add(ref.removeprefix("#/$defs/"))
        for value in node.values():
            found |= _referenced_defs(value)
    elif isinstance(node, Sequence) and not isinstance(node, str):
        for value in node:
            found |= _referenced_defs(value)
    return found


def render_module(
    pinned: PinnedContract,
    schema: Mapping[str, Any],
    pin: ContractPin,
) -> str:
    """Render one contract module. Deterministic for a given schema and pin."""
    ctx = SchemaContext(schema, pinned.module)

    body: list[str] = []
    for def_name in sorted(name for name, info in ctx.kinds.items() if info.kind == "enum"):
        body.extend(_render_enum(ctx.kinds[def_name].class_name, ctx.defs[def_name]))
    for def_name in _alias_order(ctx):
        body.extend(_render_alias(ctx.kinds[def_name].class_name, ctx.defs[def_name], ctx))
    for def_name in sorted(name for name, info in ctx.kinds.items() if info.kind == "model"):
        body.extend(_render_model(ctx.kinds[def_name].class_name, ctx.defs[def_name], ctx))
    body.extend(
        _render_model(
            ctx.root_name,
            schema,
            ctx,
            extra_docs=(
                f"Root model of contract `{pinned.contract_id}`",
                f"({pinned.category}, version {pinned.contract_version}).",
            ),
        )
    )

    rendered = "\n".join(body)
    imports = ["from dataclasses import dataclass"]
    if "field(default_factory" in rendered:
        imports[0] = "from dataclasses import dataclass, field"
    if "(StrEnum)" in rendered:
        imports.append("from enum import StrEnum")
    imports.append("from collections.abc import Mapping")
    imports.append("from typing import Any")
    imports.sort()

    header = [
        GENERATED_HEADER,
        "#",
        f"# Contract:  {pinned.contract_id} ({pinned.category}, v{pinned.contract_version})",
        f"# Release:   {pin.release.id}",
        f"# Producer:  {pin.source.repository}@{pin.source.commit_sha}",
        f"# Schema:    {pinned.schema_file}",
        f"# Digest:    {pinned.sha256}",
        '"""' + (_doc(schema) or f"Consumer models for {pinned.contract_id}.") + '"""',
        "",
        "from __future__ import annotations",
        "",
        *imports,
        "",
        f'CONTRACT_ID = "{pinned.contract_id}"',
        f'CONTRACT_VERSION = "{pinned.contract_version}"',
        f'CONTRACT_CATEGORY = "{pinned.category}"',
        f'SCHEMA_FILE = "{pinned.schema_file}"',
        f'SCHEMA_SHA256 = "{pinned.sha256}"',
        f'ROOT_MODEL = "{ctx.root_name}"',
        "",
        "",
        "",
    ]
    return "\n".join(header) + rendered


def render_package_init(pin: ContractPin, roots: Mapping[str, str]) -> str:
    """Render `models/__init__.py`: the contract-id -> root-model registry."""
    lines = [
        GENERATED_HEADER,
        "#",
        f"# Release:  {pin.release.id}",
        f"# Producer: {pin.source.repository}@{pin.source.commit_sha}",
        '"""Consumer models generated from the pinned ODay foundation contracts."""',
        "",
        "from __future__ import annotations",
        "",
    ]
    for pinned in sorted(pin.enforced_contracts, key=lambda c: c.module):
        lines.append(f"from .{pinned.module} import {roots[pinned.contract_id]}")
    lines.append("")
    lines.append("CONTRACT_MODELS = {")
    for pinned in pin.enforced_contracts:
        lines.append(f'    "{pinned.contract_id}": {roots[pinned.contract_id]},')
    lines.append("}")
    lines.append("")
    lines.append("__all__ = [")
    lines.append('    "CONTRACT_MODELS",')
    for name in sorted(roots.values()):
        lines.append(f'    "{name}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def render_all(release: FoundationRelease | None = None) -> dict[str, str]:
    """Render every generated file, keyed by path relative to the models root."""
    release = release or load_release()
    pin = release.pin
    rendered: dict[str, str] = {}
    roots: dict[str, str] = {}
    for pinned in pin.enforced_contracts:
        schema = release.schema_for(pinned)
        rendered[f"{pinned.module}.py"] = render_module(pinned, schema, pin)
        roots[pinned.contract_id] = SchemaContext(schema, pinned.module).root_name
    rendered["__init__.py"] = render_package_init(pin, roots)
    return rendered


def check_generated(release: FoundationRelease | None = None) -> list[str]:
    """Return the generated files that differ from what is checked in."""
    release = release or load_release()
    root = release.pin.vendor.generated_root
    expected = render_all(release)
    stale = [
        name
        for name, source in sorted(expected.items())
        if not (root / name).exists() or (root / name).read_text(encoding="utf-8") != source
    ]
    orphans = [
        path.name
        for path in sorted(root.glob("*.py"))
        if path.name not in expected
    ]
    return stale + [f"{name} (no longer generated)" for name in orphans]


def write_generated(release: FoundationRelease | None = None) -> list[str]:
    """Write the generated files; return the paths that changed."""
    release = release or load_release()
    root = release.pin.vendor.generated_root
    root.mkdir(parents=True, exist_ok=True)
    expected = render_all(release)
    changed: list[str] = []
    for name, source in sorted(expected.items()):
        target = root / name
        if not target.exists() or target.read_text(encoding="utf-8") != source:
            target.write_text(source, encoding="utf-8")
            changed.append(name)
    for path in sorted(root.glob("*.py")):
        if path.name not in expected:
            path.unlink()
            changed.append(f"{path.name} (removed)")
    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="Regenerate the checked-in models.")
    group.add_argument("--check", action="store_true", help="Fail if the models are stale.")
    args = parser.parse_args(argv)

    pin = load_pin()
    release = load_release(pin)
    if args.write:
        changed = write_generated(release)
        print(f"Generated {len(render_all(release))} file(s) for {pin.release.id}")
        for name in changed:
            print(f"  updated {name}")
        return 0

    stale = check_generated(release)
    if stale:
        print("Generated foundation client is stale:", file=sys.stderr)
        for name in stale:
            print(f"  - {name}", file=sys.stderr)
        print(
            "Run: uv run python -m packages.oday_data_contracts_client.codegen --write",
            file=sys.stderr,
        )
        return 1
    print(f"Generated foundation client matches {pin.release.id}")
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entrypoint
    raise SystemExit(main())
