"""Synthetic fixtures for the pinned Evidently 0.7.21 drift-monitoring baseline.

This module is the single source of truth for the baseline inputs. Both the
generator (``generate_baseline.py``) and the regression suite
(``tests/models/test_evidently_monitor_baseline.py``) import it, so a golden
file can never describe inputs that differ from the ones the test replays.

Everything here is synthetic and closed-form: no external data provider is
contacted, no NLP corpus or model is downloaded, and no secret or personal data
is used. The only randomness is ``numpy.random.default_rng(RNG_SEED)``, whose
draws are rounded to ``RNG_DECIMALS`` so the recorded fixtures stay readable and
byte-stable.

Case ``routing_expectation`` values name the branch of the Evidently 0.7.21
selector at ``evidently/legacy/calculations/stattests/registry.py::
_get_default_stattest``. They are documentation of intent only -- the assertions
compare against the method that the pinned runtime actually reported, never
against this string.
"""

from __future__ import annotations

import hashlib
import json
import math
import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

import numpy as np
import pandas as pd

RNG_SEED = 20260906
RNG_DECIMALS = 6

#: ``EvidentlyDriftResult.snapshot_id`` falls back to ``f"evidently-{uuid4()}"``.
#: That value is the only non-semantic field in the whole contract, so it is the
#: only thing this baseline is allowed to normalize. See ``normalize_result``.
AUTO_SNAPSHOT_PLACEHOLDER = "<auto-generated-uuid4>"
_AUTO_SNAPSHOT_PATTERN = re.compile(
    r"^evidently-[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
)

NORMALIZATION_POLICY = {
    "normalized": [
        "EvidentlyDriftResult.snapshot_id when the caller passed snapshot_id=None; "
        f"the uuid4 form is verified against a regex and replaced by {AUTO_SNAPSHOT_PLACEHOLDER!r}",
    ],
    "never_normalized": [
        "statistic / p-value / distance values",
        "stat-test method names and thresholds",
        "drift_detected, drifted_columns, drift_share, drifted_column_names",
        "category labels and column names",
        "metric ids, metric ordering and report structure",
        "exception types and messages of validation or runtime failures",
        "caller-supplied snapshot ids, model metadata, cohort and policy version",
    ],
}


@dataclass(frozen=True)
class DriftCase:
    """One reproducible call into ``EvidentlyDriftMonitor``."""

    case_id: str
    kind: str
    description: str
    routing_expectation: str
    reference_rows: tuple[Mapping[str, Any], ...]
    current_rows: tuple[Mapping[str, Any], ...]
    call_kwargs: Mapping[str, Any] = field(default_factory=dict)
    profiled_columns: tuple[str, ...] | None = None
    expects_failure: bool = False

    @property
    def expects_auto_snapshot(self) -> bool:
        return self.kind == "data_drift" and self.call_kwargs.get("snapshot_id") is None


def _sha256_rows(rows: Sequence[Mapping[str, Any]]) -> str:
    payload = json.dumps(list(rows), sort_keys=True, default=repr)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def canonical_json(payload: Any) -> str:
    """Stable serialization used for every golden file and every hash."""

    return json.dumps(payload, sort_keys=True, indent=2, ensure_ascii=False) + "\n"


def _cleaned(series: pd.Series) -> pd.Series:
    """Reproduce Evidently's per-column cleaning before stat-test selection.

    ``evidently/legacy/calculations/data_drift.py:138-149`` replaces +/-inf with
    NaN and drops NaN on both frames before ``get_stattest`` is called, so the
    ``N`` that drives the <=1000 / >1000 branch is the *cleaned* reference size,
    not the raw row count.
    """

    return series.replace([np.inf, -np.inf], np.nan).dropna()


def profile_columns(
    reference_rows: Sequence[Mapping[str, Any]],
    current_rows: Sequence[Mapping[str, Any]],
    columns: Sequence[str] | None = None,
) -> dict[str, dict[str, Any]]:
    """Record the dtypes, cleaned N and merged unique count of every column."""

    if not reference_rows or not current_rows:
        return {}
    reference = pd.DataFrame(list(reference_rows))
    current = pd.DataFrame(list(current_rows))
    names = list(columns) if columns is not None else list(reference.columns)
    names = [name for name in names if name in reference.columns and name in current.columns]
    profile: dict[str, dict[str, Any]] = {}
    for name in names:
        reference_clean = _cleaned(reference[name])
        current_clean = _cleaned(current[name])
        profile[name] = {
            "dtype_reference": str(reference[name].dtype),
            "dtype_current": str(current[name].dtype),
            "raw_reference_n": int(reference[name].shape[0]),
            "raw_current_n": int(current[name].shape[0]),
            "cleaned_reference_n": int(reference_clean.shape[0]),
            "cleaned_current_n": int(current_clean.shape[0]),
            "merged_unique": int(pd.concat([reference_clean, current_clean]).nunique()),
        }
    return profile


def input_receipt(case: DriftCase) -> dict[str, Any]:
    columns = case.profiled_columns
    if columns is None and case.kind != "data_drift":
        columns = tuple(case.call_kwargs.get("prediction_columns", ()) or ())
    return {
        "call_kwargs": json.loads(json.dumps(dict(case.call_kwargs), sort_keys=True, default=repr)),
        "kind": case.kind,
        "description": case.description,
        "routing_expectation": case.routing_expectation,
        "expects_failure": case.expects_failure,
        "reference_row_count": len(case.reference_rows),
        "current_row_count": len(case.current_rows),
        "reference_rows_sha256": _sha256_rows(case.reference_rows),
        "current_rows_sha256": _sha256_rows(case.current_rows),
        "columns": profile_columns(case.reference_rows, case.current_rows, columns or None),
    }


def normalize_result(result: Any, *, expects_auto_snapshot: bool) -> dict[str, Any]:
    """Project an ``EvidentlyDriftResult`` onto the golden contract.

    The only value that changes between two identical runs is the auto-generated
    ``snapshot_id``; it is validated as a uuid4-shaped Evidently id and then
    replaced. Every statistic, threshold, flag and label is passed through
    untouched.
    """

    snapshot_id = result.snapshot_id
    if expects_auto_snapshot:
        if not _AUTO_SNAPSHOT_PATTERN.match(snapshot_id):
            raise AssertionError(
                f"expected an auto-generated evidently-<uuid4> snapshot id, got {snapshot_id!r}"
            )
        snapshot_id = AUTO_SNAPSHOT_PLACEHOLDER
    elif _AUTO_SNAPSHOT_PATTERN.match(snapshot_id):
        raise AssertionError(
            "caller supplied a snapshot id but the result carries an auto-generated one"
        )

    contract = result.to_dict()
    contract["snapshot_id"] = snapshot_id
    return {
        "result": {
            "snapshot_id": snapshot_id,
            "drift_detected": result.drift_detected,
            "drifted_columns": result.drifted_columns,
            "drift_share": result.drift_share,
            "engine": result.engine,
            "reference_snapshot_id": result.reference_snapshot_id,
            "current_snapshot_id": result.current_snapshot_id,
            "model_name": result.model_name,
            "model_version": result.model_version,
            "cohort_key": result.cohort_key,
            "prediction_columns": list(result.prediction_columns),
            "prediction_output_types": (
                dict(result.prediction_output_types)
                if result.prediction_output_types is not None
                else None
            ),
            "drifted_column_names": list(result.drifted_column_names),
            "decision_policy_version_id": result.decision_policy_version_id,
        },
        "to_dict": contract,
        "metrics_index": metrics_index(json.loads(result.report_json)),
    }


def metrics_index(payload: Mapping[str, Any]) -> dict[str, Any]:
    """Flatten the report into the per-column facts §6.3 asks to compare."""

    index: dict[str, Any] = {"drifted_columns_count": None, "columns": {}}
    for metric in payload.get("metrics", []):
        config = metric.get("config", {})
        name = str(metric.get("metric_name", ""))
        if name.startswith("DriftedColumnsCount"):
            index["drifted_columns_count"] = {
                "metric_name": name,
                "id": metric.get("id"),
                "drift_share_argument": config.get("drift_share"),
                "count": metric.get("value", {}).get("count"),
                "share": metric.get("value", {}).get("share"),
            }
            continue
        if "ValueDrift" not in name:
            continue
        index["columns"][str(config.get("column"))] = {
            "metric_name": name,
            "id": metric.get("id"),
            "method": config.get("method"),
            "threshold": config.get("threshold"),
            "value": metric.get("value"),
        }
    return index


def normalize_failure(error: BaseException) -> dict[str, Any]:
    return {
        "exception_type": type(error).__name__,
        "exception_module": type(error).__module__,
        "exception_message": str(error),
    }


def utc_now_iso() -> str:
    return datetime.now(tz=UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def is_close(observed: float, expected: float, *, rel_tol: float, abs_tol: float) -> bool:
    if isinstance(observed, bool) or isinstance(expected, bool):
        return observed is expected
    if math.isnan(float(expected)):
        return math.isnan(float(observed))
    return math.isclose(float(observed), float(expected), rel_tol=rel_tol, abs_tol=abs_tol)


# ---------------------------------------------------------------------------
# Synthetic input builders
# ---------------------------------------------------------------------------

_CATEGORIES_2 = ("north", "south")
_CATEGORIES_3 = ("north", "south", "east")

#: Two disjoint vocabularies, used only to build free-text columns. Both are
#: hand-written English word lists checked into this repository; nothing is
#: fetched and no NLP corpus or tokenizer model is loaded.
_TEXT_VOCABULARY_REFERENCE = (
    "alpha", "beta", "gamma", "delta", "epsilon", "zeta",
    "eta", "theta", "iota", "kappa", "lambda", "sigma",
)
_TEXT_VOCABULARY_CURRENT = (
    "quartz", "vellum", "hollow", "marigold", "tundra", "obsidian",
    "lantern", "fathom", "cinder", "harbor", "thistle", "cobalt",
)


def _numeric_rows(values: Sequence[Any], column: str = "demand") -> tuple[dict[str, Any], ...]:
    return tuple({column: value} for value in values)


def _categorical_rows(values: Sequence[Any], column: str = "region") -> tuple[dict[str, Any], ...]:
    return tuple({column: value} for value in values)


def _text_sentence(vocabulary: Sequence[str], index: int) -> str:
    words = [vocabulary[(index * (offset + 1)) % len(vocabulary)] for offset in range(10)]
    return " ".join(words) + f" unit {index}"


def _text_rows(vocabulary: Sequence[str], count: int, column: str = "note") -> tuple[dict[str, Any], ...]:
    return tuple({column: _text_sentence(vocabulary, index)} for index in range(count))


def _normal_values(count: int, *, loc: float, scale: float, stream: int) -> tuple[float, ...]:
    """Draw from a fixed-seed PCG64 stream and round for a byte-stable fixture."""

    generator = np.random.default_rng([RNG_SEED, stream])
    draws = generator.normal(loc=loc, scale=scale, size=count)
    return tuple(round(float(value), RNG_DECIMALS) for value in draws)


def _prediction_rows(
    values: Sequence[Any],
    *,
    column: str = "prediction",
    cohort: str = "region:north",
    model_name: str = "revenue-model",
    model_version: str = "v1",
    extra: Mapping[str, Sequence[Any]] | None = None,
) -> tuple[dict[str, Any], ...]:
    rows: list[dict[str, Any]] = []
    for index, value in enumerate(values):
        row: dict[str, Any] = {
            column: value,
            "model_name": model_name,
            "model_version": model_version,
            "cohort_key": cohort,
            # Deliberately outside prediction_columns: it must never reach the
            # drift frame, and the baseline records that it does not.
            "entity_id": f"entity-{index}",
        }
        if extra:
            for extra_column, extra_values in extra.items():
                row[extra_column] = extra_values[index]
        rows.append(row)
    return tuple(rows)


def baseline_policy(threshold: float = 0.5) -> Any:
    """A governed ``DecisionPolicy`` carrying the prediction-drift threshold."""

    from shared.governance import DecisionPolicy

    tenant = "00000000-0000-0000-0000-000000000001"
    return DecisionPolicy(
        policy_version_id=f"nltk-monitoring-baseline-policy-v1:{tenant}",
        policy_label="nltk-monitoring-baseline-policy-v1",
        policy_id="nltk-monitoring-baseline-policy",
        policy_version="1.0.0",
        policy_kind="model_performance_drift",
        tenant_id=tenant,
        effective_from=datetime(2026, 9, 1, tzinfo=UTC),
        parameters={"prediction_drift": {"drift_share_threshold": threshold}},
        declared_inputs=("prediction_outputs",),
        change_reason="Pin the prediction-drift threshold for the Evidently 0.7.21 baseline",
        approved_by="model-risk-owner",
        owner_role="ml-governance",
    )


def _prediction_call(
    *,
    output_types: Mapping[str, str] | None,
    columns: Sequence[str] = ("prediction",),
    policy_threshold: float | None = 0.5,
    **overrides: Any,
) -> dict[str, Any]:
    call: dict[str, Any] = {
        "model_name": "revenue-model",
        "model_version": "v1",
        "cohort_key": "region:north",
        "prediction_columns": tuple(columns),
        "output_types": output_types,
        "reference_snapshot_id": "snapshot-reference",
        "current_snapshot_id": "snapshot-current",
        "policy": baseline_policy(policy_threshold) if policy_threshold is not None else None,
    }
    call.update(overrides)
    return call


# ---------------------------------------------------------------------------
# Data-drift cases: EvidentlyDriftMonitor.run
# ---------------------------------------------------------------------------

DATA_DRIFT_CASES: tuple[DriftCase, ...] = (
    DriftCase(
        case_id="numeric_ks_stable",
        kind="data_drift",
        description="200 distinct numeric values, identical reference and current.",
        routing_expectation="N<=1000, Numerical, merged unique>5 -> ks_stat_test",
        reference_rows=_numeric_rows([float(v) for v in range(1, 201)]),
        current_rows=_numeric_rows([float(v) for v in range(1, 201)]),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-numeric-ks-stable"},
    ),
    DriftCase(
        case_id="numeric_ks_drifted",
        kind="data_drift",
        description="Same numeric column shifted by +1000; snapshot_id omitted so the "
        "auto-generated uuid4 path is exercised.",
        routing_expectation="N<=1000, Numerical, merged unique>5 -> ks_stat_test",
        reference_rows=_numeric_rows([float(v) for v in range(1, 201)]),
        current_rows=_numeric_rows([float(v) + 1000.0 for v in range(1, 201)]),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": None},
    ),
    DriftCase(
        case_id="numeric_merged_unique_2_ztest",
        kind="data_drift",
        description="Numeric column whose reference+current union holds exactly 2 values.",
        routing_expectation="N<=1000, Numerical, merged unique<=2 -> z_stat_test",
        reference_rows=_numeric_rows([float(v % 2) for v in range(200)]),
        current_rows=_numeric_rows([float(v % 2) for v in range(200)]),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-unique-2"},
    ),
    DriftCase(
        case_id="numeric_merged_unique_3_chisquare",
        kind="data_drift",
        description="Numeric column at the lower chi-square boundary (merged unique == 3).",
        routing_expectation="N<=1000, Numerical, 2<merged unique<=5 -> chi_stat_test",
        reference_rows=_numeric_rows([float(v % 3) for v in range(200)]),
        current_rows=_numeric_rows([float(v % 3) for v in range(200)]),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-unique-3"},
    ),
    DriftCase(
        case_id="numeric_merged_unique_5_chisquare",
        kind="data_drift",
        description="Numeric column at the upper chi-square boundary (merged unique == 5).",
        routing_expectation="N<=1000, Numerical, 2<merged unique<=5 -> chi_stat_test",
        reference_rows=_numeric_rows([float(v % 5) for v in range(200)]),
        current_rows=_numeric_rows([float(v % 5) for v in range(200)]),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-unique-5"},
    ),
    DriftCase(
        case_id="numeric_merged_unique_6_ks",
        kind="data_drift",
        description="One value past the chi-square boundary (merged unique == 6).",
        routing_expectation="N<=1000, Numerical, merged unique>5 -> ks_stat_test",
        reference_rows=_numeric_rows([float(v % 6) for v in range(200)]),
        current_rows=_numeric_rows([float(v % 6) for v in range(200)]),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-unique-6"},
    ),
    DriftCase(
        case_id="numeric_reference_n_1000_ks",
        kind="data_drift",
        description="Reference cleaned N is exactly 1000, the inclusive small-sample bound.",
        routing_expectation="N<=1000, Numerical, merged unique>5 -> ks_stat_test",
        reference_rows=_numeric_rows([float(v) for v in range(1000)]),
        current_rows=_numeric_rows([float(v) for v in range(1000)]),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-n-1000"},
    ),
    DriftCase(
        case_id="numeric_reference_n_1001_wasserstein",
        kind="data_drift",
        description="One row past the bound (cleaned N == 1001) flips the numeric branch.",
        routing_expectation="N>1000, Numerical, merged unique>5 -> wasserstein_stat_test",
        reference_rows=_numeric_rows([float(v) for v in range(1001)]),
        current_rows=_numeric_rows([float(v) for v in range(1001)]),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-n-1001"},
    ),
    DriftCase(
        case_id="numeric_reference_n_1001_jensenshannon",
        kind="data_drift",
        description="Large sample but low cardinality (merged unique == 4).",
        routing_expectation="N>1000, Numerical, merged unique<=5 -> jensenshannon_stat_test",
        reference_rows=_numeric_rows([float(v % 4) for v in range(1001)]),
        current_rows=_numeric_rows([float(v % 4) for v in range(1001)]),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-n-1001-js"},
    ),
    DriftCase(
        case_id="numeric_nan_cleaned_to_1000_ks",
        kind="data_drift",
        description="1001 raw rows with one missing value; cleaning brings N back to 1000, "
        "so the small-sample branch is selected despite the raw count.",
        routing_expectation="cleaned N<=1000, Numerical, merged unique>5 -> ks_stat_test",
        reference_rows=_numeric_rows([float(v) for v in range(1000)] + [None]),
        current_rows=_numeric_rows([float(v) for v in range(1000)] + [None]),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-nan-1000"},
    ),
    DriftCase(
        case_id="numeric_nan_cleaned_to_1001_wasserstein",
        kind="data_drift",
        description="1002 raw rows with one missing value; cleaned N is 1001.",
        routing_expectation="cleaned N>1000, Numerical, merged unique>5 -> wasserstein_stat_test",
        reference_rows=_numeric_rows([float(v) for v in range(1001)] + [None]),
        current_rows=_numeric_rows([float(v) for v in range(1001)] + [None]),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-nan-1001"},
    ),
    DriftCase(
        case_id="numeric_infinity_cleaned_to_1001_wasserstein",
        kind="data_drift",
        description="+inf in reference and -inf in current are replaced by NaN and dropped, "
        "so they change the routing N without entering any statistic.",
        routing_expectation="cleaned N>1000, Numerical, merged unique>5 -> wasserstein_stat_test",
        reference_rows=_numeric_rows([float(v) for v in range(1001)] + [math.inf]),
        current_rows=_numeric_rows([float(v) for v in range(1001)] + [-math.inf]),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-inf-1001"},
    ),
    DriftCase(
        case_id="numeric_constant_stable_ztest",
        kind="data_drift",
        description="Zero-variance numeric column, unchanged.",
        routing_expectation="N<=1000, Numerical, merged unique<=2 -> z_stat_test",
        reference_rows=_numeric_rows([7.0] * 200),
        current_rows=_numeric_rows([7.0] * 200),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-constant"},
    ),
    DriftCase(
        case_id="numeric_constant_shifted_ztest",
        kind="data_drift",
        description="Zero-variance column that moves to a different constant.",
        routing_expectation="N<=1000, Numerical, merged unique<=2 -> z_stat_test",
        reference_rows=_numeric_rows([7.0] * 200),
        current_rows=_numeric_rows([9.0] * 200),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-constant-shift"},
    ),
    DriftCase(
        case_id="categorical_merged_unique_2_ztest",
        kind="data_drift",
        description="Two-label categorical column, unchanged.",
        routing_expectation="N<=1000, Categorical, merged unique<=2 -> z_stat_test",
        reference_rows=_categorical_rows([_CATEGORIES_2[v % 2] for v in range(200)]),
        current_rows=_categorical_rows([_CATEGORIES_2[v % 2] for v in range(200)]),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-cat-2"},
    ),
    DriftCase(
        case_id="categorical_merged_unique_3_chisquare",
        kind="data_drift",
        description="Three-label categorical column, unchanged.",
        routing_expectation="N<=1000, Categorical, merged unique>2 -> chi_stat_test",
        reference_rows=_categorical_rows([_CATEGORIES_3[v % 3] for v in range(200)]),
        current_rows=_categorical_rows([_CATEGORIES_3[v % 3] for v in range(200)]),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-cat-3"},
    ),
    DriftCase(
        case_id="categorical_reference_n_1001_jensenshannon",
        kind="data_drift",
        description="Categorical column above the 1000-row bound.",
        routing_expectation="N>1000, Categorical -> jensenshannon_stat_test",
        reference_rows=_categorical_rows([_CATEGORIES_3[v % 3] for v in range(1001)]),
        current_rows=_categorical_rows([_CATEGORIES_3[v % 3] for v in range(1001)]),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-cat-1001"},
    ),
    DriftCase(
        case_id="categorical_new_label_chisquare",
        kind="data_drift",
        description="Current window introduces a label absent from the reference window.",
        routing_expectation="N<=1000, Categorical, merged unique>2 -> chi_stat_test",
        reference_rows=_categorical_rows([_CATEGORIES_2[v % 2] for v in range(200)]),
        current_rows=_categorical_rows(
            [(*_CATEGORIES_2, "unseen-west")[v % 3] for v in range(200)]
        ),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-cat-new-label"},
    ),
    DriftCase(
        case_id="mixed_share_meets_threshold",
        kind="data_drift",
        description="One of two numeric columns drifts; drift_share == drift_share_threshold.",
        routing_expectation="N<=1000, Numerical, merged unique>5 -> ks_stat_test on both columns",
        reference_rows=tuple(
            {"demand": float(v), "rent": 100.0 + float(v)} for v in range(1, 201)
        ),
        current_rows=tuple(
            {"demand": float(v) + 1000.0, "rent": 100.0 + float(v)} for v in range(1, 201)
        ),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-share-meets"},
    ),
    DriftCase(
        case_id="mixed_share_below_threshold",
        kind="data_drift",
        description="Identical inputs to mixed_share_meets_threshold with a stricter share "
        "threshold: the dataset verdict flips to False while the column-level drift list "
        "still names the drifted column.",
        routing_expectation="N<=1000, Numerical, merged unique>5 -> ks_stat_test on both columns",
        reference_rows=tuple(
            {"demand": float(v), "rent": 100.0 + float(v)} for v in range(1, 201)
        ),
        current_rows=tuple(
            {"demand": float(v) + 1000.0, "rent": 100.0 + float(v)} for v in range(1, 201)
        ),
        call_kwargs={"drift_share_threshold": 0.6, "snapshot_id": "baseline-share-below"},
    ),
    DriftCase(
        case_id="numeric_gaussian_stable_ks",
        kind="data_drift",
        description="Seeded Gaussian sample, reference and current drawn from the same law.",
        routing_expectation="N<=1000, Numerical, merged unique>5 -> ks_stat_test",
        reference_rows=_numeric_rows(_normal_values(200, loc=50.0, scale=5.0, stream=1)),
        current_rows=_numeric_rows(_normal_values(200, loc=50.0, scale=5.0, stream=2)),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-gauss-stable"},
    ),
    DriftCase(
        case_id="numeric_gaussian_drifted_ks",
        kind="data_drift",
        description="Seeded Gaussian sample whose current window shifts by four sigma.",
        routing_expectation="N<=1000, Numerical, merged unique>5 -> ks_stat_test",
        reference_rows=_numeric_rows(_normal_values(200, loc=50.0, scale=5.0, stream=1)),
        current_rows=_numeric_rows(_normal_values(200, loc=70.0, scale=5.0, stream=3)),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-gauss-drift"},
    ),
    DriftCase(
        case_id="text_percentile_stable",
        kind="data_drift",
        description="High-cardinality free-text column that Evidently infers as ColumnType.Text; "
        "reference and current are identical.",
        routing_expectation="ColumnType.Text, N<=1000 -> perc_text_content_drift_stat_test",
        reference_rows=_text_rows(_TEXT_VOCABULARY_REFERENCE, 200),
        current_rows=_text_rows(_TEXT_VOCABULARY_REFERENCE, 200),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-text-perc-stable"},
    ),
    DriftCase(
        case_id="text_percentile_drifted",
        kind="data_drift",
        description="Same text column rewritten from a disjoint vocabulary.",
        routing_expectation="ColumnType.Text, N<=1000 -> perc_text_content_drift_stat_test",
        reference_rows=_text_rows(_TEXT_VOCABULARY_REFERENCE, 200),
        current_rows=_text_rows(_TEXT_VOCABULARY_CURRENT, 200),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-text-perc-drift"},
    ),
    DriftCase(
        case_id="text_absolute_drifted",
        kind="data_drift",
        description="Text column above the 1000-row bound, rewritten from a disjoint vocabulary.",
        routing_expectation="ColumnType.Text, N>1000 -> abs_text_content_drift_stat_test",
        reference_rows=_text_rows(_TEXT_VOCABULARY_REFERENCE, 1001),
        current_rows=_text_rows(_TEXT_VOCABULARY_CURRENT, 1001),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-text-abs-drift"},
    ),
)


DATA_DRIFT_FAILURE_CASES: tuple[DriftCase, ...] = (
    DriftCase(
        case_id="failure_run_empty_reference_rows",
        kind="data_drift",
        description="The wrapper refuses an empty reference window before Evidently is imported.",
        routing_expectation="first-party guard in EvidentlyDriftMonitor.run",
        reference_rows=(),
        current_rows=_numeric_rows([1.0, 2.0, 3.0]),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-empty-reference"},
        expects_failure=True,
    ),
    DriftCase(
        case_id="failure_run_column_set_mismatch",
        kind="data_drift",
        description="Reference and current carry different column sets.",
        routing_expectation="first-party guard in EvidentlyDriftMonitor.run",
        reference_rows=_numeric_rows([1.0, 2.0, 3.0], column="demand"),
        current_rows=_numeric_rows([1.0, 2.0, 3.0], column="rent"),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-column-mismatch"},
        expects_failure=True,
    ),
    DriftCase(
        case_id="failure_run_all_values_missing",
        kind="data_drift",
        description="Every value in the only column is missing. Cleaning empties both series and "
        "Evidently 0.7.21 raises from inside the stat-test, so this is an unhandled failure of "
        "the pinned engine rather than a first-party validation error. Recorded verbatim.",
        routing_expectation="cleaned N == 0; pinned Evidently 0.7.21 raises",
        reference_rows=_numeric_rows([None] * 200),
        current_rows=_numeric_rows([None] * 200),
        call_kwargs={"drift_share_threshold": 0.5, "snapshot_id": "baseline-all-missing"},
        expects_failure=True,
    ),
)


# ---------------------------------------------------------------------------
# Prediction-drift cases: EvidentlyDriftMonitor.run_prediction
# ---------------------------------------------------------------------------

_STABLE_PREDICTIONS = [float(v) for v in range(1, 101)]
_SHIFTED_PREDICTIONS = [float(v) for v in range(1001, 1101)]
_STABLE_CONFIDENCE = [round(0.5 + (v % 40) / 100.0, 6) for v in range(1, 101)]
_CLASS_LABELS_2 = ["low", "high"]
_CLASS_LABELS_3 = ["low", "high", "urgent"]

PREDICTION_CASES: tuple[DriftCase, ...] = (
    DriftCase(
        case_id="prediction_numeric_stable",
        kind="prediction_drift",
        description="Numeric prediction output, identical reference and current windows.",
        routing_expectation="N<=1000, Numerical, merged unique>5 -> ks_stat_test",
        reference_rows=_prediction_rows(_STABLE_PREDICTIONS),
        current_rows=_prediction_rows(_STABLE_PREDICTIONS),
        call_kwargs=_prediction_call(output_types={"prediction": "numeric"}),
        profiled_columns=("prediction",),
    ),
    DriftCase(
        case_id="prediction_numeric_drifted",
        kind="prediction_drift",
        description="Numeric prediction output shifted by +1000.",
        routing_expectation="N<=1000, Numerical, merged unique>5 -> ks_stat_test",
        reference_rows=_prediction_rows(_STABLE_PREDICTIONS),
        current_rows=_prediction_rows(_SHIFTED_PREDICTIONS),
        call_kwargs=_prediction_call(output_types={"prediction": "numeric"}),
        profiled_columns=("prediction",),
    ),
    DriftCase(
        case_id="prediction_categorical_stable",
        kind="prediction_drift",
        description="Two-class categorical prediction output, unchanged.",
        routing_expectation="N<=1000, Categorical, merged unique<=2 -> z_stat_test",
        reference_rows=_prediction_rows([_CLASS_LABELS_2[v % 2] for v in range(100)]),
        current_rows=_prediction_rows([_CLASS_LABELS_2[v % 2] for v in range(100)]),
        call_kwargs=_prediction_call(output_types={"prediction": "categorical"}),
        profiled_columns=("prediction",),
    ),
    DriftCase(
        case_id="prediction_categorical_new_class_drifted",
        kind="prediction_drift",
        description="Current window emits a class the reference window never produced.",
        routing_expectation="N<=1000, Categorical, merged unique>2 -> chi_stat_test",
        reference_rows=_prediction_rows([_CLASS_LABELS_2[v % 2] for v in range(100)]),
        current_rows=_prediction_rows([_CLASS_LABELS_3[v % 3] for v in range(100)]),
        call_kwargs=_prediction_call(output_types={"prediction": "categorical"}),
        profiled_columns=("prediction",),
    ),
    DriftCase(
        case_id="prediction_mixed_output_types",
        kind="prediction_drift",
        description="One numeric and one categorical output evaluated in the same cohort; only "
        "the numeric one drifts.",
        routing_expectation="ks_stat_test on prediction, z_stat_test on risk_band",
        reference_rows=_prediction_rows(
            _STABLE_PREDICTIONS,
            extra={"risk_band": [_CLASS_LABELS_2[v % 2] for v in range(100)]},
        ),
        current_rows=_prediction_rows(
            _SHIFTED_PREDICTIONS,
            extra={"risk_band": [_CLASS_LABELS_2[v % 2] for v in range(100)]},
        ),
        call_kwargs=_prediction_call(
            columns=("prediction", "risk_band"),
            output_types={"prediction": "numeric", "risk_band": "categorical"},
        ),
        profiled_columns=("prediction", "risk_band"),
    ),
    DriftCase(
        case_id="prediction_inferred_output_types",
        kind="prediction_drift",
        description="output_types omitted; the wrapper infers them from the supplied values.",
        routing_expectation="ks_stat_test on prediction, z_stat_test on risk_band",
        reference_rows=_prediction_rows(
            _STABLE_PREDICTIONS,
            extra={"risk_band": [_CLASS_LABELS_2[v % 2] for v in range(100)]},
        ),
        current_rows=_prediction_rows(
            _STABLE_PREDICTIONS,
            extra={"risk_band": [_CLASS_LABELS_2[v % 2] for v in range(100)]},
        ),
        call_kwargs=_prediction_call(
            columns=("prediction", "risk_band"),
            output_types=None,
        ),
        profiled_columns=("prediction", "risk_band"),
    ),
    DriftCase(
        case_id="prediction_policy_threshold_only",
        kind="prediction_drift",
        description="Half of the outputs drift (share 0.5) against a governed threshold of 0.8, "
        "so the dataset verdict stays False while the drifted column is still named.",
        routing_expectation="ks_stat_test on prediction, ks_stat_test on confidence",
        reference_rows=_prediction_rows(
            _STABLE_PREDICTIONS, extra={"confidence": _STABLE_CONFIDENCE}
        ),
        current_rows=_prediction_rows(
            _SHIFTED_PREDICTIONS, extra={"confidence": _STABLE_CONFIDENCE}
        ),
        call_kwargs=_prediction_call(
            columns=("prediction", "confidence"),
            output_types={"prediction": "numeric", "confidence": "numeric"},
            policy_threshold=0.8,
        ),
        profiled_columns=("prediction", "confidence"),
    ),
    DriftCase(
        case_id="prediction_requested_threshold_tightens_policy",
        kind="prediction_drift",
        description="Identical inputs to prediction_policy_threshold_only, with a caller-supplied "
        "threshold stricter than the policy: 0.4 is accepted and flips the verdict to True.",
        routing_expectation="ks_stat_test on prediction, ks_stat_test on confidence",
        reference_rows=_prediction_rows(
            _STABLE_PREDICTIONS, extra={"confidence": _STABLE_CONFIDENCE}
        ),
        current_rows=_prediction_rows(
            _SHIFTED_PREDICTIONS, extra={"confidence": _STABLE_CONFIDENCE}
        ),
        call_kwargs=_prediction_call(
            columns=("prediction", "confidence"),
            output_types={"prediction": "numeric", "confidence": "numeric"},
            policy_threshold=0.8,
            drift_share_threshold=0.4,
        ),
        profiled_columns=("prediction", "confidence"),
    ),
)


PREDICTION_FAILURE_CASES: tuple[DriftCase, ...] = (
    DriftCase(
        case_id="failure_prediction_requested_threshold_weakens_policy",
        kind="prediction_drift",
        description="A caller-supplied threshold looser than the governed one is rejected.",
        routing_expectation="_effective_drift_share_threshold guard",
        reference_rows=_prediction_rows(_STABLE_PREDICTIONS),
        current_rows=_prediction_rows(_SHIFTED_PREDICTIONS),
        call_kwargs=_prediction_call(
            output_types={"prediction": "numeric"},
            policy_threshold=0.5,
            drift_share_threshold=0.9,
        ),
        profiled_columns=("prediction",),
        expects_failure=True,
    ),
    DriftCase(
        case_id="failure_prediction_no_policy_and_no_threshold",
        kind="prediction_drift",
        description="Neither a policy nor an explicit threshold is supplied.",
        routing_expectation="_effective_drift_share_threshold guard",
        reference_rows=_prediction_rows(_STABLE_PREDICTIONS),
        current_rows=_prediction_rows(_SHIFTED_PREDICTIONS),
        call_kwargs=_prediction_call(
            output_types={"prediction": "numeric"},
            policy_threshold=None,
        ),
        profiled_columns=("prediction",),
        expects_failure=True,
    ),
    DriftCase(
        case_id="failure_prediction_reference_cohort_mismatch",
        kind="prediction_drift",
        description="A reference row belongs to a cohort other than the requested one.",
        routing_expectation="_validate_prediction_rows guard",
        reference_rows=_prediction_rows(_STABLE_PREDICTIONS[:10], cohort="region:south"),
        current_rows=_prediction_rows(_STABLE_PREDICTIONS[:10]),
        call_kwargs=_prediction_call(output_types={"prediction": "numeric"}),
        profiled_columns=("prediction",),
        expects_failure=True,
    ),
    DriftCase(
        case_id="failure_prediction_non_finite_output",
        kind="prediction_drift",
        description="A numeric output carries +inf, which must be refused rather than cleaned "
        "away the way Evidently cleans feature columns.",
        routing_expectation="_validate_prediction_rows guard",
        reference_rows=_prediction_rows(_STABLE_PREDICTIONS[:10]),
        current_rows=_prediction_rows([*(_STABLE_PREDICTIONS[:9]), math.inf]),
        call_kwargs=_prediction_call(output_types={"prediction": "numeric"}),
        profiled_columns=("prediction",),
        expects_failure=True,
    ),
    DriftCase(
        case_id="failure_prediction_missing_output_value",
        kind="prediction_drift",
        description="A current row has no value for the requested output column.",
        routing_expectation="_validate_prediction_rows guard",
        reference_rows=_prediction_rows(_STABLE_PREDICTIONS[:10]),
        current_rows=_prediction_rows([*(_STABLE_PREDICTIONS[:9]), None]),
        call_kwargs=_prediction_call(output_types={"prediction": "numeric"}),
        profiled_columns=("prediction",),
        expects_failure=True,
    ),
    DriftCase(
        case_id="failure_prediction_identical_snapshot_ids",
        kind="prediction_drift",
        description="Reference and current snapshot ids are the same value.",
        routing_expectation="run_prediction snapshot guard",
        reference_rows=_prediction_rows(_STABLE_PREDICTIONS[:10]),
        current_rows=_prediction_rows(_STABLE_PREDICTIONS[:10]),
        call_kwargs=_prediction_call(
            output_types={"prediction": "numeric"},
            reference_snapshot_id="snapshot-same",
            current_snapshot_id="snapshot-same",
        ),
        profiled_columns=("prediction",),
        expects_failure=True,
    ),
    DriftCase(
        case_id="failure_prediction_output_types_do_not_cover_columns",
        kind="prediction_drift",
        description="Declared output types do not exactly match the requested columns.",
        routing_expectation="_normalize_output_types guard",
        reference_rows=_prediction_rows(
            _STABLE_PREDICTIONS[:10],
            extra={"risk_band": [_CLASS_LABELS_2[v % 2] for v in range(10)]},
        ),
        current_rows=_prediction_rows(
            _STABLE_PREDICTIONS[:10],
            extra={"risk_band": [_CLASS_LABELS_2[v % 2] for v in range(10)]},
        ),
        call_kwargs=_prediction_call(
            columns=("prediction", "risk_band"),
            output_types={"prediction": "numeric"},
        ),
        profiled_columns=("prediction", "risk_band"),
        expects_failure=True,
    ),
    DriftCase(
        case_id="failure_prediction_duplicate_columns",
        kind="prediction_drift",
        description="The same output column is requested twice.",
        routing_expectation="_normalize_prediction_columns guard",
        reference_rows=_prediction_rows(_STABLE_PREDICTIONS[:10]),
        current_rows=_prediction_rows(_STABLE_PREDICTIONS[:10]),
        call_kwargs=_prediction_call(
            columns=("prediction", "prediction"),
            output_types={"prediction": "numeric"},
        ),
        profiled_columns=("prediction",),
        expects_failure=True,
    ),
)


ALL_CASES: tuple[DriftCase, ...] = (
    *DATA_DRIFT_CASES,
    *DATA_DRIFT_FAILURE_CASES,
    *PREDICTION_CASES,
    *PREDICTION_FAILURE_CASES,
)


def case_by_id(case_id: str) -> DriftCase:
    for case in ALL_CASES:
        if case.case_id == case_id:
            return case
    raise KeyError(case_id)


def execute(case: DriftCase) -> Any:
    """Run one case against the live pinned Evidently engine."""

    from modules.learninghub.infrastructure import EvidentlyDriftMonitor

    monitor = EvidentlyDriftMonitor()
    if case.kind == "data_drift":
        return monitor.run(
            reference_rows=list(case.reference_rows),
            current_rows=list(case.current_rows),
            **case.call_kwargs,
        )
    return monitor.run_prediction(
        reference_rows=list(case.reference_rows),
        current_rows=list(case.current_rows),
        **case.call_kwargs,
    )
