-- PostgreSQL 16 production runtime persistence for the shared repository bundle.
-- This migration is PostgreSQL-only and intentionally re-runnable.

CREATE SCHEMA IF NOT EXISTS odp_runtime;
SET LOCAL search_path TO odp_runtime, core, public;

CREATE TABLE IF NOT EXISTS odp_runtime.schema_migrations (
    migration_id TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS odp_runtime.durable_sequences (
    name TEXT PRIMARY KEY,
    counter BIGINT NOT NULL DEFAULT 0 CHECK (counter >= 0)
);

CREATE TABLE IF NOT EXISTS odp_runtime.durable_documents (
    collection TEXT NOT NULL,
    doc_id TEXT NOT NULL,
    group_key TEXT,
    seq BIGINT,
    ordinal BIGINT NOT NULL,
    correlation_id TEXT,
    data BYTEA NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (collection, doc_id),
    CHECK (seq IS NULL OR seq > 0),
    CHECK (ordinal > 0)
);
CREATE INDEX IF NOT EXISTS idx_runtime_documents_group
    ON odp_runtime.durable_documents(collection, group_key, seq);
CREATE INDEX IF NOT EXISTS idx_runtime_documents_ordinal
    ON odp_runtime.durable_documents(collection, ordinal);
CREATE UNIQUE INDEX IF NOT EXISTS uq_runtime_documents_group_seq
    ON odp_runtime.durable_documents(collection, group_key, seq)
    WHERE group_key IS NOT NULL AND seq IS NOT NULL;

CREATE TABLE IF NOT EXISTS odp_runtime.operator_comments (
    tenant_id       TEXT NOT NULL,
    comment_id      TEXT NOT NULL,
    target_type     TEXT NOT NULL CHECK (target_type IN ('task', 'decision', 'approval')),
    target_id       TEXT NOT NULL,
    content         TEXT NOT NULL CHECK (char_length(btrim(content)) > 0 AND char_length(content) <= 2000),
    created_by      TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_by      TEXT,
    updated_at      TIMESTAMPTZ,
    edited          SMALLINT NOT NULL DEFAULT 0 CHECK (edited IN (0, 1)),
    edit_count      INTEGER NOT NULL DEFAULT 0 CHECK (edit_count >= 0),
    idempotency_key TEXT,
    correlation_id  TEXT,
    history_json    TEXT NOT NULL DEFAULT '[]',
    PRIMARY KEY (tenant_id, comment_id)
);
CREATE INDEX IF NOT EXISTS idx_runtime_operator_comments_target
    ON odp_runtime.operator_comments(tenant_id, target_type, target_id, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS uq_runtime_operator_comments_idempotency
    ON odp_runtime.operator_comments(tenant_id, created_by, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS odp_runtime.durable_audit_events (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL UNIQUE,
    event_type TEXT NOT NULL,
    actor TEXT NOT NULL,
    action TEXT NOT NULL,
    resource TEXT NOT NULL,
    outcome TEXT NOT NULL,
    correlation_id TEXT NOT NULL,
    job_id TEXT,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL,
    sequence BIGINT,
    previous_hash TEXT,
    event_hash TEXT,
    signature_key_id TEXT,
    signature_version TEXT,
    signature_alg TEXT,
    worm_sink_id TEXT,
    CHECK (sequence IS NULL OR sequence > 0)
);
CREATE INDEX IF NOT EXISTS idx_runtime_audit_correlation
    ON odp_runtime.durable_audit_events(correlation_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_runtime_audit_sequence
    ON odp_runtime.durable_audit_events(sequence)
    WHERE sequence IS NOT NULL;

CREATE TABLE IF NOT EXISTS odp_runtime.durable_jobs (
    job_id TEXT PRIMARY KEY,
    job_type TEXT NOT NULL,
    status TEXT NOT NULL,
    delivery_state TEXT,
    correlation_id TEXT NOT NULL,
    idempotency_key TEXT,
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL,
    fence_token BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 1,
    locked_by TEXT,
    heartbeat_at TIMESTAMPTZ,
    lease_expires_at TIMESTAMPTZ,
    attempts INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    leased_until TIMESTAMPTZ,
    max_retries INTEGER NOT NULL DEFAULT 3,
    CHECK (fence_token >= 0),
    CHECK (version > 0),
    CHECK (attempts >= 0),
    CHECK (max_retries >= 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_runtime_jobs_idempotency
    ON odp_runtime.durable_jobs(idempotency_key)
    WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_runtime_jobs_claim
    ON odp_runtime.durable_jobs(status, created_at);

ALTER TABLE odp_runtime.durable_jobs
    ADD COLUMN IF NOT EXISTS delivery_state TEXT;

CREATE TABLE IF NOT EXISTS odp_runtime.durable_evidence_bundles (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    export_id TEXT NOT NULL UNIQUE,
    program_id TEXT NOT NULL,
    purpose TEXT NOT NULL,
    requested_by TEXT NOT NULL,
    audit_event_id TEXT NOT NULL,
    bundle_checksum TEXT NOT NULL,
    data_classification TEXT NOT NULL,
    sensitive SMALLINT NOT NULL DEFAULT 0 CHECK (sensitive IN (0, 1)),
    export_scope TEXT NOT NULL,
    retention_class TEXT NOT NULL,
    retain_until TIMESTAMPTZ NOT NULL,
    legal_hold SMALLINT NOT NULL DEFAULT 0 CHECK (legal_hold IN (0, 1)),
    generated_at TIMESTAMPTZ NOT NULL,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    correlation_id TEXT NOT NULL,
    bundle_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sequence BIGINT,
    previous_hash TEXT,
    record_hash TEXT,
    signature_key_id TEXT,
    signature_version TEXT,
    signature_alg TEXT,
    worm_sink_id TEXT,
    governance_log_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    governance_hash TEXT,
    purged_at TIMESTAMPTZ,
    tombstone_hash TEXT,
    CHECK (period_end >= period_start)
);
CREATE INDEX IF NOT EXISTS idx_runtime_evidence_program
    ON odp_runtime.durable_evidence_bundles(program_id);
CREATE INDEX IF NOT EXISTS idx_runtime_evidence_correlation
    ON odp_runtime.durable_evidence_bundles(correlation_id);
CREATE INDEX IF NOT EXISTS idx_runtime_evidence_checksum
    ON odp_runtime.durable_evidence_bundles(bundle_checksum);
CREATE INDEX IF NOT EXISTS idx_runtime_evidence_retention
    ON odp_runtime.durable_evidence_bundles(retain_until);
CREATE UNIQUE INDEX IF NOT EXISTS uq_runtime_evidence_sequence
    ON odp_runtime.durable_evidence_bundles(sequence)
    WHERE sequence IS NOT NULL;

CREATE TABLE IF NOT EXISTS odp_runtime.notification_preferences (
    user_id TEXT PRIMARY KEY,
    channels JSONB NOT NULL,
    enabled SMALLINT NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1))
);

CREATE TABLE IF NOT EXISTS odp_runtime.notification_deduplication (
    dedup_key TEXT PRIMARY KEY,
    notification_id TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS odp_runtime.notification_receipts (
    receipt_id TEXT PRIMARY KEY,
    notification_id TEXT NOT NULL,
    channel TEXT NOT NULL,
    status TEXT NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
    last_attempt TIMESTAMPTZ,
    error_message TEXT,
    delivered_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_runtime_notification_receipts
    ON odp_runtime.notification_receipts(notification_id);

CREATE TABLE IF NOT EXISTS odp_runtime.notification_inapp_inbox (
    notification_id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    detail TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'info',
    created_at TIMESTAMPTZ NOT NULL,
    acknowledged SMALLINT NOT NULL DEFAULT 0 CHECK (acknowledged IN (0, 1)),
    acknowledged_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_runtime_notification_inapp_user
    ON odp_runtime.notification_inapp_inbox(user_id);

CREATE TABLE IF NOT EXISTS odp_runtime.durable_outbox_events (
    outbox_event_id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    event_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    event_version INTEGER NOT NULL,
    aggregate_type TEXT NOT NULL,
    aggregate_id TEXT NOT NULL,
    aggregate_version BIGINT NOT NULL,
    partition_key TEXT NOT NULL,
    payload JSONB NOT NULL,
    sensitive_fields JSONB NOT NULL DEFAULT '[]'::jsonb,
    correlation_id TEXT NOT NULL,
    causation_id TEXT,
    occurred_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ,
    publish_attempts INTEGER NOT NULL DEFAULT 0,
    last_error JSONB,
    retention_until TIMESTAMPTZ NOT NULL,
    producer TEXT NOT NULL DEFAULT 'unknown',
    actor_ref TEXT,
    policy_version TEXT,
    schema_ref TEXT NOT NULL DEFAULT 'unassigned',
    published_message_id TEXT,
    available_at TIMESTAMPTZ NOT NULL,
    locked_by TEXT,
    lock_expires_at TIMESTAMPTZ,
    UNIQUE (tenant_id, event_id),
    UNIQUE (
        tenant_id,
        aggregate_type,
        aggregate_id,
        aggregate_version,
        event_type
    ),
    CHECK (event_version > 0),
    CHECK (aggregate_version >= 0),
    CHECK (publish_attempts >= 0)
);
CREATE INDEX IF NOT EXISTS idx_runtime_outbox_unpublished
    ON odp_runtime.durable_outbox_events(available_at, occurred_at)
    WHERE published_at IS NULL;

CREATE TABLE IF NOT EXISTS odp_runtime.durable_manual_corrections (
    correction_id      TEXT PRIMARY KEY,
    entity_type        TEXT NOT NULL,
    entity_id          TEXT NOT NULL,
    tenant_id          TEXT NOT NULL,
    field_name         TEXT NOT NULL,
    old_value_json     TEXT NOT NULL,
    new_value_json     TEXT NOT NULL,
    reason             TEXT NOT NULL CHECK (char_length(btrim(reason)) >= 5),
    actor_id           TEXT NOT NULL,
    occurred_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_revision    INTEGER NOT NULL DEFAULT 1,
    applied_revision   INTEGER NOT NULL DEFAULT 2,
    status             TEXT NOT NULL DEFAULT 'applied' CHECK (status IN ('applied', 'rolled_back')),
    correlation_id     TEXT,
    decision_card_json TEXT,
    audit_event_id     TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_runtime_manual_corrections_entity
    ON odp_runtime.durable_manual_corrections(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_runtime_manual_corrections_tenant
    ON odp_runtime.durable_manual_corrections(tenant_id);
CREATE INDEX IF NOT EXISTS idx_runtime_manual_corrections_correlation
    ON odp_runtime.durable_manual_corrections(correlation_id);

INSERT INTO odp_runtime.schema_migrations(migration_id)
VALUES ('000008_postgresql_runtime_persistence')
ON CONFLICT (migration_id) DO NOTHING;
