# A generic, single database configuration for Alembic.

[alembic]
# path to migration scripts
script_location = infra/db/migrations

# template used to generate new migration files
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date
# timezone = UTC

# max length of characters to use for the slug
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow Alembic to reach
# into the passed connection and determine
# the path to the alembic_version table
# version_locations = %(here)s/versions

# version table name
# version_table = alembic_version

# schema alembic_version table is in
# version_table_schema = None

# set to 'true' to search for newer versions in
# version_locations if they are not active
# search_type = descendants

# set to 'true' to enable the 'bootstrap' command
# bootstrap = false

# logging configuration
# [loggers], [handlers], [formatters] are standard python logging config

[logging]
default = INFO
alembic = INFO
sqlalchemy = WARNING
