import type {
  Approval,
  AuditEvent,
  Candidate,
  Decision,
  EvidenceItem,
  GrowthItem,
  Issue,
  Listing,
  ListingSource,
  NavWorkspace,
  OperatorHeatZone,
  OperatorRole,
  PriceOpsRecommendation,
  RebalanceStore,
  Segment,
  SiteReview,
  Store,
} from "./types";

export const DEMO_NOW = "2026-07-05T08:00:00.000Z";

export const NAV_WORKSPACES: NavWorkspace[] = [
  {
    id: "today",
    label: "Today",
    shortLabel: "Today",
    description: "Role-specific queue, decisions, store risk, and audit feed.",
    order: 1,
    requiredCapability: "workspace:today",
  },
  {
    id: "storeOps",
    label: "Store Ops",
    shortLabel: "Ops",
    description: "Issue workbench for evidence, owner assignment, field action, and outcome review.",
    order: 2,
    requiredCapability: "workspace:storeOps",
  },
  {
    id: "growth",
    label: "Growth",
    shortLabel: "Growth",
    description: "Campaign opportunities, member segments, and PriceOps recommendations.",
    order: 3,
    requiredCapability: "workspace:growth",
  },
  {
    id: "network",
    label: "Network",
    shortLabel: "Network",
    description: "HeatZones, listings, candidate sites, SiteScore, reviews, and rebalance work.",
    order: 4,
    requiredCapability: "workspace:network",
  },
  {
    id: "govern",
    label: "Govern",
    shortLabel: "Govern",
    description: "Approval center, decision log, and audit trail.",
    order: 5,
    requiredCapability: "workspace:govern",
  },
];

export const OPERATOR_ROLES: OperatorRole[] = [
  {
    id: "opsLead",
    label: "營運主管",
    description: "Owns cross-workspace triage, approvals, and operational escalation.",
    defaultWorkspace: "today",
    workspaces: ["today", "storeOps", "growth", "network", "govern"],
    capabilities: [
      "workspace:today",
      "workspace:storeOps",
      "workspace:growth",
      "workspace:network",
      "workspace:govern",
      "issue:triage",
      "issue:assign",
      "issue:execute",
      "issue:close",
      "evidence:camera",
      "review:reply",
      "growth:submitApproval",
      "network:scoreCandidate",
      "network:submitReview",
      "rebalance:submit",
      "approval:decide",
      "audit:read",
    ],
  },
  {
    id: "supportLead",
    label: "客服主管",
    description: "Owns review response, customer cases, and support-side evidence.",
    defaultWorkspace: "today",
    workspaces: ["today", "storeOps", "govern"],
    capabilities: [
      "workspace:today",
      "workspace:storeOps",
      "workspace:govern",
      "issue:triage",
      "issue:assign",
      "review:reply",
      "approval:decide",
      "audit:read",
    ],
  },
  {
    id: "facilitiesLead",
    label: "工務主任",
    description: "Owns field execution, IoT/device evidence, and facilities reports.",
    defaultWorkspace: "today",
    workspaces: ["today", "storeOps"],
    capabilities: [
      "workspace:today",
      "workspace:storeOps",
      "issue:execute",
      "issue:close",
      "evidence:camera",
      "audit:read",
    ],
  },
  {
    id: "marketingManager",
    label: "行銷經理",
    description: "Owns Growth opportunities, campaigns, segments, and PriceOps drafts.",
    defaultWorkspace: "today",
    workspaces: ["today", "growth", "govern"],
    capabilities: [
      "workspace:today",
      "workspace:growth",
      "workspace:govern",
      "growth:draft",
      "growth:submitApproval",
      "approval:decide",
      "audit:read",
    ],
  },
  {
    id: "expansionManager",
    label: "展店經理",
    description: "Owns HeatZone exploration, listings, candidates, and review submissions.",
    defaultWorkspace: "today",
    workspaces: ["today", "network"],
    capabilities: [
      "workspace:today",
      "workspace:network",
      "network:sourceListings",
      "network:scoreCandidate",
      "network:submitReview",
      "rebalance:submit",
      "audit:read",
    ],
  },
  {
    id: "auditPm",
    label: "PM／稽核",
    description: "Owns governance, decision audit, and policy override review.",
    defaultWorkspace: "today",
    workspaces: ["today", "storeOps", "network", "govern"],
    capabilities: [
      "workspace:today",
      "workspace:storeOps",
      "workspace:network",
      "workspace:govern",
      "issue:triage",
      "network:scoreCandidate",
      "approval:decide",
      "audit:read",
    ],
  },
];

export const STORE_FIXTURES: Store[] = [
  {
    id: "ST-008",
    name: "台北信義 A11",
    district: "Xinyi",
    city: "Taipei",
    manager: "Mina Chen",
    lights: {
      demand: "green",
      operations: "red",
      staffing: "yellow",
      margin: "yellow",
    },
    riskScore: 88,
  },
  {
    id: "ST-014",
    name: "台北大安復興",
    district: "Da-an",
    city: "Taipei",
    manager: "Leo Huang",
    lights: {
      demand: "green",
      operations: "yellow",
      staffing: "green",
      margin: "green",
    },
    riskScore: 52,
  },
  {
    id: "ST-021",
    name: "新北板橋文化",
    district: "Banqiao",
    city: "New Taipei",
    manager: "An Lin",
    lights: {
      demand: "yellow",
      operations: "yellow",
      staffing: "red",
      margin: "red",
    },
    riskScore: 79,
  },
];

export const ISSUE_FIXTURES: Issue[] = [
  {
    id: "ISS-1024",
    title: "晚間負評與清潔分數同步惡化",
    storeId: "ST-008",
    storeName: "台北信義 A11",
    status: "new",
    severity: "critical",
    source: "multiSignal",
    ownerRoleId: "opsLead",
    ownerName: "營運主管",
    slaDueAt: "2026-07-05T11:00:00.000Z",
    createdAt: "2026-07-05T06:24:00.000Z",
    updatedAt: "2026-07-05T06:24:00.000Z",
    evidenceIds: ["EV-1024-GR", "EV-1024-CS", "EV-1024-CAM", "EV-1024-IOT", "EV-1024-PAY", "EV-1024-FOUR", "EV-1024-CLN"],
    summary: "Google one-star reviews, CS complaints, and cleaning audit all point to a peak-hour service quality incident.",
  },
  {
    id: "ISS-1021",
    title: "冷氣遠端重啟等待核准",
    storeId: "ST-014",
    storeName: "台北大安復興",
    status: "waitingapproval",
    severity: "high",
    source: "iot",
    ownerRoleId: "facilitiesLead",
    ownerName: "工務主任",
    slaDueAt: "2026-07-05T10:30:00.000Z",
    createdAt: "2026-07-05T04:50:00.000Z",
    updatedAt: "2026-07-05T07:30:00.000Z",
    evidenceIds: ["EV-1021-IOT", "EV-1021-PAY"],
    relatedApprovalId: "APR-502",
    summary: "HVAC telemetry shows repeated compressor fault codes; remote restart needs manager approval before peak traffic.",
  },
  {
    id: "ISS-1008",
    title: "補班日人力不足觀察中",
    storeId: "ST-021",
    storeName: "新北板橋文化",
    status: "observing",
    severity: "medium",
    source: "forecastOps",
    ownerRoleId: "supportLead",
    ownerName: "客服主管",
    slaDueAt: "2026-07-06T03:00:00.000Z",
    createdAt: "2026-07-04T02:10:00.000Z",
    updatedAt: "2026-07-05T01:15:00.000Z",
    evidenceIds: ["EV-1008-FOUR", "EV-1008-CS"],
    summary: "ForecastOps staffing light remains red after shift swap; CS queue is improving but still above baseline.",
  },
];

export const EVIDENCE_FIXTURES: EvidenceItem[] = [
  {
    id: "EV-1024-GR",
    issueId: "ISS-1024",
    kind: "googleReview",
    title: "Google review cluster",
    sourceLabel: "Google Reviews",
    summary: "Three one-star reviews mention sticky tables and slow pickup between 19:00 and 21:00.",
    polarity: "supporting",
    confidence: 0.91,
    occurredAt: "2026-07-04T21:22:00.000Z",
  },
  {
    id: "EV-1024-CS",
    issueId: "ISS-1024",
    kind: "csCase",
    title: "Customer service cases",
    sourceLabel: "Zendesk POC",
    summary: "Two refund requests match the same time window and counter lane.",
    polarity: "supporting",
    confidence: 0.86,
    occurredAt: "2026-07-04T21:44:00.000Z",
  },
  {
    id: "EV-1024-CAM",
    issueId: "ISS-1024",
    kind: "camera",
    title: "Camera event placeholder",
    sourceLabel: "Camera Access",
    summary: "Video access is locked until an operator records a purpose for review.",
    polarity: "neutral",
    confidence: 0.7,
    occurredAt: "2026-07-04T20:05:00.000Z",
    lockedReason: "Purpose confirmation required before camera evidence can be opened.",
  },
  {
    id: "EV-1024-IOT",
    issueId: "ISS-1024",
    kind: "iot",
    title: "Dining-area sensor anomaly",
    sourceLabel: "IoT",
    summary: "Table-zone humidity and waste-bin fill events exceeded normal thresholds.",
    polarity: "supporting",
    confidence: 0.82,
    occurredAt: "2026-07-04T20:12:00.000Z",
  },
  {
    id: "EV-1024-PAY",
    issueId: "ISS-1024",
    kind: "payment",
    title: "Payment queue slowdown",
    sourceLabel: "Payment",
    summary: "Median checkout time rose 34 percent during the complaint window.",
    polarity: "supporting",
    confidence: 0.78,
    occurredAt: "2026-07-04T20:40:00.000Z",
  },
  {
    id: "EV-1024-FOUR",
    issueId: "ISS-1024",
    kind: "forecastOps",
    title: "ForecastOps four-light snapshot",
    sourceLabel: "ForecastOps",
    summary: "Operations light is red; staffing and margin lights are yellow.",
    polarity: "supporting",
    confidence: 0.88,
    occurredAt: "2026-07-05T05:00:00.000Z",
  },
  {
    id: "EV-1024-CLN",
    issueId: "ISS-1024",
    kind: "cleaning",
    title: "Cleaning checklist miss",
    sourceLabel: "Cleaning QA",
    summary: "19:30 lobby reset checklist was not completed before the second dinner wave.",
    polarity: "supporting",
    confidence: 0.8,
    occurredAt: "2026-07-04T19:40:00.000Z",
  },
  {
    id: "EV-1021-IOT",
    issueId: "ISS-1021",
    kind: "iot",
    title: "HVAC compressor code",
    sourceLabel: "IoT",
    summary: "Fault code C-18 repeated four times after 05:00.",
    polarity: "supporting",
    confidence: 0.94,
    occurredAt: "2026-07-05T05:21:00.000Z",
  },
  {
    id: "EV-1021-PAY",
    issueId: "ISS-1021",
    kind: "payment",
    title: "No revenue drop yet",
    sourceLabel: "Payment",
    summary: "Morning payment volume remains inside normal band.",
    polarity: "contrary",
    confidence: 0.72,
    occurredAt: "2026-07-05T07:05:00.000Z",
  },
  {
    id: "EV-1008-FOUR",
    issueId: "ISS-1008",
    kind: "forecastOps",
    title: "Staffing light red",
    sourceLabel: "ForecastOps",
    summary: "Forecast requires two more crew hours between 12:00 and 14:00.",
    polarity: "supporting",
    confidence: 0.84,
    occurredAt: "2026-07-05T01:00:00.000Z",
  },
  {
    id: "EV-1008-CS",
    issueId: "ISS-1008",
    kind: "csCase",
    title: "Support wait improving",
    sourceLabel: "Zendesk POC",
    summary: "Queue wait dropped after shift swap but remains above target.",
    polarity: "neutral",
    confidence: 0.76,
    occurredAt: "2026-07-05T01:10:00.000Z",
  },
];

export const SEGMENT_FIXTURES: Segment[] = [
  {
    id: "SEG-11",
    name: "晚間高頻外帶客",
    size: 18420,
    churnRisk: "medium",
    primaryNeed: "Shorter pickup wait and clear compensation after poor service windows.",
    suggestedGrowthItemId: "GRW-201",
  },
  {
    id: "SEG-24",
    name: "商辦午餐會員",
    size: 9680,
    churnRisk: "low",
    primaryNeed: "Predictable lunch bundles and pickup timing.",
  },
];

export const PRICEOPS_RECOMMENDATION_FIXTURES: PriceOpsRecommendation[] = [
  {
    id: "PIR-301",
    title: "信義晚間組合折扣回補",
    storeIds: ["ST-008"],
    expectedGrossMarginDelta: 1.8,
    status: "draftable",
    suggestedGrowthItemId: "GRW-201",
  },
  {
    id: "PIR-302",
    title: "板橋補班日午餐加價保護",
    storeIds: ["ST-021"],
    expectedGrossMarginDelta: 0.9,
    status: "inReview",
  },
];

export const GROWTH_ITEM_FIXTURES: GrowthItem[] = [
  {
    id: "GRW-201",
    title: "信義晚間服務補償券",
    type: "campaign",
    status: "pending",
    ownerRoleId: "marketingManager",
    storeIds: ["ST-008"],
    segmentId: "SEG-11",
    priceOpsRecommendationId: "PIR-301",
    startAt: "2026-07-06T10:00:00.000Z",
    endAt: "2026-07-13T15:59:59.000Z",
    expectedImpact: "Recover at-risk evening customers while operations issue ISS-1024 is observed.",
    conflictIds: [],
    relatedApprovalId: "APR-501",
  },
  {
    id: "GRW-188",
    title: "大安商辦午餐回訪",
    type: "opportunity",
    status: "candidate",
    ownerRoleId: "marketingManager",
    storeIds: ["ST-014"],
    segmentId: "SEG-24",
    expectedImpact: "Lift repeat purchase among office lunch members.",
    conflictIds: [],
  },
];

export const HEAT_ZONE_FIXTURES: OperatorHeatZone[] = [
  {
    id: "HZ-01",
    label: "信義松仁生活圈",
    rank: 1,
    centroid: [121.5664, 25.0322],
    demandGap: 0.82,
    competitionIndex: 0.46,
    cannibalizationRisk: "medium",
    rentBand: "NT$420k-520k/month",
    confidence: 0.91,
    recommendedLens: "demand",
    reasons: ["Late-night demand gap", "Transit footfall growth", "Delivery order density rising"],
    risks: ["Rent pressure", "Possible overlap with ST-008 evening demand"],
    nextStep: "Review CS-1002 with SiteScore WAIT decision and collect landlord terms.",
  },
  {
    id: "HZ-02",
    label: "大安復興南路",
    rank: 2,
    centroid: [121.5434, 25.0264],
    demandGap: 0.64,
    competitionIndex: 0.58,
    cannibalizationRisk: "high",
    rentBand: "NT$360k-450k/month",
    confidence: 0.78,
    recommendedLens: "cannibalization",
    reasons: ["Strong lunch traffic", "Known brand fit"],
    risks: ["Cannibalization with ST-014", "Narrow storefront supply"],
    nextStep: "Keep tracking but do not submit candidate until cannibalization review improves.",
  },
];

export const LISTING_SOURCE_FIXTURES: ListingSource[] = [
  {
    id: "SRC-591",
    name: "Manual broker intake",
    status: "connected",
    complianceNote: "POC data is manually entered; no unauthorized crawling is implied.",
    lastSyncedAt: "2026-07-05T02:00:00.000Z",
  },
  {
    id: "SRC-592",
    name: "Public listing watch",
    status: "manualOnly",
    complianceNote: "Use source URL evidence only after licensing and consent checks.",
  },
];

export const LISTING_FIXTURES: Listing[] = [
  {
    id: "LST-440",
    sourceId: "SRC-591",
    heatZoneId: "HZ-01",
    address: "台北市信義區松仁路 88 號 1F",
    status: "scored",
    rentPerMonth: 480000,
    areaPing: 41,
    geocodeConfidence: 0.94,
    hardRuleFailures: [],
    candidateId: "CS-1002",
  },
  {
    id: "LST-441",
    sourceId: "SRC-592",
    heatZoneId: "HZ-02",
    address: "台北市大安區復興南路 100 號",
    status: "duplicate",
    rentPerMonth: 390000,
    areaPing: 33,
    geocodeConfidence: 0.86,
    duplicateOfId: "LST-440",
    hardRuleFailures: [],
  },
];

export const CANDIDATE_FIXTURES: Candidate[] = [
  {
    id: "CS-1002",
    listingId: "LST-440",
    heatZoneId: "HZ-01",
    title: "松仁路 88 號候選點",
    address: "台北市信義區松仁路 88 號 1F",
    status: "wait",
    score: 76,
    recommendation: "WAIT",
    modelVersion: "sitescore-v0.9.4",
    datasetSnapshotId: "snap-network-20260705-01",
    missingData: ["Landlord lease term", "Weekend pedestrian count"],
    reviewId: "RV-701",
  },
  {
    id: "CS-1003",
    listingId: "LST-441",
    heatZoneId: "HZ-02",
    title: "復興南路重複候選",
    address: "台北市大安區復興南路 100 號",
    status: "rejected",
    score: 48,
    recommendation: "REJECT",
    modelVersion: "sitescore-v0.9.4",
    datasetSnapshotId: "snap-network-20260705-01",
    missingData: [],
  },
];

export const SITE_REVIEW_FIXTURES: SiteReview[] = [
  {
    id: "RV-701",
    candidateId: "CS-1002",
    status: "pending",
    requestedByRoleId: "expansionManager",
    reviewerRoleIds: ["opsLead", "auditPm"],
    requestedAt: "2026-07-05T05:40:00.000Z",
    reasonRequired: true,
  },
];

export const REBALANCE_STORE_FIXTURES: RebalanceStore[] = [
  {
    id: "RB-801",
    storeId: "ST-021",
    storeName: "新北板橋文化",
    status: "netplanreview",
    avmRequestId: "AVM-611",
    netPlanOptionId: "NPO-2",
    summary: "Low staffing and margin lights suggest evaluating delivery-area rebalance before relocation approval.",
    avmP10: 2340000,
    avmP50: 2860000,
    avmP90: 3420000,
    avmConf: "中高（收益法＋市場比較）",
    avmReserve: "保留價：待房東議價（預估值）",
    netPlanScenarios: [
      {
        name: "Keep / Improve",
        roi: "ROI 8%（改善後）",
        inv: "NT$450K（設備更新＋在地行銷）",
        payback: "18 個月（增量）",
        risk: "中",
        time: "即刻起 90 天",
        isSystemRecommendation: false,
      },
      {
        name: "Move (移轉新址)",
        roi: "ROI 18%（新址預估）",
        inv: "NT$1.9M（移轉＋裝修）",
        payback: "26 個月",
        risk: "中高",
        time: "Q3–Q4 執行",
        isSystemRecommendation: true,
      },
      {
        name: "Exit (關店止損)",
        roi: "年省 NT$1.1M",
        inv: "解約金 NT$180K＋設備移撥",
        payback: "—",
        risk: "低",
        time: "60 天內",
        isSystemRecommendation: false,
      },
    ],
  },
];

export const APPROVAL_FIXTURES: Approval[] = [
  {
    id: "APR-501",
    module: "growth",
    targetType: "growthItem",
    targetId: "GRW-201",
    title: "Approve 信義晚間服務補償券",
    status: "pending",
    risk: "medium",
    requestedByRoleId: "marketingManager",
    requiredRoleIds: ["opsLead", "auditPm"],
    requestedAt: "2026-07-05T06:55:00.000Z",
    systemRecommendation: "Approve with monitoring because ISS-1024 has matching service recovery evidence.",
    modelVersion: "growth-guard-v1.1.0",
    datasetSnapshotId: "snap-growth-20260705-01",
  },
  {
    id: "APR-502",
    module: "storeOps",
    targetType: "issue",
    targetId: "ISS-1021",
    title: "Approve HVAC remote restart",
    status: "pending",
    risk: "high",
    requestedByRoleId: "facilitiesLead",
    requiredRoleIds: ["opsLead", "auditPm"],
    requestedAt: "2026-07-05T07:28:00.000Z",
    systemRecommendation: "Approve before peak if field owner confirms no customer safety risk.",
    modelVersion: "ops-policy-v0.8.7",
    datasetSnapshotId: "snap-ops-20260705-01",
  },
];

export const DECISION_FIXTURES: Decision[] = [
  {
    id: "DEC-401",
    module: "network",
    targetType: "candidate",
    targetId: "CS-1002",
    systemRecommendation: "WAIT for missing landlord terms and weekend pedestrian count.",
    finalDecision: "wait",
    reason: "SiteScore 76 is promising but missing two required evidence fields.",
    actorRoleId: "expansionManager",
    actorName: "展店經理",
    modelVersion: "sitescore-v0.9.4",
    datasetSnapshotId: "snap-network-20260705-01",
    decidedAt: "2026-07-05T05:35:00.000Z",
  },
  {
    id: "DEC-402",
    module: "storeOps",
    targetType: "issue",
    targetId: "ISS-1008",
    systemRecommendation: "Observe for one lunch window after shift swap.",
    finalDecision: "approved",
    reason: "Staffing intervention is already active and CS wait is improving.",
    actorRoleId: "supportLead",
    actorName: "客服主管",
    modelVersion: "ops-policy-v0.8.7",
    datasetSnapshotId: "snap-ops-20260705-01",
    decidedAt: "2026-07-05T01:20:00.000Z",
  },
];

export const AUDIT_EVENT_FIXTURES: AuditEvent[] = [
  {
    id: "AUD-7001",
    occurredAt: "2026-07-05T05:35:00.000Z",
    actorRoleId: "expansionManager",
    actorName: "展店經理",
    category: "workflow",
    action: "candidate.score.wait",
    targetType: "candidate",
    targetId: "CS-1002",
    message: "CS-1002 scored WAIT 76 with SiteScore snapshot snap-network-20260705-01.",
    metadata: {
      score: 76,
      recommendation: "WAIT",
    },
  },
  {
    id: "AUD-7002",
    occurredAt: "2026-07-05T06:55:00.000Z",
    actorRoleId: "marketingManager",
    actorName: "行銷經理",
    category: "approval",
    action: "approval.requested",
    targetType: "approval",
    targetId: "APR-501",
    message: "Growth approval APR-501 was requested for GRW-201.",
    metadata: {
      growthItemId: "GRW-201",
    },
  },
  {
    id: "AUD-7003",
    occurredAt: "2026-07-05T07:28:00.000Z",
    actorRoleId: "facilitiesLead",
    actorName: "工務主任",
    category: "approval",
    action: "approval.requested",
    targetType: "approval",
    targetId: "APR-502",
    message: "Store Ops approval APR-502 was requested for ISS-1021.",
    metadata: {
      issueId: "ISS-1021",
    },
  },
];
