# Generated by delivery_toolchain/governance/generate_vocabularies.py from packages/schemas/canonical/vocabularies.json -- do not edit.
#
# These vocabularies cross the Python / TypeScript / API boundary. Editing a
# copy instead of the source is how the same concept ends up with two
# definitions, which is what this generator exists to stop. Change
# vocabularies.json and re-run with --write.

"""Governed cross-layer vocabularies."""

from __future__ import annotations

from enum import StrEnum


class EvidenceLevel(StrEnum):
    """Causal evidence ladder.

    ADR-0004 D3: absence is not a tier. A value of ``None`` means the evidence was
    never assessed, and it must stay distinguishable from ``L0``, which is a
    measurement -- anecdotal, but taken. No member of this enum may be used as a
    default for an unassessed claim.

    Assessability is orthogonal and travels alongside as a separate boolean; see
    modules/adlift/domain/incrementality.py, where ``assessable`` is a field of its
    own rather than a level.

    Authority: ADR-0004 / ODP-ML-05 §5.
    """

    L0_ANECDOTAL = "L0"  # anecdotal: treatment observed, nothing to compare against
    L1_BEFORE_AFTER = "L1"  # before/after, no control group
    L2_MATCHED_DESCRIPTIVE = "L2"  # matched control but pre-trend/balance not clean
    L3_DID_VALIDATED = "L3"  # control + pre-trend + balance checks pass
    L4_RANDOMIZED = "L4"  # experimental / near-random
    L5_POLICY_READY = "L5"  # replicated, policy ready


class JobStatus(StrEnum):
    """Terminal and in-flight states of a long-running job.

    PARTIAL is the state a job reaches when some of its work succeeded and some did
    not. Without it such a job has to be recorded as either succeeded or failed,
    and both are wrong in a way the caller cannot see.

    Authority: ODP-FR-SHARED-001.
    """

    QUEUED = "queued"  # accepted, not yet started
    RUNNING = "running"  # in flight
    SUCCEEDED = "succeeded"  # all work completed
    FAILED = "failed"  # no work completed
    CANCELLED = "cancelled"  # stopped before completion, deliberately
    PARTIAL = "partial"  # some work completed and some did not; neither succeeded nor failed


class JobDeliveryState(StrEnum):
    """Infrastructure delivery state of a queued job.

    Carried alongside JobStatus rather than inside it, separating queue delivery
    mechanics (such as retries and dead-lettering) from the domain outcome of the
    work itself (queued, running, succeeded, failed, cancelled, partial).

    Authority: ODP-FR-SHARED-001.
    """

    RETRYING = "retrying"  # delivery attempt failed, queued for retry
    DEAD_LETTER = "dead_letter"  # retry budget exhausted or poison message, moved to DLQ


__all__ = [
    "EvidenceLevel",
    "JobDeliveryState",
    "JobStatus",
]
