"""PriceOps public API.

Constrained, auditable price adjustment: safe action set, demand/margin
simulation, optimization, approval, pilot observation, effect evaluation and
rollback (ODP-MOD-06).
"""

from modules.priceops.application import (
    ActivationResult,
    ApprovalBlockedError,
    EvaluationResult,
    MissingRollbackPlanError,
    PlanNotFoundError,
    PriceOpsService,
)
from modules.priceops.domain import (
    DEFAULT_NEGATIVE_IMPACT_THRESHOLD,
    DEFAULT_STOP_CONDITIONS,
    PRICEOPS_FEATURE_VERSION,
    PRICEOPS_MODEL_VERSION,
    PRICEOPS_POLICY_VERSION,
    PRICEOPS_SOLVER_VERSION,
    VALID_TRANSITIONS,
    ApprovalRecord,
    ConstraintViolation,
    InterventionTreatmentHandoff,
    InvalidTransitionError,
    ItemOptimization,
    ItemPlanComparison,
    ItemRevert,
    ItemSimulation,
    LabelRegistryEntry,
    ObservationWindow,
    PlanOptimization,
    PlanSimulation,
    PlanStatus,
    PriceConstraints,
    PriceElasticityEstimate,
    PriceTreatment,
    PricingEffectEvaluation,
    PricingExecution,
    PricingPlan,
    PricingPlanComparison,
    PricingPlanItem,
    RollbackPlan,
    RollbackRecommendation,
    StatusTransition,
    build_observation_window,
    build_rollback_plan,
    count_hard_violations,
    evaluate_effect,
    optimize_item,
    recommended_price_violations,
    simulate_item,
)
from modules.priceops.infrastructure import InMemoryPriceOpsRepository
from modules.priceops.workers import (
    PlanRequest,
    PriceOpsBatchResult,
    PriceOpsOptimizerWorker,
    run_priceops_optimizer_batch,
)

__all__ = [
    "DEFAULT_NEGATIVE_IMPACT_THRESHOLD",
    "DEFAULT_STOP_CONDITIONS",
    "PRICEOPS_FEATURE_VERSION",
    "PRICEOPS_MODEL_VERSION",
    "PRICEOPS_POLICY_VERSION",
    "PRICEOPS_SOLVER_VERSION",
    "VALID_TRANSITIONS",
    "ActivationResult",
    "ApprovalBlockedError",
    "ApprovalRecord",
    "ConstraintViolation",
    "EvaluationResult",
    "InMemoryPriceOpsRepository",
    "InterventionTreatmentHandoff",
    "InvalidTransitionError",
    "ItemOptimization",
    "ItemPlanComparison",
    "ItemRevert",
    "ItemSimulation",
    "LabelRegistryEntry",
    "MissingRollbackPlanError",
    "ObservationWindow",
    "PlanNotFoundError",
    "PlanOptimization",
    "PlanRequest",
    "PlanSimulation",
    "PlanStatus",
    "PriceConstraints",
    "PriceElasticityEstimate",
    "PriceOpsBatchResult",
    "PriceOpsOptimizerWorker",
    "PriceOpsService",
    "PriceTreatment",
    "PricingEffectEvaluation",
    "PricingExecution",
    "PricingPlan",
    "PricingPlanComparison",
    "PricingPlanItem",
    "RollbackPlan",
    "RollbackRecommendation",
    "StatusTransition",
    "build_observation_window",
    "build_rollback_plan",
    "count_hard_violations",
    "evaluate_effect",
    "optimize_item",
    "recommended_price_violations",
    "run_priceops_optimizer_batch",
    "simulate_item",
]
